### ISSUE TITLE
onglet Fichiers : choix du nombre de fichiers à afficher par page

### ISSUE THREAD

**Issue by oliviermarie** [linagora/linshare#1]
Bonjour,

Serait-il possible d'envisager dans les prochaines versions un système où l'utilisateur pourrait choisir le nombre de fichiers à afficher par page dans l'onglet "Fichiers".

En effet, si l'on souhaite partager deux fichiers en même temps et que ces deux fichiers ce trouvent sur des pages différentes on est obligé de réaliser l'opération en deux fois. 

Choisir le nombre de fichiers à afficher par page permettrait dans ce cas de faire en sorte que tous les fichiers apparaissent sur la même page et réaliser un transfert groupé en une seule fois au lieu de deux.

Merci
Olivier

**Comment by fmartin-linagora** [comment]
Bonjour,
La version 1.x est actuellement en maintenance, nous ne faisons plus d'évolutions sur ces versions. Nous nous concentrons sur le développement de la version 2.0 de LinShare.
Toutefois vous avez un contournement disponible : 
1. sélectionnez un fichier via la case à cocher
2. Dans la boite d'action à doite nommée "Actions", cliquez sur 'Partager avec d'autres utilisateurs'. Un panier avec votre fichier devrait apparaitre juste en dessous, nommé 'Partage'.
3. changez de page et recommencez la manoeuvre.
4. Une fois tous le fichiers voulus dans votre panier, vous pouvez cliquer sur le bouton partage.
Cordialement,
