### ISSUE TITLE
Setting up linshare (non docker version)

### ISSUE THREAD

**Issue by arjungprs** [linagora/linshare#100]
Hi, 
Could you please answer this questions. I am looking at the documentations but not getting the big picture.

1. Once we setup the linshare (core, admin-ui, user-ui) how to get started? Where should we create user accounts. I see some ldap integration in admin ui. Is that the only option to create users? Do you have some documentations on how to create ldap for this and link it. 

2. Is there an english version of this documentation: http://download.linshare.org/documentation/admins/Linagora_DOC_LinShare-1.7.0_Guide-Config-Admin_fr_20150303.pdf

3. I setup the linshare without using a docker. What is the test credentials to login to the user-ui application please? I got the admin as :  root@localhost.localdomain/adminlinshare

Thanks

**Comment by fred49** [comment]
Hi,

First of all, LinShare do not handle user management. It is delegated to an LDAP directory like OpenLDAP or Active Directory. LinShare does not provide this part, it requires it. The two main "must have" are a LDAP directory and a smtp relay for outgoing mails.
Once you have an ldap directory, you can setup a link between the LDAP and LinShare. LinShare will discover automatically users from your LDAP. You can use this [paragraph](https://github.com/linagora/linshare-docker/#quick-start) as example to setup the link.

2. No, sorry it is still a work to be done.

3. With the docker-compose installation, we provide a LDAP with test users and the configuration between this ldap and LinShare. It is only for testing purpose. In the standard installation (without docker), we do not provide an LDAP directory. So you will not have users until you provide the LDAP directory. You will only have the root account available.

I hope it will answer you questions and help you.
Fred.

**Comment by arjungprs** [comment]
Thanks alot for clarifying the questions Fred!

**Comment by fmartin-linagora** [comment]
Hi,
There are too mandatory requirements for running LinShare, a LDAP directory to provide users and a smtp server to relay emails.

LinShare does not support the OpenID authentication method.

**Comment by arjungprs** [comment]
Thanks @fmartin-linagora
