### ISSUE TITLE
OpenID Support for SSO

### ISSUE THREAD

**Issue by arjungprs** [linagora/linshare#101]
Hi Team, 
Do you support OpenID to support SSO. 
I am planning to use OpenID for open pass. Also I will have Open pass integrated with linshare as well.
Should I stick to LemonLdap in this case?

Thanks, 
Arjun

**Comment by fmartin-linagora** [comment]
Hi,
We do not support OpenID yet in LinShare. For now, you should keep LemonLDAP.
Fred.

**Comment by arjungprs** [comment]
Hi Fred (@fmartin-linagora )
Please validate my understanding, 
The LemonLDAP will be a front layer for my linshare instance. This will connect with open ID connection on behalf of linshare.  Is that correct? That means I can bring OIDC capability in linshare by having LemonLDAP.
Thanks, 
Arjun

**Comment by fmartin-linagora** [comment]
Hi,
I suppose it is doable, using lemonLDAP to handle OpenID and protect LinShare,  but I never did it. 
Fred

**Comment by fmartin-linagora** [comment]
Hi,
Without any notice, I'm closing this issue . Feel free to reopen it if needed.
Fred
