### ISSUE TITLE
Migration from 2.2.7 to 2.3.0 with AD ldap sql issue

### ISSUE THREAD

**Issue by PhidarkMM** [linagora/linshare#102]
Hello,

we are using linshare on a centos OS, and are migrating from version 2.2.1 to 2.3.3.

We are encountering an error when we upgrade the linshare database with Migration_2.2.0_to_2.3.0.sql:

psql:Migration_2.2.0_to_2.3.0.sql:108: ERROR:  insert or update on table "ldap_attribute" violates foreign key constraint "fkldap_attri49928"
DETAIL:  Key (ldap_pattern_id)=(4) is not present in table "ldap_pattern".
psql:Migration_2.2.0_to_2.3.0.sql:113: ERROR:  current transaction is aborted, commands ignored until end of transaction block
...

Thanks for your help.
[Migration_2.2.0_to_2.3.0.sql.log](https://github.com/linagora/linshare/files/4171385/Migration_2.2.0_to_2.3.0.sql.log)

Regards,
Philippe

**Comment by faycalBordjah** [comment]
Hello,
Thank you for reporting this.
We already had this bug, and had even fix it, but maybe the issue still persist 
 We will investigate about that, and give you a response as soon as possible.
Regards.

**Comment by faycalBordjah** [comment]
Hello
Can you tell me from which LinShare version did you extract the migration script ? 
(because the script that contains the bug fix is [here](http://download.linshare.org/versions/2.3.3/) )
Thanks

**Comment by PhidarkMM** [comment]
Hello,

We are using the 2.3.0 version of the script.
I will give a try to the 2.3.3 of the script and give you a feed back.

Best regards.

**Comment by PhidarkMM** [comment]
Hello again,

it worked perfectly:
BEGIN
SET
SET
SET
SET
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
psql:Migration_2.2.0_to_2.3.0.sql:76: INFO:  Connected to "linshare" with user "linshare"
...
CREATE VIEW
CREATE VIEW
CREATE VIEW
COMMIT

linshare=> select * from version;
  id   | version |       creation_date
-------+---------+----------------------------
     1 | 2.0.0   | 2019-01-08 10:30:37.137584
 17176 | 2.1.0   | 2019-01-08 10:30:37.137584
 18251 | 2.2.0   | 2019-01-08 10:30:37.137584
 21091 | 2.3.0   | 2020-02-10 12:09:34.562724

Thanks a lot for your help.
Best regards
