### ISSUE TITLE
Integrate linshare and openpaas

### ISSUE THREAD

**Issue by ajp2020** [linagora/linshare#104]
Hi, 
I am trying to integrate openpass and linshare. If I login in openpass I don't want to login in linshare again (SSO). How do I achieve this for the users which I created In open pass applications. I don't have an option to use LDAP. It has to be the users who got created in openpass. (open pass maintains the users in mongo db)
Kindly advise.

Thanks

**Comment by fmartin-linagora** [comment]
Hi,
Sorry but the first and main requirement for LinShare is having an LDAP directory. Users in OpenPaas will only be available in OpenPaas.
To achieve the SSO functionality, we usually deploy and LDAP containing all our users and a SSO (LemonLDAP, an opensource sso solution that support many protocol like SAML, OpenID connect, CAS, header injections, ...). Then we setup the link between LinShare and the LDAP directory and finally we protect OpenPaas and LinShare  using this SSO.
Best regards,
Fred.

**Comment by fmartin-linagora** [comment]
Without any feedbacks, I'm closing this issue. Feel free to open it again if needed.
