### ISSUE TITLE
[2.3.3] upgrade tasks issue in centos

### ISSUE THREAD

**Issue by PhidarkMM** [linagora/linshare#105]
Hello,

We are upgrading Linshare to 2.3.3 in production (cf issue # 102) in Centos V7.

The last 2 Upgrade tasks are in Failed state:
UPGRADE_2_3_UPDATE_SHARED_SPACE_NODE_STRUCTURE_FOR_VERSIONING: UPGRADE_TASKS.TASKS.UPGRADE_2_3_UPDATE_SHARED_SPACE_NODE_STRUCTURE_FOR_VERSIONING
02/27/2020 - 8:51:05 AM   INFO    : Task is starting ...
02/27/2020 - 8:51:05 AM   ERROR   : 1/24:Unhandled Exception in batch : org.linagora.linshare.core.upgrade.v2_3.UpdateSharedSpaceNodeStructureForVersioningUpgradeTaskImpl
02/27/2020 - 8:51:05 AM   ERROR   : Critical error for the current task. Task stopped.
02/27/2020 - 8:51:05 AM   ERROR   : Summary : success: 0, skipped: 23, errors: 0, unhandled errors: 1

UPGRADE_2_3_ADD_QUOTA_UUID_TO_ALL_SHARED_SPACES: UPGRADE_TASKS.TASKS.UPGRADE_2_3_ADD_QUOTA_UUID_TO_ALL_SHARED_SPACES
02/27/2020 - 8:39:45 AM   INFO    : Task is starting ...
02/27/2020 - 8:39:45 AM   ERROR   : 1/24:Unhandled Exception in batch : org.linagora.linshare.core.upgrade.v2_3.AddQuotaUuidToAllWorkgroupsUpgradeTaskImpl
02/27/2020 - 8:39:45 AM   ERROR   : Critical error for the current task. Task stopped.
02/27/2020 - 8:39:45 AM   ERROR   : Summary : success: 0, skipped: 23, errors: 0, unhandled errors: 1

Thanks for your help,
best regards

**Comment by marwanJebahi** [comment]
Hello PhidarkMM,

I would like to thank you for your report, the bug of migration script for UPDATE_DOCUMENT_STRUCTURE_FOR_VERSIONING is fixed on LinShare 2.3.1, here is the [changelog](https://github.com/linagora/linshare/blob/master/CHANGELOG.md#231-2019-09-03-download-link)
From which version you like to upgrade to 2.3.3 please?

Regards

**Comment by PhidarkMM** [comment]
Thank you for your quick answer marwanJebahi.

The migration to 2.3.3 is from 2.2.7.

I can go back to 2.2.7 snapshot and upgrade to 2.3.1 first before 2.3.3 ? or do we have to install each 2.3 versions one by one (2.3.0, then 2.3.1, 2.3.2, 2.3.3) ?

Regards

**Comment by marwanJebahi** [comment]
Hello,
Can you send me the log traces please.
Regards

**Comment by PhidarkMM** [comment]
Logs sent by mail.

Regards

**Comment by marwanJebahi** [comment]
Here is the error:
```
[ERROR]:taskExecutor-1:20200227.085105:org.linagora.linshare.core.upgrade.v2_3.UpdateSharedSpaceNodeStructureForVersioningUpgradeTaskImpl:logError:1/24:Unhandled Exception in batch : org.linagora.linshare.core.upgrade.v2_3.UpdateSharedSpaceNodeStructureForVersioningUpgradeTaskImpl
[ERROR]:taskExecutor-1:20200227.085105:org.linagora.linshare.core.runner.impl.BatchRunnerImpl:execute:Query { "$java" : Query: { "uuid" : "" }, Fields: { }, Sort: { } } returned non unique result.
org.springframework.dao.IncorrectResultSizeDataAccessException: Query { "$java" : Query: { "uuid" : "" }, Fields: { }, Sort: { } } returned non unique result.
	at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.oneValue(ExecutableFindOperationSupport.java:145)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.lambda$getExecution$4(AbstractMongoQuery.java:124)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:97)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:602)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:590)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy94.findByUuid(Unknown Source)
	at org.linagora.linshare.core.upgrade.v2_3.UpdateSharedSpaceNodeStructureForVersioningUpgradeTaskImpl.execute(UpdateSharedSpaceNodeStructureForVersioningUpgradeTaskImpl.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy255.execute(Unknown Source)
	at org.linagora.linshare.core.runner.impl.BatchRunnerImpl.execute(BatchRunnerImpl.java:96)
	at org.linagora.linshare.webservice.userv1.task.BatchRunnerAsyncTask.runMyTask(BatchRunnerAsyncTask.java:66)
	at org.linagora.linshare.webservice.userv1.task.BatchRunnerAsyncTask.runMyTask(BatchRunnerAsyncTask.java:44)
	at org.linagora.linshare.webservice.userv1.task.AsyncTask.run(AsyncTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR]:taskExecutor-1:20200227.085105:org.linagora.linshare.core.runner.impl.BatchRunnerImpl:execute:Cannot process resource '' 
[ERROR]:taskExecutor-1:20200227.085105:org.linagora.linshare.core.runner.impl.BatchRunnerImpl:execute:CRITICAL ERROR : Batch stopped !
[ERROR]:taskExecutor-1:20200227.085105:org.linagora.linshare.core.upgrade.v2_3.UpdateSharedSpaceNodeStructureForVersioningUpgradeTaskImpl:logError:Critical error for the current task. Task stopped.
[ERROR]:taskExecutor-1:20200227.085105:org.linagora.linshare.core.upgrade.v2_3.UpdateSharedSpaceNodeStructureForVersioningUpgradeTaskImpl:logError:Summary : success: 0, skipped: 23, errors: 0, unhandled errors: 1
```
Can you execute this command and give me the resule please:
```
db.getCollection('shared_space_nodes').find({"uuid":"a07efaec-98df-472a-88e2-fecb92146ca3"}).pretty()
```

**Comment by PhidarkMM** [comment]
There is no result:
# mongo
MongoDB shell version v3.6.17
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("a95a2460-c2e0-420c-ac6d-378eefa897ba") }
MongoDB server version: 3.6.17
...
> db.getCollection('shared_space_nodes').find({"uuid":"a07efaec-98df-472a-88e2-fecb92146ca3"}).pretty()
>

**Comment by PhidarkMM** [comment]
Sorry here is the result:
> use linshare
switched to db linshare
> db.getCollection('shared_space_nodes').find({"uuid":"a07efaec-98df-472a-88e2-fecb92146ca3"}).pretty()
{
        "_id" : ObjectId("5c419eeb82ce6685d9a4ee83"),
        "_class" : "org.linagora.linshare.mongo.entities.SharedSpaceNode",
        "uuid" : "a07efaec-98df-472a-88e2-fecb92146ca3",
        "name" : "Contrat local de santÃ© du territoire messin 2017-2020",
        "nodeType" : "WORK_GROUP",
        "creationDate" : ISODate("2019-01-18T09:39:55.850Z"),
        "modificationDate" : ISODate("2019-01-18T09:39:55.850Z")
}
{
        "_id" : ObjectId("5e576ae282ce4b1fb243da24"),
        "_class" : "org.linagora.linshare.mongo.entities.SharedSpaceNode",
        "uuid" : "a07efaec-98df-472a-88e2-fecb92146ca3",
        "name" : "Contrat local de santÃ© du territoire messin 2017-2020",
        "nodeType" : "WORK_GROUP",
        "creationDate" : ISODate("2019-01-18T09:39:55.851Z"),
        "modificationDate" : ISODate("2019-01-18T09:39:55.860Z")
}

**Comment by marwanJebahi** [comment]
So here is the problem, when we retrieve the list of `sharedSpaceNodes` to apply the updates of the versioning structure, we get two `sharedSpaceNodes` with the same `uuid` which explain the `IncorrectResultSizeDataAccessException` . 
Have you ever tried to modify data on database with command lines (not through LinShare interface)?
Can you send me please the result of: 

```
db.getCollection('shared_space_members').find({"node.uuid":"a07efaec-98df-472a-88e2-fecb92146ca3"}).pretty();
```

**Comment by marwanJebahi** [comment]
Hello, 
In the list of shared_spaces_members sent, i didn t see some duplicated members when creating a sharedSpace, but i need to check if it is the once sharedSpace (with this `uuid":"a07efaec-98df-472a-88e2-fecb92146ca3`) duplicated or there is some others, so can you please launch this command:
```
db.getCollection('shared_space_nodes').aggregate({ $group: { "_id":{"uuid": "$uuid"}, docCount: { $sum: 1 } } },{ $match: {docCount: { $gt: 1 } } })
```

**Comment by PhidarkMM** [comment]
No, we never changed any data manually on database.
Our update is from version 2.1, throught each intermediate 2.x version and then 2.3.3 version.

Result of the command (with anonymized datas for users, i send you the whole result by mail):
> use linshare
switched to db linshare
> db.getCollection('shared_space_members').find({"node.uuid":"a07efaec-98df-472a-88e2-fecb92146ca3"}).pretty();
{
        "_id" : ObjectId("5c419eeb82ce6685d9a4ee86"),
        "_class" : "org.linagora.linshare.mongo.entities.SharedSpaceMember",
        "uuid" : "fab86038-f81e-4d10-9f84-e2bbb0fd36cd",
        "node" : {
                "uuid" : "a07efaec-98df-472a-88e2-fecb92146ca3",
                "name" : "Contrat local de santÃ© du territoire messin 2017-2020",
                "nodeType" : "WORK_GROUP",
                "creationDate" : ISODate("2019-01-18T09:39:55.850Z"),
                "modificationDate" : ISODate("2019-01-18T09:39:55.850Z")
        },
        "role" : {
                "uuid" : "234be74d-2966-41c1-9dee-e47c8c63c14e",
                "name" : "ADMIN"
        },
        "account" : {
                "uuid" : "045084be-2d9c-4902-a8c2-a71936001763",
                "name" : "F1 L1",
                "firstName" : "F1",
                "lastName" : "L1",
                "mail" : "@mail1"
        },
        "creationDate" : ISODate("2019-01-18T09:39:55.897Z"),
        "modificationDate" : ISODate("2019-01-18T09:39:55.897Z")
}
{
        "_id" : ObjectId("5c41a05682ce6685d9a4ee96"),
        "_class" : "org.linagora.linshare.mongo.entities.SharedSpaceMember",
        "uuid" : "ffd9ff53-db64-49da-ba9c-e2e8f57b0c26",
        "node" : {
                "uuid" : "a07efaec-98df-472a-88e2-fecb92146ca3",
                "name" : "Contrat local de santÃ© du territoire messin 2017-2020",
                "nodeType" : "WORK_GROUP",
                "creationDate" : ISODate("2019-01-18T09:39:55.850Z"),
                "modificationDate" : ISODate("2019-01-18T09:39:55.850Z")
        },
        "role" : {
                "uuid" : "4ccbed61-71da-42a0-a513-92211953ac95",
                "name" : "READER"
        },
        "account" : {
                "uuid" : "d4e45f08-decf-4ad1-901f-2e7067d7d33d",
                "name" : "F2 N2",
                "firstName" : "F2",
                "lastName" : "N2",
                "mail" : "@mail2"
        },
        "creationDate" : ISODate("2019-01-18T09:45:58.498Z"),
        "modificationDate" : ISODate("2019-01-18T09:45:58.498Z")
}
{
        "_id" : ObjectId("5c41a06382ce6685d9a4ee99"),
        "_class" : "org.linagora.linshare.mongo.entities.SharedSpaceMember",
        "uuid" : "d683ae06-f3c7-4b75-8bde-7f19916530b6",
        "node" : {
                "uuid" : "a07efaec-98df-472a-88e2-fecb92146ca3",
                "name" : "Contrat local de santÃ© du territoire messin 2017-2020",
                "nodeType" : "WORK_GROUP",
                "creationDate" : ISODate("2019-01-18T09:39:55.850Z"),
                "modificationDate" : ISODate("2019-01-18T09:39:55.850Z")
        },
        "role" : {
                "uuid" : "4ccbed61-71da-42a0-a513-92211953ac95",
                "name" : "READER"
        },
        "account" : {
                "uuid" : "2d2b9c8e-acff-4aec-8ea7-ef72bd25494d",
                "name" : "F3 L3",
                "firstName" : "F3",
                "lastName" : "L3",
                "mail" : "@mail3"
        },
        "creationDate" : ISODate("2019-01-18T09:46:11.707Z"),
        "modificationDate" : ISODate("2019-01-18T09:46:11.707Z")
}
{
        "_id" : ObjectId("5c41a06f82ce6685d9a4ee9c"),
        "_class" : "org.linagora.linshare.mongo.entities.SharedSpaceMember",
        "uuid" : "08eb7e2a-d49b-454b-a941-dba35a8b82e9",
        "node" : {
                "uuid" : "a07efaec-98df-472a-88e2-fecb92146ca3",
                "name" : "Contrat local de santÃ© du territoire messin 2017-2020",
                "nodeType" : "WORK_GROUP",
                "creationDate" : ISODate("2019-01-18T09:39:55.850Z"),
                "modificationDate" : ISODate("2019-01-18T09:39:55.850Z")
        },
        "role" : {
                "uuid" : "4ccbed61-71da-42a0-a513-92211953ac95",
                "name" : "READER"
        },
        "account" : {
                "uuid" : "edc1513b-6054-406b-bf80-890a4277048a",
                "name" : "F4 L4",
                "firstName" : "F4",
                "lastName" : "L4",
                "mail" : "@mail4"
        },
        "creationDate" : ISODate("2019-01-18T09:46:23.197Z"),
        "modificationDate" : ISODate("2019-01-18T09:46:23.197Z")
}
{
        "_id" : ObjectId("5c41a1d882ce6685d9a4ee9f"),
        "_class" : "org.linagora.linshare.mongo.entities.SharedSpaceMember",
        "uuid" : "c02dce8f-c504-4fb8-bbdf-faaa821880a2",
        "node" : {
                "uuid" : "a07efaec-98df-472a-88e2-fecb92146ca3",
                "name" : "Contrat local de santÃ© du territoire messin 2017-2020",
                "nodeType" : "WORK_GROUP",
                "creationDate" : ISODate("2019-01-18T09:39:55.850Z"),
                "modificationDate" : ISODate("2019-01-18T09:39:55.850Z")
        },
        "role" : {
                "uuid" : "4ccbed61-71da-42a0-a513-92211953ac95",
                "name" : "READER"
        },
        "account" : {
                "uuid" : "ce296b8b-d47b-40e6-9391-ec78df240e23",
                "name" : "F5 L5",
                "firstName" : "F5",
                "lastName" : "L5",
                "mail" : "@mail5"
        },
        "creationDate" : ISODate("2019-01-18T09:52:24.699Z"),
        "modificationDate" : ISODate("2019-01-18T09:52:24.699Z")
}

Regards

**Comment by PhidarkMM** [comment]
Hello,
here is the result of the command:
> db.getCollection('shared_space_nodes').aggregate({ $group: { "_id":{"uuid": "$uuid"}, docCount: { $sum: 1 } } },{ $match: {docCount: { $gt: 1 } } })
{ "_id" : { "uuid" : "a07efaec-98df-472a-88e2-fecb92146ca3" }, "docCount" : 2 }
{ "_id" : { "uuid" : "679d86b7-86c2-4a23-8543-1b7f36445238" }, "docCount" : 2 }
{ "_id" : { "uuid" : "ad509e2e-6299-4777-ac77-270735886c88" }, "docCount" : 3 }

**Comment by marwanJebahi** [comment]
Hello,
There are 3 duplicated `sharedSpaces`, here you can delete the duplication and let one from each and the upgradeTask will run correctly.
Regards

**Comment by PhidarkMM** [comment]
Hello,

All upgrade tasks are OK after deletion thanks a lot.

Steps if it can help:
1) Duplicates 
db.getCollection('shared_space_nodes').aggregate({ $group: { "_id":{"uuid": "$uuid"}, docCount: { $sum: 1 } } },{ $match: {docCount: { $gt: 1 } } })
{ "_id" : { "uuid" : "a07efaec-98df-472a-88e2-fecb92146ca3" }, "docCount" : 2 }
{ "_id" : { "uuid" : "679d86b7-86c2-4a23-8543-1b7f36445238" }, "docCount" : 2 }
{ "_id" : { "uuid" : "ad509e2e-6299-4777-ac77-270735886c88" }, "docCount" : 3 }

2) Duplicate deletion:
db.shared_space_nodes.aggregate([
{ $group: { "_id":{"uuid": "$uuid"}, dups: { "$addToSet": "$_id" }, docCount: { $sum: 1 } } },{ $match: {docCount: { $gt: 1 } } }],
{allowDiskUse: true}      
).forEach(function(doc) {
    doc.dups.shift();     
    db.shared_space_nodes.remove({_id : {$in: doc.dups }});  
})

3) No more duplicate
db.getCollection('shared_space_nodes').find({"uuid":"a07efaec-98df-472a-88e2-fecb92146ca3"}).pretty()
{
        "_id" : ObjectId("5e576ae282ce4b1fb243da24"),
        "_class" : "org.linagora.linshare.mongo.entities.SharedSpaceNode",
        "uuid" : "a07efaec-98df-472a-88e2-fecb92146ca3",
        "name" : "Grp1",
        "nodeType" : "WORK_GROUP",
        "creationDate" : ISODate("2019-01-18T09:39:55.851Z"),
        "modificationDate" : ISODate("2019-01-18T09:39:55.860Z")
}
> db.getCollection('shared_space_nodes').find({"uuid":"679d86b7-86c2-4a23-8543-1b7f36445238"}).pretty()
{
        "_id" : ObjectId("5e576ae282ce4b1fb243da2d"),
        "_class" : "org.linagora.linshare.mongo.entities.SharedSpaceNode",
        "uuid" : "679d86b7-86c2-4a23-8543-1b7f36445238",
        "name" : "Grp2",
        "nodeType" : "WORK_GROUP",
        "creationDate" : ISODate("2019-03-21T13:00:56.768Z"),
        "modificationDate" : ISODate("2019-03-21T13:00:56.772Z")
}
> db.getCollection('shared_space_nodes').find({"uuid":"ad509e2e-6299-4777-ac77-270735886c88"}).pretty()
{
        "_id" : ObjectId("5e576ae282ce4b1fb243d9ed"),
        "_class" : "org.linagora.linshare.mongo.entities.SharedSpaceNode",
        "uuid" : "ad509e2e-6299-4777-ac77-270735886c88",
        "name" : "Grp3",
        "nodeType" : "WORK_GROUP",
        "creationDate" : ISODate("2019-11-12T09:36:06.803Z"),
        "modificationDate" : ISODate("2019-11-12T09:36:26.749Z")
}
> db.getCollection('shared_space_nodes').aggregate({ $group: { "_id":{"uuid": "$uuid"}, docCount: { $sum: 1 } } },{ $match: {docCount: { $gt: 1 } } })
>

Regards
