### ISSUE TITLE
update issue 3.2.0 - maintenance mode

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#108]
Hello,
I had an issue when upgrading to 2.3.4 (from 2.3.1 I think).
I put my domain in maintenance mode before updating but after upload, impossible to disable it.
An error message appear (I didn't note it but it wasn't very explicit).
Fortunatly I did a snapshot before updating.
I do the update again without maintenance mode, it was ok. 

Regards,

**Comment by fmartin-linagora** [comment]
Hi,
It is very weird, there is no database updates (never) when you are upgrading from 2.3.x to 2.3.y.
Without server logs and/or HAR archive from you browser (F12/Network tab), it will be complicated to know what is going on :) 
Regards.

**Comment by fmartin-linagora** [comment]
So, without any feedback I'm closing this issue.
