### ISSUE TITLE
Erreur de connection LDAP active directory

### ISSUE THREAD

**Issue by kreos77** [linagora/linshare#11]
Bonjour, cela fait plusieurs jours que je n'arrive pas a me connecter linshare a mon annuaire LDAP, on ma dit que je doit avoir une erreur dans la déclaration du user provider, mais quesque user provider.

merci

[catalina.2017-11-28.log](https://github.com/linagora/linshare/files/1510383/catalina.2017-11-28.log)
![capture](https://user-images.githubusercontent.com/34066691/33326615-b7a005b2-d455-11e7-9de1-a5ee0505361e.PNG)

**Comment by fmartin-linagora** [comment]
Bonjour,

Dans le menu configuration des domaines, sur un top ou sub domaine vous pouvez configurer le 'Fournisseur d'utilisateurs' avec l'utilisation de votre connexion LDAP et votre filtre.

Cordialement,

**Comment by kreos77** [comment]
Bonjour, je pense l'avoir déjà fait.
![capture3](https://user-images.githubusercontent.com/34066691/33327039-d428c542-d456-11e7-86ce-5f02c6a38188.PNG)

**Comment by fmartin-linagora** [comment]
Le "baseDn" doit être une branche valide dans votre annuaire. J'ai l'impression que vous avez renseigné un dn d'un compte sauf erreur de ma part.

**Comment by kreos77** [comment]
désoler de mon ignorance, je suis vraiment nul sur LDAP, mais par branche vous voulez dire quoi, mon OU?

**Comment by fmartin-linagora** [comment]
Oui, par example 'ou=users,dc=Equancy'

**Comment by kreos77** [comment]
Bonjour, après plusieurs test ma recherche ne fonctionne toujours pas (Erreur de serveur interne), je pense avoir bien configurer le domain mais je pense que  le problème viens du pattern.

![conf-domain](https://user-images.githubusercontent.com/34066691/33424471-401d7976-d5bc-11e7-8eea-c0d23a83d369.PNG)
![pattern1](https://user-images.githubusercontent.com/34066691/33424472-4035adac-d5bc-11e7-8497-673f615cf199.PNG)

**Comment by fmartin-linagora** [comment]
Attention utiliser le filtre objectClass=* est très dangereux car vous allez interroger tous les objects dans l'annuaire.
Le second point concerne la fonction ldap.list, elle recherche des entrées uniquement dans les enfants de votre baseDn (1 seul niveau), si vous voulez que la recherche soit récursive il faut utiliser ldap.search.
Vous pouvez vous inspirer des modèles de filtres par défaut tel que le filtre activeDirectory.

**Comment by kreos77** [comment]
L'ObjectClass doit être un user en particulier ou mon groupe où ce situe mes users? j'ai essayer les deux cela ne fonctionne pas

**Comment by fmartin-linagora** [comment]
Normalement tous les utilisateurs  possèdent un attribut qui permet de déterminer le type de l'entrée dans l'annuaire. Généralement il s'agit de l'objectClass  inetOrgPerson.

**Comment by kreos77** [comment]
Good merci pour les info j'ai réussie à connecter ma base LDAP. Merci de votre aide

**Comment by kreos77** [comment]
je rencontre un problème au niveau de ma connexion a l'interface user, je tombe sur une erreur 404. dois je faire une modification particulière?

**Comment by fmartin-linagora** [comment]
Avez-vous déployé le module LinShare-ui-user ?

**Comment by kreos77** [comment]
j'ai réussie a me debugger désoler de jouer le relou, je vous remercie de toute votre aide, maintenant je recontre un petit bug ([ERROR]:http-nio-8080-exec-7:20171201.142030:org.linagora.linshare.ldap.JScriptLdapQuery:dnToUser:Can not convert dn : 'CN=Issam BEDHIAF' to an user object.), je vais essayer de trouver l'erreur.

enocre une fois merci.

**Comment by kreos77** [comment]
The field 'user_uid' (ldap attribute : 'uid') must exist in your ldap directory, it is required by the system.

**Comment by kreos77** [comment]
le compte root@localhost.localdomain lui fonctionne bien j'arrive à accéder à l'espace de stockage

**Comment by kreos77** [comment]
j'ai rien dit c'est bon, ma connexion fonctionne j'ai réussie a régler le problème. merci de votre aide
