### ISSUE TITLE
Migration 1.12 vers 2.0

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#111]
J'essaie de migrer de la version 1.12 vers 2.0 (visiblement, il n'y a pas de procédure pour passer directement en 2.3). J'ai monté la 2.0.7 sur un nouveau serveur qui fonctionne.
J'applique pour cela la procédure de migration corrigée (il y a des erreurs pour la migration des bdd postgresql : il faut recréer la base puis se connecter à celle-ci avant de restaurer le dump).
La migration des bdd est ok.
1er problème : si dans /etc/default/tomcat8 je remplace la valeur "-Dspring.profiles.active=default,jcloud,mongo" par "-Dspring.profiles.active=default,jackrabbit-to-jcloud,mongo,batches" puis que je redémarre tomcat8, la fenêtre de login n'apparaît pas sur l'interface d'administrateur. j'ai donc mis -Dspring.profiles.active=default,jackrabbit,jcloud,mongo,batches" et je peux alors me connecter. Est-ce une erreur documentaire ou y a-t-il une subtilité ?
Avec cette configuration, je peux alors lancer les tâches de migration.
2ème problème (bloquant) : lorsque je lance UPGRADE_2_2_UPGRADE_STORAGE l'erreur suivante apparaît :  05/13/2020 - 4:49:53 PM   INFO    : Task is starting ...
05/13/2020 - 4:49:53 PM   ERROR   : 1/1537:Unhandled TechnicalException in batch : org.linagora.linshare.core.upgrade.v2_0.FileDataStoreMigrationUpgradeTaskImpl
05/13/2020 - 4:49:53 PM   ERROR   : Critical error for the current task. Task stopped.
05/13/2020 - 4:49:53 PM   ERROR   : Summary : success: 0, skipped: 1536, errors: 0, unhandled errors: 1 
J'ai bien ajouter dans linshare.properties linshare.files.directory=/media/fileshare (répertoire dans lequel sont mes fichiers de la v1)
Ci-joint les lignes de catalina.out correspondantes aux derniers tests 
[catalina.out.txt](https://github.com/linagora/linshare/files/4622796/catalina.out.txt)

**Comment by fmartin-linagora** [comment]
Bonjour,

En effet, vous devez dans un premier temps migrer de la version 1.12 à la version 2.0, puis effectuer toutes les migrations intermédiaires, 2.0 vers 2.1, 2.1 vers 2.2 et enfin 2.2 vers 2.3. 

Les profiles  Jcloud, Jackrabbit et Jackrabbit-to-Jcloud sont exclusifs, il s'agit de profiles qui permettent de configurer comment LinShare stockera les fichiers qui lui sont transmis. Vous avez une petite note explicative dans le fichier de configuration d'exemple de la 2.0, [ici](https://github.com/linagora/linshare-core/blob/maintenance-2.0.x/src/main/resources/linshare.properties.sample).

Si vous n'avez pas la fenetre de login sur l'interface d'administration, il est fort possible que LinShare n'a pas pu démarrer. Il faut donc regarder les logs du serveur tomcat (catalina.out) pour en connaitre la cause.

Dans votre fichier de log, il est possible de voir que la configuration du fileDataStore ne permet pas l'execution de l'upgrade task. Au vu de votre paramétrage "default,jackrabbit,jcloud,mongo,batches", je pense que le profile retenu pour le fileDataStore est jcloud. Lors de la migration de la version 1 vers la version 2, nous devons lire les données dans JackRabbit et les copier dans Jcloud. Pour ce faire, le profil à utiliser est donc jackrabbit-to-jcloud,, soit spring.profiles.active=default,jackrabbit-to-jcloud,mongo,batches

Fred.

**Comment by EPTBSGL** [comment]
Bonjour,
J'ai bien décommenté la ligne "linshare.files.directory=/media/fileshare" (ce répertoire est celui dans lequel les fichiers sont déposés) dans linshare.properties.
Faut-il aussi décommenter celle-ci ? linshare.db.persistence_manager=org.apache.jackrabbit.core.persistence.pool.PostgreSQLPersistenceManager.
Y a-t-il quelque chose à faire pour activer le profil jackrabbit-to-jcloud ? Car c'est lorsque je mets la variable spring.profiles.active=default,jackrabbit-to-jcloud,mongo,batches que je n'ai plus la fenêtre de login pour la plateforme d'administration.
En vous remerciant d'avance,
Philippe NICOLAS

**Comment by fmartin-linagora** [comment]
Bonjour,
Si vous n'avez plus la fenêtre de login, cela signifie que le serveur Tomcat n'as pas réussi à démarrer. Il est possible qu'il y ait des erreurs dans la configuration. Vous devez regarder les logs du serveur pour connaître les raisons de cette erreur.

**Comment by EPTBSGL** [comment]
Etant pris par le temps, nous avons finalement opté pour que les utilisateurs reprennent eux-mêmes leurs données de l'ancienne vers la nouvelle plateforme.
