### ISSUE TITLE
Migration from 1.12 to 2.0

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#112]
I am trying to migrate from version 1.12 to 2.0 (I've not find procedure to go directly to 2.3). I mounted 2.0.7 on a new working server.
I apply for this the corrected migration procedure (there are errors for the migration of postgresql bdd: you must recreate the database then connect to it before restoring the dump).
The migration of bdd is ok.
1st problem: if in / etc / default / tomcat8 I replace the value "-Dspring.profiles.active = default, jcloud, mongo" by "-Dspring.profiles.active = default, jackrabbit-to-jcloud, mongo, batches" then I restart tomcat8, the login window does not appear on the administrator interface. so I put -Dspring.profiles.active = default, jackrabbit, jcloud, mongo, batches  and I can then log in. Is this a document error or is there some subtlety?
With this configuration, I can then launch the migration tasks.
2nd problem (blocking): when I launch UPGRADE_2_2_UPGRADE_STORAGE the following error appears: 05/13/2020 - 4:49:53 PM INFO: Task is starting ...
05/13/2020 - 4:49:53 PM ERROR: 1/1537: Unhandled TechnicalException in batch: org.linagora.linshare.core.upgrade.v2_0.FileDataStoreMigrationUpgradeTaskImpl
05/13/2020 - 4:49:53 PM ERROR: Critical error for the current task. Task stopped.
05/13/2020 - 4:49:53 PM ERROR: Summary: success: 0, skipped: 1536, errors: 0, unhandled errors: 1
I did add in linshare.properties linshare.files.directory = / media / fileshare (directory in which my v1 files are)
Attached are the lines of catalina.out corresponding to the latest tests
[catalina.out.txt](https://github.com/linagora/linshare/files/4642900/catalina.out.txt)

**Comment by fmartin-linagora** [comment]
Hi,
I answered you in french in your first issue [here](https://github.com/linagora/linshare/issues/111).
To sum up, you need to use only one storage profile, and during then upgrade you need to be able to read files store in Jackrabbit to put them in Jcloud. So you must use "-Dspring.profiles.active = default,jackrabbit-to-jcloud,mongo,batches". It is a comma separated list, do not add spaces.

When you do not have LinShare login page on the admin interface, please check LinShare's logs to know why it does not start.
Fred.

**Comment by fmartin-linagora** [comment]
this other issue is closed. I'm closing this issue too
