### ISSUE TITLE
API example

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#114]
Hello,
I'm quite a newby with API and I would like some help with share creation.
I have uploaded a document with API (v1, not v2, the v2 gives me an error 400) but I don't find the way to create the share .
To upload the file I used:
 curl -i -v -X POST http://127.0.0.1:8080/linshare/webservice/rest/user/documents/ -F file=@/path/file -u "user@domain:password" -H "Accept: application/json" -H "Content-Type: multipart/form-data"

the doc indicate:
8..0 create
POST /
Create a share.
URL
http://localhost:8080/linshare/webservice/rest/user/v2/

the url should be http://localhost:8080/linshare/webservice/rest/user/v2/shares/ isn't it?

An example for share creation would be great. My tries gives me a 404 error or 415 if I add /shares/ at the end of the url…

Thanks

**Comment by matdemb** [comment]
after sniffing packets I found how to do for sharing.
For the ones who want the information:
curl -i -v -X POST http://127.0.0.1:8080/linshare/webservice/rest/user/v2/shares/  -d '{
"documents" : ["uuidGivenWhenUploading"],
"expirationDate" : "{timestamp}", //optional
"recipients" : [{"mail" : "RecipientMail"}],
"subject":"EmailSubject",
"message":"Emailmessage"
}' -u 'connectionEmail:Password' -H "Accept: application/json" -H  "Content-Type: application/json"

But I still can't upload file by API V2. 
The request is probably different than in V1…

**Comment by tolstoyfafa** [comment]
Hello, 
- Indeed the URL to create a Share is `http://localhost:8080/linshare/webservice/rest/user/v2/shares/`
Here is an example to make a share on LinShare API 

```bash
curl -X POST '{your_host}/linshare/webservice/rest/user/v2/shares' -u "user1@linshare.org:password1" -H "Accept: application/json" -H "Content-Type: application/json" -d '{
  "recipients": [
    {
      "firstName": "Twist",
      "lastName": "Oliver",
      "domain": "{your_domain_uuid}",
      "mail": "recipient_uuid"
    }
  ],
  "documents": [
    "{document_uuid}"
  ],
  "mailingListUuid": [],
  "secured": true,
  "creationAcknowledgement": true,
  "expirationDate": 1598565599999,
  "enableUSDA": true,
  "notificationDateForUSDA": 1590938422780,
  "sharingNote": "",
  "subject": "{your_mail_subject}",
  "message": "{your_mail_content}"
}'
```

**Comment by matdemb** [comment]
thanks, your response is more precise.

**Comment by tolstoyfafa** [comment]
Re,
About upload file on API v2:
```bash
curl -i -u "login:password" http://<server>/linshare/webservice/rest/user/v2/documents 
-X POST -H "Content-Type: multipart/form-data"
 -F"file=@/path/to/file"  -F"filesize= xxx"
```

**Comment by matdemb** [comment]
yes! thank you!

**Comment by fmartin-linagora** [comment]
For the record, When you are sharing a document, the only required field in the recipient object is the mail address. Other fields are just useless.
