### ISSUE TITLE
Prévisualisation

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#115]
Bonjour,
Je n'arrive pas à faire fonctionner la prévisualisation des fichiers déposés sur linshare. J'ai pourtant LibreOffice installé sur le serveur et suivi votre documentation. Si je clique sur "Détail" à côté du fichier, le cadre prévu pour l'aperçu affiche "Aucune prévisualisation", que le fichier soit en pdf ou en word (docx). Pour info, je fais les tests avec linshare-core 2.3.5 sur un serveur Debian 9.

**Comment by fmartin-linagora** [comment]
Bonjour,
Lors du dépôt d'un fichier, l'aperçu est pas généré. Si le moteur d'aperçu, n'est pas disponible à ce moment, l'aperçu n'est pas généré. Puis que LinShare dé-duplique les fichiers déposés, l’aperçu n'est pas régénéré lors que vous redéposez le même fichier. l'unicité du fichier fichier est calculé grâce à une fonction de hashage  SHA256.

Avez-vous bien installé le générateur d'aperçu ([cf](https://github.com/linagora/linshare/blob/master/documentation/FR/installation/linshare-install-debian.md#thumbnail)) ? 

Vous pouvez tester le service via les commandes que vous trouverez [ici](https://github.com/linagora/linshare-thumbnail-server-dockerfile#test).

**Comment by EPTBSGL** [comment]
Je vous remercie pour votre réponse rapide. Je viens de voir que la doc n'est pas conforme : il est dit de créer le fichier .service dans /etc/systemd/system/ alors qu'il faut le créer dans /lib/systemd/system pour que la commande "enable" crée le lien symbolique. Cela n'a toutefois pas réglé le problème. Je n'aurais malheureusement le temps de tester tout ça qu'à mon retour de congé (dans 3 semaines).

**Comment by marwanJebahi** [comment]
Hello,
I would like to thank you for your remark,
we will check the issue and update the documentation if needed.
Regards

**Comment by marwanJebahi** [comment]
Hello, 

The preview process of LinShare is computed when uploading the file, so if the file is uploaded and the service is not activated, you won't be able to preview it.
So i advice you to enable the `linshare-thumbnail-server.service`, then upload a new file, that was not uploaded before, and re-try the preview.
If you still have the same issue, please send me the Tomcat log traces.

Regards

**Comment by EPTBSGL** [comment]
Bonjour,

J'ai constaté que dans mon fichier /lib/systemd/system/linshare-thumbnail-server.service j'avais écrit : ExecStart=/usr/bin/java -jar /usr/local/sbin/linshare-thumbnail-server.jar /etc/linshare/linshare-thumbnail-server.yml au lieu de ExecStart=/usr/bin/java -jar /usr/local/sbin/linshare-thumbnail-server.jar **server** /etc/linshare/linshare-thumbnail-server.yml
(il manquait "server").
J'ai corrigé, redémarré le service et j'ai bien la génération des aperçus.
Je vous remercie pour vos réponses et clos le ticket.
