### ISSUE TITLE
upload invitation

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#116]
Hello, 
I saw in a previous version that when the administrator logged in user UI, he had a menu named "upload invitation" (something like that) but that wasn't operationnal.
Is it a functionality that will be available soon.
It's something that interest us. 
The usage of guest account is quite "complicated" for just deposit a file in one shot (create the account, validate, send file, share it,...).
It would be great to have this.
Thanks.

**Comment by fmartin-linagora** [comment]
Hello,
We plan to release LinShare 4.0 during July, it will contains a lot of technical upgrades especially Java 11 usage and security enhancements like account lockout and second factor authentication. Then we will start working on the upload request (Invitation de dépot), I can't give you a release date but I hope we will be able to deliver LinShare 4.1 for the last quarter of this year.
Regards.

**Comment by matdemb** [comment]
Hello,
good news.
Can't wait to see that.
Regards,
