### ISSUE TITLE
new clean installation not working, problem tomcat9

### ISSUE THREAD

**Issue by alfred194** [linagora/linshare#117]
Hello

i've installed the latest version 2.3.5 of LinShare on a new server Ubuntu 18.04.4 LTS
so all is new (the OS + LinShare)
openjdk-11-jdk
tomcat9

i followed exactly step by step the documentation for the installation
[https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-debian.md](url)

when i try to access the admin gui i get (the service is currently unavailable)(HTTP code 503)
when i checked the status of tomcat9 i found it in failed state

>● tomcat9.service - Apache Tomcat 9 Web Application Server
   Loaded: loaded (/lib/systemd/system/tomcat9.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-06-21 18:53:31 UTC; 2min 41s ago
     Docs: https://tomcat.apache.org/tomcat-9.0-doc/index.html
  Process: 2531 ExecStart=/bin/sh /usr/libexec/tomcat9/tomcat-start.sh (code=exited, status=1/FAILURE)
  Process: 2516 ExecStartPre=/usr/libexec/tomcat9/tomcat-update-policy.sh (code=exited, status=0/SUCCESS)
 Main PID: 2531 (code=exited, status=1/FAILURE)
Jun 21 18:53:31 linshare systemd[1]: Starting Apache Tomcat 9 Web Application Server...
Jun 21 18:53:31 linshare systemd[1]: Started Apache Tomcat 9 Web Application Server.
Jun 21 18:53:31 linshare tomcat9[2531]: NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Jun 21 18:53:31 linshare tomcat9[2531]: Error: Could not find or load main class ${JAVA_OPTS}
Jun 21 18:53:31 linshare tomcat9[2531]: Caused by: java.lang.ClassNotFoundException: ${JAVA_OPTS}
Jun 21 18:53:31 linshare systemd[1]: tomcat9.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 18:53:31 linshare systemd[1]: tomcat9.service: Failed with result 'exit-code'.
 
in /etc/default/tomcat9, i have

> JAVA_OPTS="-Djava.awt.headless=true -XX:+UseG1GC"
JAVA_OPTS="${JAVA_OPTS} -Djava.awt.headless=true -Xms512m -Xmx2048m"
JAVA_OPTS="${JAVA_OPTS} -Dlinshare.config.path=file:/etc/linshare/"
JAVA_OPTS="${JAVA_OPTS} -Dlog4j.configuration=file:/etc/linshare/log4j.properties"
JAVA_OPTS="${JAVA_OPTS} -Dspring.profiles.active=default,jcloud,batches"

the first line is the default one, the 4 others are from /etc/linshare/linshare.properties and /etc/linshare/log4j.properties as instructed
if i remove or comment the 4 last lines added (JAVA_OPTS="${JAVA_OPTS} -...), tomcat9 service works and can be started in the active state

i tried to comment the 4 lines and uncomment one by one, to find the one(s) causing error without luck, tomcat9 service won't start with any of the 4 lines
so only the default tomcat9 configuration works, so LinShare not working with tomcat9

any help ?

Thanks

**Comment by fmartin-linagora** [comment]
Hi,
The default installation [guide](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-debian.md) was updated for LinShare 4.0. As you see just after the summary you have a list of installation guide per version. You are looking for 2.3 guide available [here](https://github.com/linagora/linshare/blob/maintenance-2.3.x/documentation/EN/installation/linshare-install-debian.md).
There is a glitch in the current guide, the 2.3 link is referring to master instead of maintenance-2.3.x branch. I will fix it asap.
Regards.

**Comment by alfred194** [comment]
Hi
OK thank you
where i can find the version 4.0 ?
it isn't available for download (http://download.linshare.org/versions), nothing about the version 4.0 in this URL
Thanks

**Comment by fmartin-linagora** [comment]
Hi,
It is not yet available. We plan to release it during July.
For now LinShare 2.3 is the latest stable version.
Regards

**Comment by alfred194** [comment]
Thanks a lot
