### ISSUE TITLE
no authentication for admin gui

### ISSUE THREAD

**Issue by alfred194** [linagora/linshare#118]
Hello

i've installed the latest version 2.3.5 of LinShare on a new server Ubuntu 18.04.4 LTS
so all is new (the OS + LinShare)
openjdk-8-jdk
tomcat8

i followed exactly step by step the documentation for the installation
[https://github.com/linagora/linshare/blob/maintenance-2.3.x/documentation/EN/installation/linshare-install-debian.md](url)

i added both (linshare-admin.local) (linshare-user.local) entries to my hosts file

when i access http://linshare-admin.local, there is nothing where to authenticate, absolutely nothing, there is no form and no popup window for authentication

where i have to authenticate to enter the admin gui ?

Thanks

catalina.out

> 22-Jun-2020 18:33:49.354 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.357 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.358 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.358 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.361 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.361 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.362 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.362 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.362 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.362 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.363 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.363 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
22-Jun-2020 18:33:49.878 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.39 (Ubuntu)
22-Jun-2020 18:33:49.878 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 9 2019 19:47:51 UTC
22-Jun-2020 18:33:49.878 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.39.0
22-Jun-2020 18:33:49.878 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
22-Jun-2020 18:33:49.878 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-106-generic
22-Jun-2020 18:33:49.878 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
22-Jun-2020 18:33:49.878 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
22-Jun-2020 18:33:49.879 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_252-8u252-b09-1~18.04-b09
22-Jun-2020 18:33:49.879 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Private Build
22-Jun-2020 18:33:49.879 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat8
22-Jun-2020 18:33:49.879 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
22-Jun-2020 18:33:49.879 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
22-Jun-2020 18:33:49.879 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
22-Jun-2020 18:33:49.879 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseConcMarkSweepGC
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512m
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2048m
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlinshare.config.path=file:/etc/linshare/
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlog4j.configuration=file:/etc/linshare/log4j.properties
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
22-Jun-2020 18:33:49.880 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat8
22-Jun-2020 18:33:49.881 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
22-Jun-2020 18:33:49.881 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp
22-Jun-2020 18:33:49.881 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.3].
22-Jun-2020 18:33:49.881 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
22-Jun-2020 18:33:49.881 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
22-Jun-2020 18:33:49.884 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1  11 Sep 2018]
22-Jun-2020 18:33:49.955 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
22-Jun-2020 18:33:49.990 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
22-Jun-2020 18:33:50.028 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 634 ms
22-Jun-2020 18:33:50.058 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
22-Jun-2020 18:33:50.058 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.39 (Ubuntu)
22-Jun-2020 18:33:50.066 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/var/lib/tomcat8/webapps/ROOT]
22-Jun-2020 18:33:51.367 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
22-Jun-2020 18:33:51.415 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/var/lib/tomcat8/webapps/ROOT] has finished in [1,349] ms
22-Jun-2020 18:33:51.418 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
22-Jun-2020 18:33:51.426 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 1388 ms

**Comment by marwanJebahi** [comment]
Hello,

When you don't have the authentication on ui-admin, it is possible that the backed is not well started,
in this log traces i don t see any logs of linShare, can you restart your tomcat server and sent me the traces please.

Regards.

**Comment by alfred194** [comment]
Hi

> systemctl stop apache2
systemctl stop tomcat8
systemctl stop postgresql
rm /var/log/tomcat8/*
rm /var/log/apache2/*
rm /var/log/postgresql/*
systemctl start postgresql
systemctl start tomcat8
systemctl start apache2

/var/log/tomcat8/catalina.out

> 23-Jun-2020 08:42:03.208 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.212 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.213 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.213 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.216 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.216 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.217 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.217 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.217 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.217 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.219 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.219 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
23-Jun-2020 08:42:03.756 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.39 (Ubuntu)
23-Jun-2020 08:42:03.757 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 9 2019 19:47:51 UTC
23-Jun-2020 08:42:03.757 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.39.0
23-Jun-2020 08:42:03.757 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
23-Jun-2020 08:42:03.757 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-106-generic
23-Jun-2020 08:42:03.757 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
23-Jun-2020 08:42:03.758 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
23-Jun-2020 08:42:03.758 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_252-8u252-b09-1~18.04-b09
23-Jun-2020 08:42:03.758 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Private Build
23-Jun-2020 08:42:03.758 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat8
23-Jun-2020 08:42:03.759 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
23-Jun-2020 08:42:03.759 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
23-Jun-2020 08:42:03.759 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
23-Jun-2020 08:42:03.759 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
23-Jun-2020 08:42:03.760 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseConcMarkSweepGC
23-Jun-2020 08:42:03.760 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
23-Jun-2020 08:42:03.760 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512m
23-Jun-2020 08:42:03.760 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2048m
23-Jun-2020 08:42:03.760 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlinshare.config.path=file:/etc/linshare/
23-Jun-2020 08:42:03.761 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlog4j.configuration=file:/etc/linshare/log4j.properties
23-Jun-2020 08:42:03.761 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
23-Jun-2020 08:42:03.761 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
23-Jun-2020 08:42:03.761 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
23-Jun-2020 08:42:03.761 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
23-Jun-2020 08:42:03.762 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat8
23-Jun-2020 08:42:03.762 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
23-Jun-2020 08:42:03.762 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp
23-Jun-2020 08:42:03.762 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.3].
23-Jun-2020 08:42:03.763 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
23-Jun-2020 08:42:03.763 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
23-Jun-2020 08:42:03.766 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1  11 Sep 2018]
23-Jun-2020 08:42:03.842 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
23-Jun-2020 08:42:03.866 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
23-Jun-2020 08:42:03.887 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 620 ms
23-Jun-2020 08:42:03.914 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
23-Jun-2020 08:42:03.914 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.39 (Ubuntu)
23-Jun-2020 08:42:03.922 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/var/lib/tomcat8/webapps/ROOT]
23-Jun-2020 08:42:04.832 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
23-Jun-2020 08:42:04.876 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/var/lib/tomcat8/webapps/ROOT] has finished in [954] ms
23-Jun-2020 08:42:04.879 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
23-Jun-2020 08:42:04.887 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 992 ms

Thanks

**Comment by marwanJebahi** [comment]
Hi,
Can you please attach all log file, because in the traces which you have sent, i don't see any LinShare traces, and avoid to delete logs please.
regards

**Comment by alfred194** [comment]
Hi
it's the whole files, the whole content pasted, nothing left
i stopped postgresql, tomcat and apache then restarted them
i also change apache LogLevel to debug
please see attachment
Thanks

[linshare-2.3.5.zip](https://github.com/linagora/linshare/files/4819618/linshare-2.3.5.zip)

**Comment by alfred194** [comment]
Hi

any help please ?
i really would like to test and use LinShare, but till now, nothing works

Thanks

**Comment by fred49** [comment]
Hi,
Can you run the following command and send back the result ?  `ls  -l /var/lib/tomcat8/webapps`

**Comment by alfred194** [comment]
total 141708
drwxr-x--- 4 tomcat8 tomcat8      4096 Jun 22 10:15 linshare
-rw-r--r-- 1 root    root    145092624 Jun 22 10:15 linshare.war
drwxr-xr-x 3 root    root         4096 Jun 22 17:18 ROOT

**Comment by fred49** [comment]
`cat /etc/default/tomcat8`

**Comment by alfred194** [comment]
> # Run Tomcat as this user ID. Not setting this or leaving it blank will use the
# default of tomcat8.
TOMCAT8_USER=tomcat8

# Run Tomcat as this group ID. Not setting this or leaving it blank will use
# the default of tomcat8.
TOMCAT8_GROUP=tomcat8

# The home directory of the Java development kit (JDK). You need at least
# JDK version 8. If JAVA_HOME is not set, some common directories for
# OpenJDK and the Oracle JDK are tried.
#JAVA_HOME=/usr/lib/jvm/java-8-openjdk

# You may pass JVM startup parameters to Java here. If unset, the default
# options will be: -Djava.awt.headless=true -XX:+UseConcMarkSweepGC
#
# Use "-XX:+UseConcMarkSweepGC" to enable the CMS garbage collector (improved
# response time). If you use that option and you run Tomcat on a machine with
# exactly one CPU chip that contains one or two cores, you should also add
# the "-XX:+CMSIncrementalMode" option.
JAVA_OPTS="-Djava.awt.headless=true -XX:+UseConcMarkSweepGC"
###-------------------------------------------------------------------------------------------
JAVA_OPTS="${JAVA_OPTS} -Djava.awt.headless=true -Xms512m -Xmx2048m"
JAVA_OPTS="${JAVA_OPTS} -Dlinshare.config.path=file:/etc/linshare/"
JAVA_OPTS="${JAVA_OPTS} -Dlog4j.configuration=file:/etc/linshare/log4j.properties"

###--- JAVA_OPTS="${JAVA_OPTS} -Dspring.profiles.active=default,jcloud,batches"
###--- JAVA_OPTS="${JAVA_OPTS} -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true"
###-------------------------------------------------------------------------------------------
###--- If you want to change the location of tmp directory:
###--- JAVA_OPTS="${JAVA_OPTS} -Djava.io.tmpdir=/tmp/"


# To enable remote debugging uncomment the following line.
# You will then be able to use a java debugger on port 8000.
#JAVA_OPTS="${JAVA_OPTS} -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"

# Java compiler to use for translating JavaServer Pages (JSPs). You can use all
# compilers that are accepted by Ant's build.compiler property.
#JSP_COMPILER=javac

# Use the Java security manager? (yes/no, default: no)
#TOMCAT8_SECURITY=no

# Number of days to keep logfiles in /var/log/tomcat8. Default is 14 days.
#LOGFILE_DAYS=14
# Whether to compress logfiles older than today's
#LOGFILE_COMPRESS=1

# Location of the JVM temporary directory
# WARNING: This directory will be destroyed and recreated at every startup !
#JVM_TMP=/tmp/tomcat8-temp

# If you run Tomcat on port numbers that are all higher than 1023, then you
# do not need authbind.  It is used for binding Tomcat to lower port numbers.
# (yes/no, default: no)
#AUTHBIND=no

**Comment by fred49** [comment]
pelase use the "insert code" button juste before the "add link" button in the toolbar to enclose the result. It will handle the text you're about to paste as raw text.

**Comment by fred49** [comment]
`ls -l /etc/linshare` please

**Comment by alfred194** [comment]
``total 141732
-rw-rw-r-- 1 root root     10640 Jun 22 19:20 linshare.properties
-rw-r--r-- 1 root root     10344 Jun 22 17:04 linshare.properties.sample.org
-rw-r--r-- 1 root root       592 Jun 22 17:16 linshare-thumbnail-server.yml
-rw-r--r-- 1 root root 145092624 Jun 22 17:03 linshare.war
-rw-rw-r-- 1 root root      3467 Apr 20 10:02 log4j.properties
-rw-r--r-- 1 root root      3467 Jun 22 17:04 log4j.properties.org

**Comment by fred49** [comment]
In the log4j.properties file can you change : 
`log4j.rootCategory=INFO, CONSOLE`
by
`log4j.rootCategory=INFO, LINSHARE`

Then restart tomcat send me the /var/log/tomcat8/linshare.log file please

**Comment by alfred194** [comment]
linshare.log
[linshare.log](https://github.com/linagora/linshare/files/4840293/linshare.log)

**Comment by fred49** [comment]
`Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]`
	
Have you installed mongodb ?

**Comment by alfred194** [comment]
Yes

dpkg -l | grep mongo
ii  mongodb-org                            3.6.18                                          amd64        MongoDB open source document-oriented database system (metapackage)
ii  mongodb-org-mongos                     3.6.18                                          amd64        MongoDB sharded cluster query router
ii  mongodb-org-server                     3.6.18                                          amd64        MongoDB database server
ii  mongodb-org-shell                      3.6.18                                          amd64        MongoDB shell client
ii  mongodb-org-tools                      3.6.18                                          amd64        MongoDB tools

**Comment by fred49** [comment]
systemctl status mongodb

**Comment by alfred194** [comment]
it wassn't running
i've started it
then restarted tomcat8

now 
`● mongod.service - MongoDB Database Server
   Loaded: loaded (/lib/systemd/system/mongod.service; disabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-06-27 11:27:07 WAT; 3min 17s ago
     Docs: https://docs.mongodb.org/manual
 Main PID: 2483 (mongod)
   CGroup: /system.slice/mongod.service
           └─2483 /usr/bin/mongod --config /etc/mongod.conf

Jun 27 11:27:07 linshare systemd[1]: Started MongoDB Database Server.
`

linshare.log in attachme,nt
[linshare.log](https://github.com/linagora/linshare/files/4840309/linshare.log)

**Comment by alfred194** [comment]
i've just closed browsers
cleared the cache
then started again, now, i have the popup window for authentication

thanks a lot

one question
mongod must start automatically ?
because before my first message this morning i rebooted the server, so it appears that mongod didnt start automatically after reboot

**Comment by fred49** [comment]
systemctl enable mongodb

**Comment by fred49** [comment]
an it will start automaticlly

**Comment by alfred194** [comment]
systemctl enable mongodb
Failed to enable unit: Unit file mongodb.service does not exist.

 systemctl enable mongod
Created symlink /etc/systemd/system/multi-user.target.wants/mongod.service → /lib/systemd/system/mongod.service.

i am very grateful for your help, thank you too much

**Comment by fred49** [comment]
you're welcome. Enjoy.
