### ISSUE TITLE
feature: default and max guest date

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#119]
Hello,
It would be great if we can define a default expire date for guests (for example some days like today) but let the possibility to the creator to change this default one for a later date (with a max defined by the admin).
Best regards,

**Comment by fmartin-linagora** [comment]
Hi,
Yes, I would like to have it too. Currently the default value is the max value. Having to different values is a huge job that I would like to do but it is not planned neither our priority for now. Sorry. LinShare is a free software, any help or contribution is welcome ;)
Fred.

**Comment by fmartin-linagora** [comment]
Hi,

This feature was introduced in LinShare 4.1.
Upgrade LinShare and you will be able to enjoy it.

Regards,

**Comment by matdemb** [comment]
Hi,
I don't see any difference between my 2.3 and my 4.2.3 version for guests parameters...
I still have expiration and Postpone guest expiry date..
i doesn't look at the good place?
Regards,

**Comment by fmartin-linagora** [comment]
Hi,
If you look closer to the Guest expiration functionality you will see some extra parameters:
![image](https://user-images.githubusercontent.com/6229766/140538529-c0020283-1b86-466c-aa5a-1447799df507.png)
Regards,

**Comment by matdemb** [comment]
I have not the same UI...
![image](https://user-images.githubusercontent.com/33221710/140539443-450a61e1-9860-437b-ab08-f8ed311ee31e.png)
I tryed deleting web cache and using anonymous browsing, same resullt.

**Comment by fmartin-linagora** [comment]
Sorry, there was a bug and we fixed it but it is not released yet.

You can use the snapshot if you want:
* 4.1.x: https://nexus.linagora.com/service/local/repositories/linshare-snapshots/content/org/linagora/linshare/linshare-ui-admin/4.1.5-SNAPSHOT/linshare-ui-admin-4.1.5-20211103.032110-3.tar.bz2
* 4.2.x: https://nexus.linagora.com/service/local/repositories/linshare-snapshots/content/org/linagora/linshare/linshare-ui-admin/4.2.4-SNAPSHOT/linshare-ui-admin-4.2.4-20211103.031911-3.tar.bz2
