### ISSUE TITLE
linshare installation ubuntu 16 or centos 7 minimal

### ISSUE THREAD

**Issue by kathirvel2020** [linagora/linshare#12]
Hi Team,

Your doing greate work!,
I am trying to install linshare in my virtual machine,i folloewd document in installation centos 7 still I am not able to install exectly, please any one can give me step by step installtion or please record video and share.

**Comment by kathirvel2020** [comment]
I think I installed, but some issue is there, Tomcat configuration, 
![linshare_errror1](https://user-images.githubusercontent.com/33827020/33516018-6746c8d2-d791-11e7-8874-234bc162098d.png)
![tomcat issue configuration](https://user-images.githubusercontent.com/33827020/33516032-8e357574-d791-11e7-8b89-a072dd8882e0.png)
![tomcat](https://user-images.githubusercontent.com/33827020/33516033-8e7370ae-d791-11e7-8aad-8820d8e9b05c.png)
[history of linshare.txt](https://github.com/linagora/linshare/files/1523825/history.of.linshare.txt)

**Comment by kathirvel2020** [comment]
issue is mentioned below,
![catalina out no files](https://user-images.githubusercontent.com/33827020/33532551-a3a1df76-d8c0-11e7-9ae9-e41deb8c5db2.JPG)

**Comment by kathirvel2020** [comment]
status of httpd & tomcat
![httpd status](https://user-images.githubusercontent.com/33827020/33532686-c71704c6-d8c1-11e7-865b-fb5f7a6f2689.JPG)
![tomcat status](https://user-images.githubusercontent.com/33827020/33532687-c773b162-d8c1-11e7-8608-0e7feae5aa7c.JPG)

**Comment by fmartin-linagora** [comment]
I'm sorry I do not understand your problem. Logs are in the /var/log/tomcat/catalina.out.

**Comment by kathirvel2020** [comment]
Thanks for your reply, this is the error.
https://user-images.githubusercontent.com/33827020/33532551-a3a1df76-d8c0-11e7-9ae9-e41deb8c5db2.JPG

**Comment by fmartin-linagora** [comment]
Logs are not in /opt but /var like as said previously.

**Comment by kathirvel2020** [comment]
sorry, it's maybe my mistake, I followed installation document, can you please share me, step by step installation guide pls.

**Comment by fmartin-linagora** [comment]
Documentation updated. Tks.
https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-centos-7.md

**Comment by kathirvel2020** [comment]
I followed the same document but still, i am facing issue

**Comment by kathirvel2020** [comment]
if you have any idea how to setup in  linshare in AWS EC2 and host website, Help me with this, last 2 week I am searching solution for this installation,issue

**Comment by kathirvel2020** [comment]
if it's possible can you please record video and upload :)

**Comment by chezmohamed** [comment]
hello you found the solution? I have the same problem as you

**Comment by fmartin-linagora** [comment]
Hi,
This is an old issue without any logs. We can't help you further. So, I will closed this issue. If you still have some problems, please create a new explicit issue with the problem you are facing and the related logs. Tks.
