### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bzg** [linagora/linshare#120]
LinShare is a candidate for being referenced in the [Socle Interministériel de Logiciels Libres](https://sill.etalab.gouv.fr/fr/software).

I was able to find the AGPL-3.0 licence in https://github.com/linagora/linshare-core (although not very well advertized), but I cannot find a license in this repository.

LinShare cannot be added to the Socle Interministériel de Logiciels Libres until it is clearly released under an OSI-or-FSF approved license.

See https://github.com/DISIC/sill/issues/115

**Comment by fmartin-linagora** [comment]
Hi,
LinShare licence is available here https://www.linshare.org/files/LinShare-License_AfferoGPL-v3_en.pdf.
The link available in the COPYING file of linshare-core repository is broken, I will fix it asap.
Fred.

**Comment by bzg** [comment]
Thanks for your quick reply! To make things 100% correct, there should be a `LICENSE` or `COPYING` file with an OSI/FSF license in every LinShare repository.  Let me know when you're done and I'll proceed with adding LinShare to the SILL. Thanks!

**Comment by pvi-github** [comment]
Hi,

It seems to me that COPYING et COPYING.md appeared in the Linshare repositories.

I'm going to add an update in the issue [/DISIC/sill/115](https://github.com/DISIC/sill/issues/115) to do things correctly.

Thanks @fmartin-linagora for the fix

PVI

**Comment by bzg** [comment]
Thanks for the addition of `COPYING` and `COPYING.md`.

I noticed the link to http://www.linshare.org/licenses/LinShare-License_AfferoGPL-v3.pdf in the `COPYING.md` file is dead.  This should probably be fixed.

**Comment by pvi-github** [comment]
ping @fmartin-linagora : it's down the last part of the file in the very last blue-backgrounded block

**Comment by fmartin-linagora** [comment]
Hi,
Issue created, our website will be updated soon to fix the link.

**Comment by fmartin-linagora** [comment]
Done.
