### ISSUE TITLE
paramétrage pour la suppression physique des fichiers

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#123]
Je souhaite que les fichiers effacés dans LinShare soient supprimer physiquement du disque. Pour cela, j'ai modifié des lignes dans /etc/linshare/linshare.properties en décommentant la ligne :
job.shares.cron.expression=0 30 ? ? ? et en mettant job.document.cleaner.activation=true.
Après avoir redémarré tomcat8, si je tente de me connecter avec login/mot de passe, le message "Le serveur est temporairement indisponible apparaît.
Voyez-vous d'où vient le problème ?
En vous remerciant d'avance pour vos réponses.

**Comment by fmartin-linagora** [comment]
Bonjour,
Si le serveur est indisponible, vous devez regarer les logs du serveur pour comprendre pourquoi il n'a pas réussi à démarrer. La cause la plus problable étant votre dernière modification, en particulier job.shares.cron.expression.

**Comment by EPTBSGL** [comment]
Oui, la cause est bien cette modification. Mais alors quelle modification faut-il faire pour que les fichiers soient physiquement supprimé et que le serveur démarre ?

**Comment by fmartin-linagora** [comment]
l'expression suivante est la valeur par défaut, `job.shares.cron.expression=0 30 0 * * ?` elle permet au job de s'executer toutes les nuits.

**Comment by EPTBSGL** [comment]
En fait, j'avais remplacé les 2 "*" par des "?".  Si je laisse l'expression d'origine, ça fonctionne. Mais cela ne devrait-il pas fonctionner aussi avec "?" à la place de "*" ? (j'ai refait le test et si je mets _job.shares.cron.expression=0 30 0 ? ? ?_, le dysfonctionnement se reproduit.

**Comment by fmartin-linagora** [comment]
```

#******************** BATCH AND CRON
# Syntax :
# 	 Field				Mandatory	Allowed Values			Allowed Special Characters
# 1. Second				yes			0-59					, - * /	
# 2. Minutes			        yes			0-59					, - * /
# 3. Hours				yes			0-23					, - * /
# 4. Day of month		        yes			1-31					, - * ? / L W
# 5. Month				yes			1-2 or JAN-DEC			, - * /
# 6. Day of week		        yes			1-7 or SUN-SAT			, - * ? / L #
# 7. Year 				no			empty, 1970-2099		, - * /
#
# Legend : ? : no specific value
#		 : L : last
#		 : W : weekday
#
```
la documentation incluse dans le fichier linshare.properties au dessus du cron semble indiqué que la valeur "?" n'est pas autorisée partout.

**Comment by EPTBSGL** [comment]
Merci beaucoup pour votre réponse. Je n'avais pas fait attention à ce point de détail. Je clos donc le ticket.
