### ISSUE TITLE
Connect to linshare via desktop

### ISSUE THREAD

**Issue by LawlessWorld** [linagora/linshare#125]
is there a way to connect to linshare via a desktop?

For example, I use cyberduck and can access nextcloud instances as well as sftp into other sites.  Is there a way to do this with linshare?

- [X ] last question, when do you think 4.0 may be released? asking for a friend

**Comment by fmartin-linagora** [comment]
Hi,
Sorry we do not have FTP access on LinShare, having a desktop client is not planned on short or middle term.
LinShare 4.0 was released Friday 17 July 2020, enjoy ;)

**Comment by Trollwut** [comment]
Has anything changes about this information?

A desktop integration (especially into file system) would be baller. We'd even consider it for our business.

If it would be integrated like GoogleDrive / Nextcloud / similar like a simple folder (and icons to represent the sync status), it would be the ideal solution we look for.

**Comment by Donald42** [comment]
> A desktop integration (especially into file system) would be baller. We'd even consider it for our business.

According to this post from March 2022, desktop sync is allegedly being worked on:
https://old.reddit.com/r/opensource/comments/tjcxnn/linshare_live_webinar_european_opensource/i1n2z0w/?context=3

I am also waiting for this feature.
