### ISSUE TITLE
upgrade to 4.0

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#126]
Hello, 
I've migrated from 2.3.4 to 4.0.0 version but there is some missing or errors in the [upgrade documentation](https://github.com/linagora/linshare/blob/master/documentation/EN/upgrade/linshare-upgrade-from-v2.3-to-v4.0.md).

For the mongoDB restore is it "mongorestore --drop /path/to/dump/" to use (it seems to be ok with that)?
There is nothing about it in the doc.

And for the postggresql the instruction given are not enough.
After the drop table, we need to do a create table and then import the dB with linshare user (I used 'psql -U linshare -d linshare -f /tmp/dump-linshare.sql'). It doesn't work with postgres user (it doesn't create the linshare database, it probably populate the postgres table).

The "Sharedspace quota" in the admin UI always show wrong used/free space. How can I do to have the correct value? 

Thanks.

**Comment by tolstoyfafa** [comment]
Hello,
Thanks for the feedback,  we will take care to update our documentation soon as possible
Regards

**Comment by marwanJebahi** [comment]
Hello,
The documentation of the upgrade guide from 2.3 to 4.0 is updated. You can [see](https://github.com/linagora/linshare/blob/master/documentation/EN/upgrade/linshare-upgrade-from-v2.3-to-v4.0.md#linshare-upgrade).
The bug of sharedSpace quota wil be treated with this [issue](https://github.com/linagora/linshare/issues/96)
I will close this issue, if it does not answer to your question feel free to re-open it.
Regards
