### ISSUE TITLE
domains overlapping

### ISSUE THREAD

**Issue by alfred194** [linagora/linshare#128]
Hello

we had a configuration issue in 2.0.6 version, now, i've just fresh installed the 4.0.0 version
i would like to have an answer about this issue before beginning the configuration

the issue
in the version 2.0.6 we've configured 3 domains (Admins), (AD) and (Guests)
Domains -- Manage Domains -- Admins
then 2 sub domains
Domains -- Manage Domains -- AD
Domains -- Manage Domains -- Guests
 
the goal was granting Guest creation to users (Admins) only

the problem is that the Domain (Admins) points to an (OU) in our Active Directory, and the Domain (AD) points to all users in the Active Directory

so a user belonging to the domain (Admins) belongs also to the domain (AD)

when adding the user from the domain (Admins) the first time it is ok
when we try to log another time with the same user, we got an error, it is like Linshare try to authenticate the user with the second domain (AD) so a problem, the only solution is to delete the user, then add it again, but it is always a single use because the problem will appear again

so obviously, a user must belong to one domain only ?

so my question 
is it possible to work with one active directory but in the same time assign some users to the (Admins) domain while all the rest of users will belong to the (AD) domain ?
i am asking because unfortunately LinShare doesn't have local users

Best Regards

**Comment by fred49** [comment]
Hi,
Yes, an user must appear in one domain only. you can't overlap domains.

I suppose you don't have a branch with all your admins only, and some other branches with all your regular users, do you ?

So, you can use an attribute that let you identify which user is a admin and which is a regular user. Then you can create two "Domain Pattern" to pick only admins or users.

**Comment by fmartin-linagora** [comment]
I suppose my answer fixed your issue. So I'm closing this issue.
