### ISSUE TITLE
Is there a Slack or IRC or Gitter channel ?

### ISSUE THREAD

**Issue by qorrect** [linagora/linshare#129]
Really loving linshare, do you have a chat channel ?  Sorry I know this is the wrong place.

**Comment by fred49** [comment]
Hello, nope, you're right ! It's the good place to ask questions. We don't have any chat, we are using issues in this GitHub repository to communicate with the community.

**Comment by qorrect** [comment]
OK great.  I'd like to add an SFTP interface to LinShare so I can convince my employer to use it for our MFT solution.  It looks like I'd be calling the API /linshare/webservice/rest/user/v4/ which has all I need ( to authenticate, to list files ).  I will start a new project linshare-sftp-preview and ask questions as I go along.
