### ISSUE TITLE
 linshare_v2.0.1_2

### ISSUE THREAD

**Issue by kathirvel2020** [linagora/linshare#13]
Hi Team,
i tried so many times still issue is not able to solve to install linshare in my centos7 minimal version,
so I download virtual machine  linshare_v2.0.1_2.box and add to my virtual box. Now I try to login but what is the login name and password to log in
![vagrant instance](https://user-images.githubusercontent.com/33827020/33539701-cd1aeffa-d8ed-11e7-8a2c-6cc281acd93f.JPG)
 my virtual machine

**Comment by fmartin-linagora** [comment]
Hi,
Have you try vagrant/vagrant ? Be carefull keyboard layout may be QWERTY.

**Comment by kathirvel2020** [comment]
Thanks, it working please update the document.
