### ISSUE TITLE
4.0: upload issue

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#130]
Hello,
I tryed a new 4.0 on debian 10 installation but I have an issue: the tomcat can't write in the specified path, but I don't know why.
The log indicate:
[INFO]:main:20200804.111532:org.linagora.linshare.core.dao.impl.AbstractJcloudFileDataStoreImpl:createContainerIfNotExist:creation of a new bucket e0531829-8a75-49f8-bb30-4539574d66c7 without locale.
[DEBUG]:main:20200804.111532:org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl:logDebug:Creating container e0531829-8a75-49f8-bb30-4539574d66c7
[DEBUG]:main:20200804.111532:org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl:logDebug:Creating directory /data/linshare/filesystemstorage/e0531829-8a75-49f8-bb30-4539574d66c7
[DEBUG]:main:20200804.111532:org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl:logDebug:Could not create directory: /data/linshare/filesystemstorage/e0531829-8a75-49f8-bb30-4539574d66c7: Système de fichiers accessible en lecture seulement

My filesystem is writable (I create the path ./linshare/filesystemstorage manually) and the directory has the good autorization.
 
ls -al /data/linshare/
total 12
drwxr-xr-x 3 tomcat tomcat 4096 août   4 10:13 .
drwxr-xr-x 4 root   root   4096 août   4 10:13 ..
drwxr-xr-x 2 tomcat tomcat 4096 août   4 10:13 filesystemstorage

mount -l
[...]
/dev/sda1 on /boot type ext4 (rw,relatime)
/dev/mapper/vg01-data on /data type ext4 (rw,relatime)
/dev/mapper/vg01-temp--lin on /usr/share/tomcat/temp-lin type ext4 (rw,relatime)
[...]

I tryied with directory /var/lib/linshare like in the documentation, I have the same issue.

I have quite the same configuration on 2.3 (I had the new options for 4.0 configuration file ) and it works well on it.

Any idea what is the problem?
Thanks.

**Comment by matdemb** [comment]
I found what's wrong:
Tomcat9 has a security on debian not allowing to write anywhere.
https://stackoverflow.com/questions/56827735/how-to-allow-tomcat-war-app-to-write-in-folder

This is not in the installation doc.

Regards.

**Comment by fred49** [comment]
Thanks for the feedback, it is interesting. We will update the documentation.

**Comment by marwanJebahi** [comment]
Hello matdemb,
Thank you for your feedBack, the install documentation is updated, you can [see](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-debian.md#linconf).
Regards.

**Comment by marwanJebahi** [comment]
Hello

Issue fixed and the documentation is updated, I am closing this issue, feel free to open a new one if needed.

Regards
