### ISSUE TITLE
calendar language

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#132]
Hello,
is it possible to configure the language of the calendar?
I didn't find any way to do this...
Even on fr-Fr interface it's in english.
And eventually to change the first day of the week?
Thanks.

**Comment by fmartin-linagora** [comment]
Hi,
I think this is a bug, I will inform the frontend team about it.
For the first day of the week, it may be related to the language issue.
Thanks for the feedback.

**Comment by matdemb** [comment]
Hi,
the bug seems to be corrected on version 4.2.2 (maybe before).
So it's ok.
Thanks.
