### ISSUE TITLE
LDAP SSO http-bio WARN

### ISSUE THREAD

**Issue by PhidarkMM** [linagora/linshare#133]
Hello,

We have a problem creating users through our kerberos / AD SSO configuration (version 2.3.5)

Our configuration of each domain corresponds to an LDAP path to our Active Directory, and works fine for existing users, but no longer for new users present in the corresponding OUs.

For example, new user testlinshare in an OU AD for an existing Linshare domain:
Aug 13 09:44:08 srv-linshare server: [WARN]:http-bio-8080-exec-7:20200813.094408:org.hibernate.engine.internal.StatefulPersistenceContext:narrowProxy:HHH000179: Narrowing proxy to class org.linagora.linshare.core.domain.entities.LdapUserProvider - this operation breaks ==
Aug 13 09:44:08 srv-linshare server: [WARN]:http-bio-8080-exec-7:20200813.094408:org.linagora.linshare.core.facade.auth.impl.AuthentificationFacadeImpl:checkStillInLdap:authentication process : the current user does not exist anymore into the LDAP directory : Testlinshare Testlinshare(a0440711-a97f-45d6-88e3-d11dcdc32066, testlinshare)
Aug 13 09:44:08 srv-linshare server: [INFO]:http-bio-8080-exec-7:20200813.094408:org.linagora.linshare.core.service.LogEntryService:insert:AuditLogEntry [AuthUser=AccountMto [firstName=null, lastName=null, name=system, mail=system, uuid=system, role=SUPERADMIN, accountType=SYSTEM, domain=Domain [uuid=LinShareRootDomain, label=LinShareRootDomain]], resourceUuid=a0440711-a97f-45d6-88e3-d11dcdc32066, action=UPDATE, type=USER, creationDate=Thu Aug 13 09:44:08 CEST 2020]
Aug 13 09:44:08 srv-linshare server: [INFO]:http-bio-8080-exec-7:20200813.094408:org.linagora.linshare.core.service.LogEntryService:insert:AuditLogEntry [AuthUser=null, resourceUuid=null, action=FAILURE, type=AUTHENTICATION, creationDate=null]
Aug 13 09:44:08 srv-linshare server: [ERROR]:http-bio-8080-exec-7:20200813.094408:org.linagora.linshare.auth.dao.UserDetailsProvider:logAuthError:Couldn't log an authentication failure : User not found ! Login : testlinshare@xxx.fr

This problem exists on our test platform, our production platform, on versions 2.3.3 and 2.3.5, but did not exist on our previous version 2.2.2.

Thanking you in advance,
Best regards,

**Comment by fmartin-linagora** [comment]
Hi,
Can you send me the log file as attachment, it is very hard to have the context and read this traces as a github post ;)

**Comment by PhidarkMM** [comment]
Hello,

Here are the logs, from our test and prod platforms, with existant users and a new user of the same AD OU.

[test.zip](https://github.com/linagora/linshare/files/5116273/test.zip)
[prod.zip](https://github.com/linagora/linshare/files/5116278/prod.zip)

Best regards
