### ISSUE TITLE
Linshare version 4 features

### ISSUE THREAD

**Issue by annmaria1** [linagora/linshare#134]
Hi Linshare Team,

What are the features available in Linshare version 4. 
Here i'm using "Admin version : 2.6.1 and Core version : 1.12.8. Where did i get outlook plugin for linshare

Thanks
Jinju

**Comment by marwanJebahi** [comment]
Hello,
You can see all changes of the different LinShare's versions in the [here](https://github.com/linagora/linshare/blob/master/CHANGELOG.md).
About the plugin Outlook LinShare, it is not maintained anymore.
Regards.

**Comment by annmaria1** [comment]
Thanks Linshare for your reply.
I have two more questions. Could you please answer it.
1) Is Upload request option available in any of the latest version other than core version 1.x ?
2) Possible to enable file encryption by default ? 
3) Can i get existing Outlook plugin as we are using core version 1.x

Thanks
Jinju

**Comment by marwanJebahi** [comment]
Hello,

* For upload request, it is not available in any other version else than the 1.x, but our team is starting to work on this feature , we will let you know when it will be ready. I hope it will be available by the end of this year.
* The data encryption can be enabled just by the user itself.
* The Outlook plugin is only available just with our entreprise offer(support).

Regards

**Comment by annmaria1** [comment]
Hi,
Thanks for your email.
Please let me know the cost only for outlook plugin, if possible.

Thanks
Jinju

**Comment by fmartin-linagora** [comment]
Hi,
If you want more information about our enterprise offer, please send us your contact information (phone or email). Otherwise you can reach our commercial team through vente@linagora.com.
Regards,

I'm closing this issue, feel free to open a new one if needed.
