### ISSUE TITLE
Customize the mail content

### ISSUE THREAD

**Issue by annmaria1** [linagora/linshare#135]
Hi Linshare Team,

How can i update the content of body from below table? The highlighted content is not required for us.

**After download is complete, make sure to decrypt them locally by using the application:<br/><a href="${jwsEncryptUrl}">${jwsEncryptUrl}</a><br/>You must use the <i>password</i> granted to you by the user who made the file(s) available for sharing.</p><br/><br/>**

INSERT INTO mail_content (id, uuid, domain_abstract_id, language, mail_content_type, visible, plaintext, modification_date, creation_date, greetings, name, subject, body, alternative_subject, enable_as) VALUES  (11, 'fef9a3f1-6011-46cd-8d39-6bd1bc02f899', 1, 0, 10, true, false, now(), now(), E'Hello ${firstName} ${lastName},<br/><br/>', E'New sharing of a cyphered file', E'A user ${actorRepresentation} has just made a file available to you!', E'<strong>${firstName} ${lastName}</strong> has just shared with you ${number} file(s):<ul>${documentNames}</ul><br/>To download the file(s), simply click on the following link or copy/paste it into your favorite browser: <a href="${url}${urlparam}">${url}${urlparam}</a><br/><p>One or more received files are <b>encrypted</b>. After download is complete, make sure to decrypt them locally by using the application:<br/><a href="${jwsEncryptUrl}">${jwsEncryptUrl}</a><br/>You must use the <i>password</i> granted to you by the user who made the file(s) available for sharing.</p><br/><br/>', '${actorSubject} from ${actorRepresentation}', true);

Thanks
Jinju.

**Comment by fmartin-linagora** [comment]
I don't know. I supposed that if you remove the useless part from the template, it will work. I suppose you can do it through the admin interface.

**Comment by annmaria1** [comment]
Hi Federic,

I have updated it in the DB table and it's working now.

Thanks
Jinju.

**Comment by fmartin-linagora** [comment]
Hi,
I don't know which version you are using, it seems to be a version 1, very old version. I don't know if you are aware but we released the version 4. You should think about upgrading.
Fred.

**Comment by annmaria1** [comment]
Hi Fred,

We will upgrade once you integrate with the upload request.

Thanks
Jinju.
