### ISSUE TITLE
4.0 feature Lockout account

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#137]
Hello,
the new feature Lockout account is interesting but how many time an account is locked, is it editable and is there a way to manually unlock it?
Thanks

**Comment by tolstoyfafa** [comment]
Hello,
Here are the rules:
- After 3 attempts : account locked for 10 minutes
- After 6 attempts : account locked for 20 minutes
- After 9 attempts : account locked for 60 minutes (1 hour)
- After 12 attempts : account locked for 1440 minutes (1 day)
- After 15 attempts : account locked indefinitely

The manual unlock is planned for the next release 4.0.1
Regards

**Comment by matdemb** [comment]
Thank you for this informations.
Regards,
