### ISSUE TITLE
Software download website unavailable

### ISSUE THREAD

**Issue by camgithub** [linagora/linshare#139]
The installation  guide refers to downloading the latest code from download.linshare.org.  This site is returning a HTTP 404 error.  Is there an alternative site to download linshare?

**Comment by marwanJebahi** [comment]
Hello,
Thank you for you feedback, we will fix the problem ASAP.
You can download LinShare's components from: https://nexus.linagora.com/content/repositories/linshare-releases/org/linagora/linshare/
regards

**Comment by marwanJebahi** [comment]
Hello,
The download [link](http://download.linshare.org/versions/) is accessible again.
Regards
