### ISSUE TITLE
Can't connect ldaps

### ISSUE THREAD

**Issue by Alexconte31** [linagora/linshare#143]
Hello,

I linked linshare to an ldap, but i got those errors:

[ERROR]:http-bio-8080-exec-1:20201029.163959:org.linagora.linshare.core.service.impl.UserProviderServiceImpl:throwError:Error while searching for a user with ldap connection b21cbb7b-4ce8-4bc0-847e-141fb1a91e09
[ERROR]:http-bio-8080-exec-1:20201029.163959:org.linagora.linshare.core.service.impl.UserProviderServiceImpl:throwError:simple bind failed:  "nom de domaine ".fr:636; nested exception is javax.naming.CommunicationException: simple bind failed: "nom de domaine ".fr:636 [Root exception is javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching "nom de domaine.fr found]
[ERROR]:http-bio-8080-exec-1:20201029.163959:org.linagora.linshare.core.service.impl.AbstractDomainServiceImpl:searchUserWithDomainPolicies:can not search users from domain:6376d235-6bb8-4635-8e8b-d2fc55882528

Do someone have an idea ?

Regards.

**Comment by matdemb** [comment]
Hi,
are you sure of your domain name?
It says "No name matching".
Try to test if your server can resolve this domain name.
Maybe a DNS issue.

Regards,

**Comment by fmartin-linagora** [comment]
Hi,
Did you add the CA that emitted the SSL certificate to the java keystore ? Otherwise the tomcat won't be able the verify the ssl certificate used by the SSL connection. And you must use the same fqdn as in the certicate to join the ldap server.
