### ISSUE TITLE
Mise à jour d'une version 3.5 vers 4.0

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#144]
Existe-t-il une procédure de mise à jour de la version 2.3.5 (ou 2.3.x) vers 4.x ?
Y a-t-il un script sql permettant de migrer la base de donnée de l'une à l'autre version et si oui lequel ?
En vous remerciant pour vos réponse,
Philippe NICOLAS

**Comment by marwanJebahi** [comment]
Hello, 

The last version of LinShare before the release of LinShare 4.0 is 2.3.5.
you can follow this  [guide](https://github.com/linagora/linshare/blob/master/documentation/EN/upgrade/linshare-upgrade-from-v2.3-to-v4.0.md#linshare-upgrade) to upgrade your LinShare.

Regards

**Comment by EPTBSGL** [comment]
Bonjour et merci pour votre réponse.
J'ai testé la procédure et elle fonctionne parfaitement.
Juste une petite correction à apporter dans la documentation : pour désactiver "linshare-user", il faut passer la commande "a2dissite linshare-user" et non pas "a2ensite linshare-user".
Philippe NICOLAS
