### ISSUE TITLE
Error on download folder

### ISSUE THREAD

**Issue by Maxgesd** [linagora/linshare#148]
Hello,

I have migrate my server from 2.3 (debian 8) to 4.0.2 (debian 10). All run nicely except the functionnality to download a folder.

Catalina.out show these errors : 
 [info] [ERROR]:http-nio-8080-exec-3:20201202.145518:org.apache.cxf.jaxrs.utils.JAXRSUtils:logMessageHandlerProblem:Problem with writing the data, class org.linagora.linshare.webservice.utils.DocumentStreamReponseBuilder$1, ContentType: application/zip
 [info] [ERROR]:http-nio-8080-exec-3:20201202.145518:org.linagora.linshare.webservice.interceptor.GenericExceptionMapper:toResponse:A NullPointerException was caught : /linshare/tmp/linshare-download-folder-18245718771435737441.zip (No such file or directory).

I have tested to change path of TOMCAT's tmp directory and add path to override.conf but same errors.

Any ideas?

Thanks

**Comment by marwanJebahi** [comment]
Hello,
Thank you for your report.
This bug is fixed and it will be available in the next release.
Regards.

**Comment by fmartin-linagora** [comment]
Hi,
We released  LinShare 4.0.3, it should fix your issue.
Regards
