### ISSUE TITLE
Admin interface: it is not possible to delete record but it possible to add it

### ISSUE THREAD

**Issue by kevin-m87** [linagora/linshare#149]
Hi,

Still there with 4.0.2

https://github.com/linagora/linshare/issues/127

**Comment by marwanJebahi** [comment]
Hello,

Thank you for your feedBack.
We are aware about this issue, and the team is working to fix it. We will keep you informed when it will be fixed.

Regards

**Comment by fmartin-linagora** [comment]
Hi,
We released LinShare 4.0.3, it should fix your issue.
Regards
