### ISSUE TITLE
Fichiers sur NAS

### ISSUE THREAD

**Issue by kreos77** [linagora/linshare#15]
Bonjour, je souhaite sauvegarde mes fichiers dans un NAS QNAP, j'ai repéré dans le fichier linshare.properties la ligne (linshare.documents.storage.filesystem.directory=/var/lib/linshare/filesystemstorage), je l'ai modifier en mettant /mnt/linshare (mount de mon fichier de partage de mon NAS) mais j'obtiens un message erreur lorsque je souhaite télécharger mon fichier depuis l'interface web (erreur: serveur injoignable).

Merci d'avance

**Comment by fmartin-linagora** [comment]
Bonjour,
Lorsque vous avez une erreur coté navigateur, vous devriez consulter les logs serveurs (/var/log/tomcat8/catalina.out) pour plus de détails.
Cordialement,

**Comment by fmartin-linagora** [comment]
Bonjour,
En l'absence de réponse, je procède à la cloture de ce ticket.
Cdt.
