### ISSUE TITLE
Nouvelle fonctionalité

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#150]
Quelqu'un peut-il me dire à quoi correspond cette fonctionnalité (concernant les domaines) : FUNCTIONALITIES.DETAILS.DRIVE__CREATION_RIGHT.NAME ?
C'est nouveau dans la version 4 mais je n'ai pas trouvé de documentation.
En vous remerciant d'avance.

**Comment by fmartin-linagora** [comment]
Bonjour,
Désolé il s'agit d'un bug de notre part, cette fonctionnalité est en cours de développement et il semblerait que le label n'est pas été traduit/masqué.
Cdt,

**Comment by EPTBSGL** [comment]
Merci pour votre réponse rapide. Du coup, je clos le ticket en attendant la correction.
