### ISSUE TITLE
Modèle de groupe de travail

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#152]
Bonjour,
Je cherche à récupérer les groupes de travail depuis notre Active Directory. J'ai donc créé un modèle de groupe de travail basé sur le seul modèle disponible : ldpap groups.
J'ai remplacé la requête de recherche de tous les groupes de travail "ldap.search(baseDn, "(&(objectClass=groupOfNames)(cn=workgroup-*))");" par "ldap.search(baseDn, "(&(objectClass=group)(cn=service))");" car dans l'AD l'objectClass à la valeur group et non pas groupOfNames. J'ai fait de même pour la requête de recherche d'un groupe de travail. Je précise également que ces groupes ne possèdent pas d'adresse de courriel. D'autre part les noms de groupe commencent par "service".
Dans le domaine, j'ai renseigné la partie "fournisseur de groupe de travail en indiquant la connexion LDAP, le modèle de groupe de travail et la base DN.
Je n'arrive pas à lister les groupes de mon AD dans linshare. Je précise que depuis le serveur linshare, je fais des requête LDAP en ligne de commande avec ldapsearch en sélectionnant les groupes et cela fonctionne.
Avez-vous une idée ?
En vous remerciant d'avance pour vos réponse

**Comment by fmartin-linagora** [comment]
Bonjour,
J'ai l'impression qu il y a une erreur dans votre filtre : "(cn=service)" => "(cn=service*)"
Vous devez ajouter une "*" pour indiquer que le filtre n'est pas un matching exact.

Pour obtenir plus d'info, vous pouvez aussi mettre LinShare core en debug et regarder les logs ;)
Fred.

**Comment by EPTBSGL** [comment]
J'ai essayé avec "(cn=service*)", j'ai même supprimé ce critère en tapant "ldap.search(baseDn, "(objectClass=group)");" et ça ne fonctionne pas plus.

**Comment by fmartin-linagora** [comment]
Bonjour,
Avez-vous regardé les logs ?
Cdt,

**Comment by EPTBSGL** [comment]
Je ne peux activer les logs qu'à partir du core. Mais je n'ai rien qui apparaît dans les groupes de travail puisque en admin, je ne les vois pas. A tout hasard, je vous joins le catalina.out.
En vous remerciant,
Cordialement
[catalina.txt](https://github.com/linagora/linshare/files/5704998/catalina.txt)

**Comment by fmartin-linagora** [comment]
Bonjour,

Dans le doute, je préfère décrire les étapes nécessaires au bon fonctionnement de cette synchro.
1. créer le Workgroup Pattern
    Le filtre est le meme que pour la commande ldapsearch, il est donc aisé de le tester pour vérifier que celui-ci retourne bien une liste de dn correspondant à des objets de type groupOfNames.
2. Dans votre domaine LinShare, vous avez déja du créer un UserProvider, vous devez désormais créer un GroupProvider référençant le Workgroup parttern précédent.
3. La synchronisation s'effectue toutes les 4 heures par défaut.Il faut donc modifier la fréquence pour voir facilement le résultat de votre paramétrage.

La documentation officielle est présente ici: https://github.com/linagora/linshare/blob/master/documentation/EN/administration/ldap.md

Fred

**Comment by fmartin-linagora** [comment]
Un redémarrage du tomcat est toujours nécessaire lors de la modification du fichier linshare.properties.

**Comment by EPTBSGL** [comment]
Merci pour vos réponses mais je n'arrive toujours pas à faire fonctionner la synchro des groupes. J'ai décommenter la ligne concernant le cron de synchro des groupes LDAP dans linshare.properties , ai réglé toutes les 5 secondes puis ai redémarré tomcat9. Si j'utilise la commande ldapsearch, j'écris : "ldapsearch -h x.x.x.x -D "cn=s-ldap,ou=utilisateurs de service,ou=sgl,dc=gls,dc=intra" -W -b "ou=groupes,ou=sgl,dc=gls,dc=intra" "(&(objectclass=group)(cn=SERVICE*))" et ça me retourne bien ce que je veux après avoir saisi le mot de passe. Dans la requête du modèle de groupe de travail, il faut remplacer baseDN par ou=groupes,ou=sgl,dc=gls,dc=intra avec ou sans guillemet ? (j'ai essayé les deux, ça ne fonctionne toujours pas). Si je laisse baseDN, ça ne fonctionne pas non plus. Est-ce que le fait que mes groupes ne soient pas associés chacun à une adresse de courriel empêche la synchro ?

**Comment by fmartin-linagora** [comment]
Bonjour,
Maintenant que vous avez le process qui tourne toutes les 5 minutes, vous devriez avoir des logs. Vous pouvez  meme activer les mode debug pour avoir encore plus de détail dans le catalina.out.
Je veux bien le fichier, ce sera plus simple pour comprendre ce qui se passe.
Fred

**Comment by EPTBSGL** [comment]
Ci-joint les 100 dernières lignes :
[catalina.txt](https://github.com/linagora/linshare/files/5716383/catalina.txt)
En vous remerciant

**Comment by fmartin-linagora** [comment]
Le serveur est encore en mode info et le fichier ne contient aucune trace d'éxécution du job, seulement des traces d'acces web. Vous devriez avoir des traces liées à la classe : LDAPGroupSyncServiceImpl

**Comment by EPTBSGL** [comment]
Pouvez-vous me donner un exemple concret de ce qu'il faut mettre dans la requête svp?

**Comment by EPTBSGL** [comment]
Pouvez-vous me donner un exemple concret de ce qu'il faut mettre dans la requête svp  ?

**Comment by EPTBSGL** [comment]
Bonjour,
Mon problème vient du cron. J'avais mis "0/5 0 0 * * ?" ce qui ne lance pas la tâche. J'ai mis "0 * * * * ?" pour que ce soit exécuté toute les minutes. Je rapatrie bien les groupes. Merci pour votre aide et vos réponses et bonnes fêtes de fin d'année.
Je clos le ticket qui est résolu.
