### ISSUE TITLE
feature to login with ldap uid instead of mail

### ISSUE THREAD

**Issue by BorisFC** [linagora/linshare#153]
Hi,

is it possible to let the choice to administrators to configure with which ldap attribute (mail or uid) users will login in linshare ? 

Regards,

Boris

**Comment by fmartin-linagora** [comment]
Hi,
By default, linshare-ui-user enforce usage of email as login. You should disable this check by adding the following key to your 
config.js file : loginWithMailOnly: false,
Then, you can have a look to your "domain patterns", to the query named : "Authentication command". By default, ldap attributes uid and mail  are supported for authentication.
Fred

**Comment by BorisFC** [comment]
Hi Fred,

Thank you for the workaround, ldap authentication works fine with ldap login. Is it possible to change the default text in login area on the login page ? 

i'd like to display "login" instead of "mail address" .

regards,

Boris

**Comment by fmartin-linagora** [comment]
Hi,
Quite the same solution, you need to override the default folder for i18n using your own i18n files. 
```
localPath: 'i18n/original', // custom your i18n folder path
```
I do not remember if LinShare will fallback to the default files if you do not provide every i18n files in your custom folder.
Fred
