### ISSUE TITLE
Internal recipient must have access rights for downloading shared files

### ISSUE THREAD

**Issue by annmaria1** [linagora/linshare#154]
Hi,
When a user shared a file to Internal and external party, the external recipient can download the file using with password generated by Linshare. But the internal recipient must have login access for download the file. Is it the normal behavior? can this be removed and get the same email like external recipient?
Thanks,
JInju

**Comment by fmartin-linagora** [comment]
Hi,
Yes it is possible to use the same sharing process for internal/guest users as the external users, ie a single page per share.
NB: Users with accounts (internal or guest) won't be able to find them again, the sharing won't appears in "Received Shares" menu.

See http://server/#/functionality/LinShareRootDomain/detail/ANONYMOUS_URL?view=simple, and then look at the nested functionality named "Anonymous URL - force anonymous sharing process"

Fred

**Comment by annmaria1** [comment]
![linshare](https://user-images.githubusercontent.com/41739394/106233704-1cb30500-621d-11eb-9cd0-c29bb4dbf5f3.jpg)
![linshare2](https://user-images.githubusercontent.com/41739394/106233715-20468c00-621d-11eb-8988-c64a50be698f.jpg)

Hi Fred,

I didn't find the "Anonymous URL - force anonymous sharing process"
I have attached here the current setting of Anonymous URL and the email getting to the internal user.

**Comment by annmaria1** [comment]
Hi Fred,
I'm using the below version of Linsahre. "Anonymous URL - force anonymous sharing process" feature is not found in the Admin portal.
Product version : 2.6.1
Core version : 1.12.8

**Comment by fmartin-linagora** [comment]
Hi,
Your version is very outdated, you should plan an upgrade. You are late by to major version, 2.x and 4.x.

This feature was introduced in more recent version than yours, at least it is available in LinShare 2.3.

**Comment by annmaria1** [comment]
Hi Fred,

Is UPLOAD REQUEST available in Latest version? We have required an upload
request. That's why we are using linshare version 1x

**Comment by fmartin-linagora** [comment]
Ok, I understand.
We are currently working on it, I hope we will be able to release it this month in the LinShare 4.1 version. :smile: 
NB: upgrading for 1.x to 4.x will require to upgrade to intermediate version and it will require a lot of work.

**Comment by annmaria1** [comment]
Thank you very much Fred. I will touch you the first week of next month.

**Comment by annmaria1** [comment]
Hi Fred,

I have noticed that the new version is available now. I will build a new
server and setup everything for it. In this case how can I transfer users
files to new system. Kindly help.

Thanks,
Jinju

**Comment by fmartin-linagora** [comment]
Hi Jinju,
You need to follow upgrade guides to upgrade from 1.12 to 2.0, then 2.1, 2.2, 2.3, 4.0 and finally 4.1.
See here https://github.com/linagora/linshare/blob/master/documentation/EN/upgrade/README.md
Fred
