### ISSUE TITLE
Email anonymous share

### ISSUE THREAD

**Issue by kevin-m87** [linagora/linshare#156]
Hello,

I'm using version 4.0.3.

We send an anonymous partage to an client user and he can't download it.

Source mail :

`<br><a href="https://<url>/#%21/external/anonymous/f4defb14-c9c2-46fc-97c9-894e20c67f64" target="_blank"><span style='color:#1294DC;text-decoration:none'>https://<url>/#!/external/anonymous/f4defb14-c9c2-46fc-97c9-894e20c67f64</span></a>`

The issue is for i don't know why href url contain '%21' instead of '!'

We done multiple more anonymous partage and i can't reproduce.

Do you have an a idea that why the href email was rewriting with this '%21' for this anonymous user ? Issue with ascii encoding ?

**Comment by fmartin-linagora** [comment]
Hi,

Nope, no idea. Maybe your MTA or MUA are applying some modifications to every sent/received emails.
