### ISSUE TITLE
L'invitation de dépôt (upload request) ne fonctionne pas

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#157]
Bonsoir,
Je viens d'installer la version 4.1 sur Debian 10 et je ne parviens pas à faire fonctionner l'invitation de dépôt. Je l'ai mise dans un vhost et j'ai résolu le nom du serveur (directive ServerName) dans /etc/hosts. D'ailleurs, si je tape directement l'adresse url http://linsharetest-upload-request.local dans le navigateur, j'ai bien accès à la page du site.
J'ai bien mis cette adresse via la plateforme d'administration dans la fonctionnalité "invitation de dépôt".  Lorsqu'après avoir rempli les différents champs du formulaire je clique sur "Créer" une notification apparaît dans le navigateur "Mauvaise requête".
Avez-vous une idée pour ce problème ?
En vous remerciant d'avance pour vos réponse,
Philippe NICOLAS

**Comment by alamartiniere-Linagora** [comment]
Bonjour,
Pouvez-vous partager le contenu de vos logs tomcat s'il vous plaît?
Bien à vous,
Alvin

**Comment by EPTBSGL** [comment]
Bonjour,
Merci pour votre réponse rapide. Voici les dernières lignes du fichier après avoir tenté d'envoyer une invitation de dépôt.
[catlina.txt](https://github.com/linagora/linshare/files/6129875/catlina.txt)

**Comment by EPTBSGL** [comment]
Re-bonjour,
tout est tombé en marche ! En fait, ce problème n'était lié qu'au cache du navigateur. L'invitation de dépôt se crée bien et son initiateur a bien accès aux fichiers déposés. Je clos donc ce ticket en vous remerciant pour votre réactivité.
