### ISSUE TITLE
Langue par défaut de la plateforme d'invitation de dépôt

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#158]
Bonjour,

J'ai testé l'invitation de dépôt qui fonctionne bien. La seule remarque, c'est que la lange par défaut est systématiquement l'anglais (US). Les domaines et notifications ainsi que la langue de notification pour l'upload-request est paramétré en Français, j'ai même essayé de mettre dans le fichier index.html de upload-request <html lang=fr> (au lieu de lang=en)  mais rien n'y fait : il faut toujours changer la langue manuellement.
Pouvez-vous m'indiquer comment changer la langue par défaut ?

En vous remerciant d'avance

Philippe NICOLAS

**Comment by fmartin-linagora** [comment]
Bonjour,

Je ne suis pas sur de comprendre de quelle langue il s'agit, celle des emails ou du portail externe ?

**Comment by EPTBSGL** [comment]
Il s'agit de la langue par défaut du portail externe. Mais apparemment, je n'ai plus le problème (certainement encore des problèmes de cache). Pourriez-vous simplement me confirmer si la balise <html lang=fr-FR> (originellement avec la valeur "en") a une influence ou non sur la langue par défaut du portail externe ?

**Comment by fmartin-linagora** [comment]
Non, elle n'a aucune influence. Le site reste par défaut en anglais et les utilisateurs peuvent alors changer la langue.
