### ISSUE TITLE
upload-request URL is not working on 4.1.0

### ISSUE THREAD

**Issue by annmaria1** [linagora/linshare#161]
Hi Linshare,

I'm getting tomcat admin interface when opening the below upload-request URL. There is no issue for accessing linshare-user and linshare-admin URL's.

http://linshare-upload-request.local/#/38709b3b-4221-47ff-9977-30427e693e33

Product version : 4.1.0
Core version : 4.1.0-1
O/S : Redhat 8

![image](https://user-images.githubusercontent.com/41739394/112589085-81a66800-8e26-11eb-8963-348139e05310.png)

cat /etc/httpd/sites-available/linshare-upload-request.conf
<VirtualHost *:80>
ServerName linshare-upload-request.local
DocumentRoot /var/www/linshare-ui-upload-request
<Location /linshare>
    ProxyPass http://127.0.0.1:8080/linshare
    ProxyPassReverse http://127.0.0.1:8080/linshare
    ProxyPassReverseCookiePath /linshare /

    # Workaround to remove httpOnly flag (could also be done with tomcat)
    Header edit Set-Cookie "(JSESSIONID=.*); Path.*" "$1; Path=/"
    # For https, you should add Secure flag.
    # Header edit Set-Cookie "(JSESSIONID=.*); Path.*" "$1; Path=/; Secure"

    #This header is added to avoid the  JSON cache issue on IE.
   Header set Cache-Control "max-age=0,no-cache,no-store"
</Location>

ErrorLog /var/log/httpd/linshare-ui-upload-request-error.log
CustomLog /var/log/httpd/linshare-ui-upload-request-access.log combined
</Virtualhost>

Kindly support it.

**Comment by fmartin-linagora** [comment]
Hi,
Did you enable the upload-request vhost file ? (because I saw the path is /etc/httpd/sites-available/linshare-upload-request.conf)
Regards

**Comment by annmaria1** [comment]
Thanks for the help. Its working now.

**Comment by annmaria1** [comment]
Hi,

When I use uploadrequest as subdirectory of main domain, I'm getting below error. Can you help me on it. Im getting blank page on browser.


root@linshare01#curl http://linshare-user.test.com/uploadrequest

<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><link rel=icon href=/favicon.ico><title>LinShare Upload Request</title><link rel=stylesheet href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900"><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css><link href=/css/chunk-09b720fd.4cee38b9.css rel=prefetch><link href=/css/chunk-12410e11.9a3c5f79.css rel=prefetch><link href=/css/chunk-3344b98f.2c972bba.css rel=prefetch><link href=/css/chunk-6062f725.21c5bb70.css rel=prefetch><link href=/css/chunk-7e0fda80.67ba89d5.css rel=prefetch><link href=/css/chunk-b5445a74.ed4bcf6f.css rel=prefetch><link href=/css/chunk-c9dfe73c.7646606d.css rel=prefetch><link href=/js/chunk-09b720fd.aad43111.js rel=prefetch><link href=/js/chunk-12410e11.58eb0fff.js rel=prefetch><link href=/js/chunk-3344b98f.e2653051.js rel=prefetch><link href=/js/chunk-6062f725.a5d0faa8.js rel=prefetch><link href=/js/chunk-7e0fda80.4c886ecc.js rel=prefetch><link href=/js/chunk-b5445a74.ba65aa63.js rel=prefetch><link href=/js/chunk-c9dfe73c.3142d8ed.js rel=prefetch><link href=/css/app.25203dee.css rel=preload as=style><link href=/css/chunk-vendors.d84eedbe.css rel=preload as=style><link href=/js/app.31e18bdc.js rel=preload as=script><link href=/js/chunk-vendors.8c8e833c.js rel=preload as=script><link href=/css/chunk-vendors.d84eedbe.css rel=stylesheet><link href=/css/app.25203dee.css rel=stylesheet></head><body><noscript><strong>W**e're sorry but LinShare Upload Request doesn't work properly without JavaScript enabled.** Please enable it to continue.</strong></noscript><div id=app></div><script src=/js/chunk-vendors.8c8e833c.js></script><script src=/js/app.31e18bdc.js></script></body></html>[root@linshare01 www]#


cat /etc/httpd/sites-available/linshare-user.conf
<VirtualHost *:80>
ServerName linshare-user.test.com
DocumentRoot /var/www/linshare-ui-user
Alias /uploadrequest /var/www/linshare-ui-upload-request

<Location /linshare>
    ProxyPass http://127.0.0.1:8080/linshare
    ProxyPassReverse http://127.0.0.1:8080/linshare

    ProxyPassReverseCookiePath /linshare /

Header edit Set-Cookie "(JSESSIONID=.*); Path.*" "$1; Path=/"

Header set Cache-Control "max-age=0,no-cache,no-store"

</Location>

ErrorLog /var/log/httpd/linshare-user-error.log
CustomLog /var/log/httpd/linshare-user-access.log combined
</Virtualhost>

Sorry to disturb you.
Thanks,
Jinju.

**Comment by fmartin-linagora** [comment]
Hi,
It is not an error, just the default page when you try to access it with a client without the support of Javascript. :)
Regards.

**Comment by annmaria1** [comment]
Hi,

I can access the URL http://linshare-upload-request.local without any issue.
But in the same browser, I can't access it like http://linshare-user.test.com/uploadrequest.
I have shared the apache configuration here. The same configuration is working for linshare version 1.

Any idea how to resolved it.

Thanks
Jinju

**Comment by fmartin-linagora** [comment]
Hi,

Indeed, Upload request module does not support to be deployed into a folder. For now it must be at the document root of your server. 

Can you create a new dedicated issue on github, as a feature request ?

Tks.

**Comment by annmaria1** [comment]
Thanks Fred.

I saw the below comment on the portal. Waiting for the new release.

[image: image.png]

**Comment by annmaria1** [comment]
Hi Fred,

Kindly let me know about the next release of version 4.1.2

Thanks
Jinju.

**Comment by fmartin-linagora** [comment]
Hi,
I hope, we will release the4.1.2  by the end of the next week. :)
Fred

**Comment by annmaria1** [comment]
Thanks Fred
