### ISSUE TITLE
upload-request issues and enhancement

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#162]
Hello,
I have tested the upoad-request but I have somme issue with it.

When I put the invitation in archive, if I doesn't select "copy files to personnal space", files are not available anymore (that seems normal) but the personnal space quota is not updated (even after midnight cron).

Another bug, when the invitation is automatcly closed, it send an email to recipient that resume what he sent. But it always says "1 files":
![image](https://user-images.githubusercontent.com/33221710/113406563-fa1fa280-93ab-11eb-8827-65e135d04afb.png)
The creator receive a good message.

Another issue, when I send files of some MB (100-200MB) I can send it up to 200Mb/s. If I sent a big file of 10GB, it send it at 70Mb/s.
On the "normal" interface, I can upload big filles up to 800Mb/s.
Is there something to change in parameters for the upload-request interface?

Last thing that could be an enhancment will be to have something more visible when we send a file, not just the little red indication on the top of the interface. If we scroll down before sending the file, this little indication can't be seen and we don't know if it's working. A little popup like when the upload is done would be great.

This new function is great as well, even if it will be better to have it on the same top domain, not a new one (maybe it's possible but I didn't found how for now).

Best regards,

**Comment by fmartin-linagora** [comment]
Hi,
Thanks for all these feedbacks, It is really appreciated. Just to let you know, in a general manner,  it would be easier to answer you, to follow these issues if you could create one issue per problem/question or at least use numbers to identify them. ;)

1. Quota issue:
Indeed, there is a bug :'( 

2. File count issue
It is a known bug. we are already on it. tks

3. Speed issue
I have to dig a bit about this one, I don't have the answer yet. 

4. Upload queue issue
I think we already have a popup message when the file is uploaded but I agree that we need a more obvious feedback.

5. Folder deployment
Already notice, issue created. We will look at it.

Regards,
Fred

**Comment by matdemb** [comment]
Thanks Fred.
Next time I'll create one question by issue, you're true, it will be easier to follow it.
Corry for that.
Best regards,

**Comment by fmartin-linagora** [comment]
Re,

For the "3. Speed issue" topic, I found the issue. We are currently using file chunking to send them to the server. For now ui-upload-request is using 1Mo while ui-user is using dynamic chunking algorithm (between 10Mo and 100Mo).

We will study this improvement, probably in version 4.2.

As a first step, I think we can increase the chunk size from 1Mo to 10Mo.

Regards,
Fred.

**Comment by fmartin-linagora** [comment]
Hi,

For the "5. Folder deployment" topic, it is already fixed (4.1.2 snapshot) and will be part of the next security release.

Fred

**Comment by matdemb** [comment]
Hi, 
how  does it works?
The [doc](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-debian.md#first-access-1) indicate to use  http://linshare-user.local/upload-request/ but I see no configuration part that talk about this...
the vhost configuration example still indicate  http://linshare-user.local/upload-request/ and I don't see how we can do to use the main user domain.

Regards,

**Comment by fmartin-linagora** [comment]
Hi, 
Indeed there is a tiny glitch in the documentaion, we should use this link to access it :  http://linshare-upload-request.local. 
Regards,

**Comment by matdemb** [comment]
Hi,
so it's the normal way where we need to have a specific subdomain for upload-request.
Will it be fully integrated to linhare to only have one domain (and configuration an certificate)?
I'm not sure to understand your response for the "5. Folder deployment" topic.
Regards,

**Comment by fmartin-linagora** [comment]
Hi,
In the documentation we used a subdomain for the Upload Request because it is easier. But if you want to deploy it as folder under ui-user, like http://linshare-user.local/upload-request/, of course you can, you will just have to adapt the configuration by your self. You will need to remove the vhost you don't use, put the UR app in a folder inside ui-user vhost and update the notification URL in the admin interface.
It is not part of the official documentation because wWe can't cover all setups :smile: 
This works since 4.1.2 release.

**Comment by matdemb** [comment]
it works. On my test it didn't, I probably forgot to do something.
Thanks
