### ISSUE TITLE
Compatibilité Linshare avec Rhel 8

### ISSUE THREAD

**Issue by Sand0w** [linagora/linshare#163]
Bonjour,

Suite à la sortie de la dernière version de Linagora en version 4.1.1, pourriez-vous m'indiquer si cette version est compatible avec Rhel 8 ? et si les versions antérieures à la 4.1.1 le sont.

En vous remerciant par avance.

**Comment by fmartin-linagora** [comment]
Bonjour,

Nous supportons LinShare uniquement sur Centos 7 et **Debian 10 (recommandé)** pour les versions 4 et supérieures. Cette limitation est principalement dû à la présence ou non des composants nécessaires à LinShare.

Pour la version 4.1 de LinShare,  nous recommandons les composants suivants:
* Java 11
* Apache 2.4
* Tomcat 9
* PostgreSQL 11
* MongoDB 4.2

Si vous êtes capable d'installer et de configurer ces composants et d'adapter la [documentation officielle](https://github.com/linagora/linshare/blob/master/documentation/FR/installation/linshare-install-centos.md), vous devriez pouvoir faire fonctionner LinShare.

Cordialement,
