### ISSUE TITLE
Document cleaner for Uploaded file.

### ISSUE THREAD

**Issue by annmaria1** [linagora/linshare#164]
Hi Linshare,

Which setting will help to clean expired files of uploaded document.

Thanks
![linshare](https://user-images.githubusercontent.com/41739394/113819056-67f61080-9796-11eb-8a3f-de9063146c21.jpg)

Jinju.

**Comment by fmartin-linagora** [comment]
Hi,

Once the upload request closed manually or expired (closed automatically by the system), you need to archive the upload request. When you will try, LinShare will ask you if you want to keep a copy of files in your personal space or remove them.

Fred

**Comment by fmartin-linagora** [comment]
Hi,
There is no automatic archiving job if it was what you meant.
Fred

**Comment by fmartin-linagora** [comment]
BTW, there was a tiny bug about the deletion of files once archived. it will be fixed in 4.1.2, we plan to release by the end of this month.

**Comment by annmaria1** [comment]
Hi Fred,

What is it means COMMON.ENUM.LOG_ACTION.FILE_SHARE_WITH_ALERT_FOR_USD. I
can see it when I check on History in the admin portal.


[image: image.png]

Recipient got the below mail.
"LinShare workspace is about to be deleted"

Thanks
Jinju

**Comment by fmartin-linagora** [comment]
Hi,
it means we have a missing translation key. :)
I can't see your image neither undestand your issue

**Comment by annmaria1** [comment]
Hi Fred,

One of the users shared a file. We are getting the below error when we open
it.

[image: image.png]

**Comment by fmartin-linagora** [comment]
ok, but I still can't see the screenshot. :cry:

**Comment by annmaria1** [comment]
Hi Fred,

Kindly ignore the above request. It could be the issue of the end user.

Thanks
Jinju
