### ISSUE TITLE
Install linshare-ui-admin component to configure LinShare.

### ISSUE THREAD

**Issue by hoannguyen1352** [linagora/linshare#165]
I think i installed The linshare but I'm having trouble installing the linshare-ui-admin component to configure LinShare.Can you help me please? I don't know what i did wrong.

![Screenshot from 2021-04-15 09-48-36](https://user-images.githubusercontent.com/71828341/114808411-62ba4680-9dd2-11eb-802a-f5acdf3a0d1f.png)
![Screenshot from 2021-04-15 09-49-02](https://user-images.githubusercontent.com/71828341/114808418-651ca080-9dd2-11eb-8616-fc7c84f196be.png)
![Screenshot from 2021-04-15 10-20-36](https://user-images.githubusercontent.com/71828341/114809440-63ec7300-9dd4-11eb-8e6f-32320963aed5.png)

**Comment by hoannguyen1352** [comment]
![Screenshot from 2021-04-15 10-20-36](https://user-images.githubusercontent.com/71828341/114809376-43241d80-9dd4-11eb-99ac-cc353ee0c023.png)

**Comment by fmartin-linagora** [comment]
Hi,

The admin interface seems to be working well, you can see the dashboard and there is no errors in the logs. What does bother you ?

**Comment by hoannguyen1352** [comment]
Hi,
Yes the admin interface to be working well.But the user interface have some problem. I use 127.0.0.1:8080/linshare to go it and it happen some problems 
![Screenshot from 2021-04-15 00-55-31](https://user-images.githubusercontent.com/71828341/114834348-5065eb80-9d85-11eb-9167-9ad82ac2d2a5.png)

**Comment by fmartin-linagora** [comment]
Hi,

As you saw in the [installation guide](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-debian.md), we used 2 vhosts to expose admin and user interfaces. This is mandatory, you must not use the IP address otherwise you will only be able to reach the admin interface (default vhost).

So you need to access to these interfaces using their vhost names:  http://linshare-user.local and http://linshare-admin.local

**Comment by hoannguyen1352** [comment]
Hi,
What can i do to access http: //linshare-user.local ? 
I don't go to http: //linshare-user.local.

**Comment by hoannguyen1352** [comment]
this is two file about Vhost Configuration What i did changed  
https://drive.google.com/drive/folders/12RgIs9id5HFR1xjT8nqmM7VGuQMG453-?usp=sharing

**Comment by hoannguyen1352** [comment]
This is two file vhost Configuration What I changed 
Kindly advise what needs to be done.
https://drive.google.com/drive/folders/12RgIs9id5HFR1xjT8nqmM7VGuQMG453-?usp=sharing

**Comment by fmartin-linagora** [comment]
Did you forgot to add linshare-user.local in your /etc/hosts file ? 

Before the first access to LinShare you need to add all linshare-*.local ServerNames to the /etc/hosts file.
```
127.0.0.1   linshare-user.local
127.0.0.1   linshare-admin.local
127.0.0.1   linshare-upload-request.local
```

**Comment by hoannguyen1352** [comment]
I fixed it.I will close issue.
Thank you verry much
