### ISSUE TITLE
Don't change password and add technical accounts in LinShare administration interface

### ISSUE THREAD

**Issue by hoannguyen1352** [linagora/linshare#166]
Hi, 
I have some problems When change password and add technical accounts in LinShare administration interface

![Screenshot from 2021-04-16 10-57-00](https://user-images.githubusercontent.com/71828341/114969687-1d197e80-9ea3-11eb-9f01-acd25da4dd9f.png)

**Comment by marwanJebahi** [comment]
Hello,
Thank you for your feedback.
We have an issue in progress concerning this bug, it will be treated ASAP.
If the entered password does not satisfy the default conditions set  in your `linshare.properties` of the password conplexity, you will receive 400 bad request with an error `28410`, you can check this section :
```
# Minimum length of password
password.min.length=12

# Maximum length of password
password.max.length=30

# Minimum Number of uppercase in password
uppercase.character.password=1

# Minimum Number of lowercase in password
lowercase.character.password=1

# Minimum Number of digits in password
digits.character.password=1

# Minimum Number of special characters in password
special.character.password=1
```

Here is the error message which you will receive:

```
[Password must be 12 or more characters in length., Password must contain 1 or more uppercase characters., Password must contain 1 or more digit characters., Password must contain 1 or more special characters.]
```

Regards.

**Comment by MewHoEn** [comment]
I understood. 
Thank you verry much

**Comment by hoannguyen1352** [comment]
I understood.
Thank you very much
