### ISSUE TITLE
Create a new user interface 

### ISSUE THREAD

**Issue by MewHoEn** [linagora/linshare#167]
Hi,
I'm sorry to bother you.
I'm a new user.I don't know How to create a new acount in linshare-user.local.
Can you give me some advice? or can you have a guide for using Linshare ?
I was confused about this :(((

**Comment by fmartin-linagora** [comment]
Hi, 

Users in LinShare are provisioned/created from the LDAP directory. It means Linshare does not manage users. You need to created them in your LDAP.

So once LinShare is installed you must create a domain and add  a userProvider (link to LDAP)

**Comment by MewHoEn** [comment]
Can you give me some documents about creating a domain and add a userProvider  (link to LDAP) ?
I tried to find document or guide but i did't find it.

**Comment by fmartin-linagora** [comment]
Sorry, I only have a old [french version of the documentation](https://github.com/linagora/linshare/blob/master/documentation/FR/administration/linshare-admin.md) but we are currently working on it to update it and then translate it in english.

**Comment by fmartin-linagora** [comment]
As a tiny helper, you can go to the admin page, go to "Manage domain" and create a domain. Once the domain is created, you can edit it and add a user provider.

**Comment by MewHoEn** [comment]
Thank you so much!
I really appreciate it.
You support very professional.
