### ISSUE TITLE
Some question about create user local and LDAP 

### ISSUE THREAD

**Issue by MewHoEn** [linagora/linshare#168]
Hi,
I installed and create some user in LDAP.
I connected to LDAP connection in admin interface.
I am not understanding for create user local.It uses the imformation: email and password in order to login in user interface.
Can you give me some advices?

**Comment by fmartin-linagora** [comment]
Hi,

Once you created your LDAP connection, you have to update the domain (top or sub domain) in order to add an UserProvider (it is composed of the ldap connection, the baseDN of your LDAP, and a DomainPattern which is just some ldap queries/filters). Then if all parameters are good, you should be able to test it by searching your ldap users from the User management page of the LinShare Admin interface.

Fred

**Comment by MewHoEn** [comment]
What is a structure of user local linshare in ldap? 
I created a new as:
dn: uid=test1,ou=People,dc=linshare,dc=org
uid: test1
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top
sn: Test1
cn: admin
userPassword: {SSHA}OMGJWWCNYl+aVh1EqkKL8dOQ36n8b1NS
mail: test1@linshare.org

**Comment by MewHoEn** [comment]
What is a structure of a user local in ldap?
i created a new user with some information:
dn: uid=test1,ou=People,dc=linshare,dc=local
uid: test1
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top
sn: Test1
cn: admin
userPassword: {SSHA}OMGJWWCNYl+aVh1EqkKL8dOQ36n8b1NS
mail: test1@linshare.local

Is it true?

**Comment by MewHoEn** [comment]
Hi,
I created a domain TopDm and add some attributes of it. 
I find email and it show some problems.
![Screenshot from 2021-04-22 08-30-25](https://user-images.githubusercontent.com/82631284/115642612-7cfda280-a345-11eb-8730-7ac888ba55bf.png)

**Comment by fmartin-linagora** [comment]
Hi, I think you get this error because the user does not exist yet in the database. Nevertheless, it seems you can find user in your LDAP directory.
Please go to "Manage user" and search your user, you should be able to find it. if you click on the result, the ui should ask you if you want to create the profile in the database. You can do it if you want.
As a reminder, the user's profile are create when you triy to edit the profile in admin portal, when you log in the user portal, when you share documents which the user as recipient or when you add him as member of a workgroup.

Fred

**Comment by MewHoEn** [comment]
I can't see a user in manage user 
![Uploading Screenshot from 2021-04-22 15-44-48.png…]()

**Comment by MewHoEn** [comment]
i can't search your user in manage user. 
![Screenshot from 2021-04-22 15-44-48](https://user-images.githubusercontent.com/82631284/115685023-0fbc3280-a382-11eb-932f-ff3dc1b43241.png)

**Comment by fmartin-linagora** [comment]
when you put "local" in the "Mail" field, what does happen ?

**Comment by MewHoEn** [comment]
I don't put "local" in the "Mail" field.

**Comment by MewHoEn** [comment]
Where is it put?

**Comment by fmartin-linagora** [comment]
I mean in the form (screenshot above), can you try to trigger the search by tapping "local" into the input text called "Mail" ?

**Comment by MewHoEn** [comment]
![Screenshot from 2021-04-22 15-53-46](https://user-images.githubusercontent.com/82631284/115685991-f4055c00-a382-11eb-9d66-bb45f1b2cbb6.png)

i tried put my email.

**Comment by MewHoEn** [comment]
i can't why it can find in inconsistent users.But when i put "Email" in manage users it  appears.

**Comment by fmartin-linagora** [comment]
it is weird, i though your test user is user@linshare.local. why are you looking for user@linshare.host in "Manage user" ? you can just search for linshare.

**Comment by MewHoEn** [comment]
Sorry i seem wrote wrong it But i tried find it again and some another email. I don't find we.   
![Screenshot from 2021-04-22 23-08-16](https://user-images.githubusercontent.com/82631284/115747645-a9ee9b80-a3bf-11eb-9dc0-04afaf5f118f.png)

**Comment by fmartin-linagora** [comment]
Please look at the tomcat server log, the catalina.out. You will find some explaination why LinShare can't find your user.

**Comment by MewHoEn** [comment]
[catalina.2021-04-22.log](https://github.com/linagora/linshare/files/6359766/catalina.2021-04-22.log)
my file tomcat server log

**Comment by MewHoEn** [comment]
i can't find file catalina.out in tomcat

**Comment by fmartin-linagora** [comment]
you need to provide me the server's logs when you try to search your user. the goal is to see if the server display an error that will indicate to us what is the issue in your configuration

**Comment by MewHoEn** [comment]
my files: 
admin:///var/log/tomcat9/catalina.out
admin:///var/log/tomcat9/catalina.2021-04-22.log

**Comment by MewHoEn** [comment]
my files:
admin:///var/log/tomcat9/catalina.out
admin:///var/log/tomcat9/catalina.2021-04-22.log

**Comment by MewHoEn** [comment]
my files log :
https://drive.google.com/drive/folders/1CQFmBEx7bYh4sBXbwdHj7lCIi_lhjLzY?usp=sharing

**Comment by fmartin-linagora** [comment]
As you saw in the catalina.out log file, you have some errors:
```
[2021-04-22 12:26:14] [info] [ERROR]:http-nio-8080-exec-10:20210422.122614:org.linagora.linshare.ldap.JScriptUserLdapQuery:dnToObject:Can not convert dn : 'uid=test1' to an object.
[2021-04-22 12:26:14] [info] [ERROR]:http-nio-8080-exec-10:20210422.122614:org.linagora.linshare.ldap.JScriptUserLdapQuery:dnToObject:The field 'user_mail' (ldap attribute : 'test1@linshare.local') must exist in your ldap directory, it is required by the system.

```
it means you have configured LinShare to look into the  LDAP Directory for the 'test1@linshare.local' attribute. I am pretty sure there is no attribute called 'test1@linshare.local'. 

For yhe field 'user_mail', LinShare is expecting the name of a LDAP attribute in the user ldap entry that will contain his emails. By the fault, the attribute name is 'email' as it is provided by  default DomainPattern models ;)

**Comment by MewHoEn** [comment]
I fixed it.Thank you
