### ISSUE TITLE
Error 46001 When i create a linshare profile in database

### ISSUE THREAD

**Issue by hoannguyen1352** [linagora/linshare#169]
When i create a linshare profile in database.It showed a error.
![Screenshot from 2021-04-22 19-58-46](https://user-images.githubusercontent.com/71828341/115718938-d09fd880-a3a5-11eb-86b5-0b102a37e347.png)

**Comment by fmartin-linagora** [comment]
Hi,

Which are the versions of each composant ?

Fred

**Comment by hoannguyen1352** [comment]
I am using versions 4.1.1

**Comment by fmartin-linagora** [comment]
Did you installed LinShare manually or using our docker-compose ?

**Comment by hoannguyen1352** [comment]
i installed it manually

**Comment by fmartin-linagora** [comment]
CentOS or Debian ?
