### ISSUE TITLE
Probléme de partage

### ISSUE THREAD

**Issue by mounir81** [linagora/linshare#17]
Bonjour,

J’ai installé la version linshare 2.0.3 sur Redhat 7.3 en suivant la documentation linshare-install-centos-7.md.
Jusqu’à présent j'arrive à me connecter et uploader les fichiers, sauf que quand je procédé au partage des fichiers je reçois l'erreur suivant "Mauvais Passerelle"

Pourriez-vous svp, m'aider a résoudre ce problème.

Ci-après les logs Tomcat.

[Thu Dec 21 14:05:51.604757 2017] [proxy_http:error] [pid 17807] (70007)The timeout specified has expired: [client 10.100.120.223:57638] AH01102: error reading status line from remote server 127.0.0.1:8080, referer: http://linshare-user.local/
[Thu Dec 21 14:05:51.604867 2017] [proxy:error] [pid 17807] [client 10.100.120.223:57638] AH00898: Error reading from remote server returned by /linshare/webservice/rest/user/v2/shares, referer: http://linshare-user.local/

Cordialement

**Comment by fmartin-linagora** [comment]
Bonjour,
Vous avez une erreur de timeout avec le serveur proxy. L'instruction pour paramétrer un serveur apache est : ProxyTimeout nb_secondes.
Cordialement,
