### ISSUE TITLE
invitation de dépôt (upload request)

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#170]
Bonjour,

Lorsque je reçois la notification m'alertant que l'invitation de dépôt va bientôt être clôturée, les dates de clôture et d'activation sont inversées (voir pièce jointe). De plus, le nombre de jours restant est négatif (ici -5). Ce problème existait déjà dans la version précédente (4.1.0).

Y a-t-il une correction ?

Cordialement
![PbDatesInvitatonDépot](https://user-images.githubusercontent.com/33631516/116980444-859b9480-acc6-11eb-8dbb-2992b45b2c04.png)

**Comment by marwanJebahi** [comment]
Hello,
Thank you for your feedback.
Issue confirmed, it will be treated soon, we will keep you informed.
Regards

**Comment by annmaria1** [comment]
Kindly provide the bug fix.

**Comment by marwanJebahi** [comment]
Hello,

This issue is fixed and it will be available on 4.2 version of LinShare, it will be released in few days.

Regards
