### ISSUE TITLE
upload-request - expiration date

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#172]
Hi,
I tried to modify the date of expiration to the current date at a later hour  (some hours later) but nothing happen when I want to save.
If I put an other day, it work.
Regards,

**Comment by fmartin-linagora** [comment]
Hi,

Are you still experiencing some trouble or can we close this issue ?

Regards,

**Comment by matdemb** [comment]
Hi,
it's ok for this, but I just find a new one with activation date. I do another ticket?
Regards,

**Comment by fmartin-linagora** [comment]
Yes, please one ticket per issue. It is easier to manage.
