### ISSUE TITLE
upload-request - mauvaise requềte

### ISSUE THREAD

**Issue by si-pg** [linagora/linshare#173]
Bonjour,

Très ancien utilisateur de Linshare (et ravi) Je teste upload request en 4.1.2.
Erreur : mauvaise requete quand je crée une invitation
extrait Catalina :
[ERROR]:http-nio-8080-exec-4:20210611.114652:org.linagora.linshare.webservice.interceptor.UnrecognizedPropertyExceptionMapper:toResponse:An unrecognized field excpetion was caught : Unrecognized field "dirty" (class org.linagora.linshare.core.facade.webservice.common.dto.UploadRequestCreationDto), not marked as ignorable (15 known properties: "protectedByPassword", "expiryDate", "body", "activationDate", "canClose", "enableNotification", "maxFileCount", "label", "notificationDate", "locale", "maxDepositSize", "contactList", "maxFileSize", "canDelete", "canEditExpiryDate"])
 at [Source: (org.apache.cxf.transport.http.AbstractHTTPDestination$1); line: 1, column: 302] (through reference chain: org.linagora.linshare.core.facade.webservice.common.dto.UploadRequestCreationDto["dirty"]). 

Avez vous une idée ?
Merci pour vos efforts

**Comment by fmartin-linagora** [comment]
Bonjour,
Il semblerait à la vue de votre erreur que l'interface web envoie un champ inconnu au serveur. 
Quelle version de l'interface utilisateur et du backend avez vous déployé ?
Cdt,

**Comment by si-pg** [comment]
Bonjour et merci pour l'attention portée à ma question.
J'étais full 4.1.2.
Mais visiblement ui-client ne s'était pas bien déployé.
Après un nouveau tar de linshare-ui-user cela semble mieux fonctionner.
Merci

**Comment by fmartin-linagora** [comment]
Bonjour,
Vous me rassurez, je trouvais le problème un peu curieux. :smiley: 
N'hésitez à créer de nouveau des tickets si vous rencontrez d'autres soucis.
Bonne journée.
