### ISSUE TITLE
upgrade to 4.2 question

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#174]
Hi,
is it possible to upgrade from 2.3 to 4.2 directly, or we need to upgrade via 4.0, 4.1 then 4.2?
Thanks,

**Comment by marwanJebahi** [comment]
Hello,

To upgrade to 4.2 version of LinShare, you need to upgrade to 4.0, 4.1 before. Here is the [upgrade guide](https://github.com/linagora/linshare/blob/master/documentation/EN/upgrade/linshare-upgrade-from-v4.1-to-v4.2.md).

Regards
