### ISSUE TITLE
sql Migration script issue

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#175]
Hi,
I tried to migrate from 4.1 to 4.2 but the sql migration script has an error:

psql:linshare-core-sql/postgresql/Migration_4.1.0_to_4.2.0.sql:335: INFO:  MONTHLY STAT with ID "1825" DATE : 2020-11-30 23:59:59.999
psql:linshare-core-sql/postgresql/Migration_4.1.0_to_4.2.0.sql:335: INFO:  current_actual_operation_sum previous : 8439182255
psql:linshare-core-sql/postgresql/Migration_4.1.0_to_4.2.0.sql:335: INFO:  current_actual_operation_sum next : <NULL>
psql:linshare-core-sql/postgresql/Migration_4.1.0_to_4.2.0.sql:335: ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « create_operation_sum »
DÉTAIL : La ligne en échec contient (1825, WORK_GROUP_MONTHLY_STAT, 2020-12-01 00:00:00.743, 2020-11-30 23:59:59.999, 10, 5, 5, null, null, null, null, 1023, 1008, 1)
CONTEXTE : instruction SQL « UPDATE statistic
                                                SET
                                                        actual_operation_sum = current_actual_operation_sum,
                                                        create_operation_sum = current_create_operation_sum,
                                                        diff_operation_sum = current_diff_operation_sum,
                                                        delete_operation_sum = current_delete_operation_sum
                                                WHERE id = monthly_stat_row.id »
fonction PL/pgsql ls_compute_monthly_workgroup_statistic(), ligne 36 à instruction SQL

the line in my table:
linshare=> select * from statistic WHERE id = 1825;
  id  |     statistic_type      |      creation_date      |     statistic_date      | operation_count | delete_operation_count | create_operation_count | create_operation_sum | delete_operation_sum | diff_operation_sum | actual_operation_sum | account_id | domain_id | domain_parent_id
------+-------------------------+-------------------------+-------------------------+-----------------+------------------------+------------------------+----------------------+----------------------+--------------------+----------------------+------------+-----------+------------------
 1825 | WORK_GROUP_MONTHLY_STAT | 2020-12-01 00:00:00.743 | 2020-11-30 23:59:59.999 |              10 |                      5 |                      5 |                 5695 |                 5695 |              11390 |          12055986040 |       1023 |      1008 |                1

No "null" value in this entry.
I don't understand why it doesn't work...
Any idea?

**Comment by matdemb** [comment]
I think my databse is not correct ,I will try with a working one and tell you if it works.

**Comment by fmartin-linagora** [comment]
Hi,
Or maybe we have a glitch in our upgrade script. :s

**Comment by matdemb** [comment]
Hi,
same issue with a database restored from my production server.
`DÉTAIL : La ligne en échec contient (101131, WORK_GROUP_MONTHLY_STAT, 2020-12-01 00:01:08.291, 2020-11-30 23:59:59.999, 14, 14, 0, null, null, null, null, 65178, 1001, 1)
`
If I look at the statistic table for the account_id that return an error, it seems to have some lacks in it for WEEKLY_STAT between 2020-08-23 and 2020-11-09  AND MONTHLY_STAT between 2020-09-30 and 2020-12-01 (but maybe it's normal and there is no link) .
I put an extract of the table in attachment.
[table-stats.txt](https://github.com/linagora/linshare/files/6877430/table-stats.txt).

Regards,

**Comment by fmartin-linagora** [comment]
Hi,
Sorry for the delay, most of the team is in holidays ! :smile: 
I will try to look at this error ASAP, this week I hope.

**Comment by fmartin-linagora** [comment]
Hi,

I managed to reproduce the bug and I am working on it.
I will keep you posted as soon as we release the fix.

Fred

**Comment by fmartin-linagora** [comment]
Hi,
It is fixed in version 4.2.2. You can find the changelog [here](is fixing the upgrade process from LinShare 4.1 to 4.2 (SQL and upgrade tasks)).
Regards,
