### ISSUE TITLE
download.linshare.org

### ISSUE THREAD

**Issue by fir3wall** [linagora/linshare#176]
Hi,

Download URL from website or installation guides seems not working anymore:
http://download.linshare.org/versions/

Where I can find releases now as Github only got source code not artefacts as good as I can see?

Thanks
D

**Comment by fmartin-linagora** [comment]
Hi,
We are experiencing some outages with our infrastructure. For now, this service is offline but it will be back as soon as possible.
Regards,

**Comment by fmartin-linagora** [comment]
it is back online.

**Comment by fmartin-linagora** [comment]
For the record, most of all artifacts of download.linshare.org are hosted here https://nexus.linagora.com/#view-repositories;linshare-releases~browseindex

**Comment by fir3wall** [comment]
Many thanks @fmartin-linagora
