### ISSUE TITLE
upload-request ui

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#179]
Hello,
on the last upload-request ui (4.2.2), there is a bug on french version and on the russian one.
On french, the "+" doesn'nt appear and the "supprimer" appear a little, it's not hidden.
![image](https://user-images.githubusercontent.com/33221710/129568696-00394289-3fcb-4de2-8b0f-967a091c617c.png)

On the Russian version the "+" doesn't appear, just a white zone.

Kind regards,

**Comment by fmartin-linagora** [comment]
Hi,

Thanks for the report, our QA already noticed it and it will be fixed in the next version (4.2.3).

Regards

**Comment by fmartin-linagora** [comment]
Hi,

LinShare 4.2.3 was released and should have fix it.
Can you confirm it to us ?

Regards,

**Comment by matdemb** [comment]
Hi,
yes it's fixed,
regards,
