### ISSUE TITLE
demo site down

### ISSUE THREAD

**Issue by Kai-M** [linagora/linshare#18]
http://demo.linshare.org/ is down. It's claiming to be under maintenance a very long time.

Further more an https call on the demo site leads to SSL_ERROR_RX_RECORD_TOO_LONG error in firefox.

**Comment by crssi** [comment]
Any progress here?

**Comment by fmartin-linagora** [comment]
Hi,
Yes, I've just finished to LinShare Demo back online.

**Comment by fmartin-linagora** [comment]
Thank you for warning us.

**Comment by crssi** [comment]
It still doesn't work. :(

Cheers

**Comment by fmartin-linagora** [comment]
You may have to wait a little bit for dns updates

**Comment by crssi** [comment]
Thank you... will check again tommorow and report back in case of troubles.
Cheers

**Comment by sburkett** [comment]
Down for me as well - not sure if this is a new issue, or related to the same as this one, but thought I would let you know!

**Comment by fmartin-linagora** [comment]
Hello,
I put the demo back online.
Thank you for warning us. ;)
Fred.
