### ISSUE TITLE
Problème affichage

### ISSUE THREAD

**Issue by k3vin62** [linagora/linshare#181]
Bonjour, 

J'essai en vain d'installer la dernière version sur une distribution Ubuntu. Je dois butter sur qqchose mais je ne sais pas quoi. A la fin de l'installation l'interface adminstrateur de linshare s'affiche mais tout le panel côté gauche n'apparait pas et pareil sur la fenêtre du milieu[](url)
![Capture](https://user-images.githubusercontent.com/89534587/130818387-dc16b379-a27f-4521-a026-8a333a88c8be.PNG)

Si une âme charitable à un peu de patience pour m'expliquer ce que je fait de travers !

Merci d'avance

**Comment by fmartin-linagora** [comment]
Bonjour,

Il semble que ce ticket soit resté sans réponse de votre part depuis un très long moment.
Je procède donc à sa clôture.
N’hésitez pas à ouvrir de nouveaux tickets si besoin.

Cdt,
