### ISSUE TITLE
The file couldn't be scanned (3007)

### ISSUE THREAD

**Issue by georgej77** [linagora/linshare#184]
Hi,

When I upload a file to linshare, I'm getting the attached error some time. It is "The file couldn't be scanned (3007)
Kindly let me know the root cause of it. Where should I check and resolved it.

Product version is 4.1.2

Thanks
george
![file_upload_error](https://user-images.githubusercontent.com/41739394/135253298-eb655016-ae4c-4720-929c-3cf195cbb995.jpg)

**Comment by fmartin-linagora** [comment]
Hi George,

it probably means that you enable the Antivirus functionality in ui-admin but you did not set up the proper parameters in linshare.properties file (antivirus IP and port)

Fred.

**Comment by georgej77** [comment]
Hi Fred,

Thanks for your reply.
Yes. I have enabled ClamAV on it. Please find the virus scanner configuration from linshare.properties. Can I add anything more? Please take note that above mentioned error will not come all time.

#******************** VIRUS SCANNER
#uncomment those properties if you want to enable clamav virus scanner feature
virusscanner.clamav.host=localhost
virusscanner.clamav.port=3310
# Every file which size is over than the value below (in bytes) will skip the virus scanner.
# virusscanner.limit.filesize=50000000

Thanks
George

**Comment by fmartin-linagora** [comment]
So did you install ClamAV ?

**Comment by georgej77** [comment]
Yes. It is there already.

# freshclam
Mon Oct  4 20:40:52 2021 -> ClamAV update process started at Mon Oct  4 20:40:52 2021
Mon Oct  4 20:40:52 2021 -> daily.cld database is up-to-date (version: 26312, sigs: 1938566, f-level: 90, builder: raynman)
Mon Oct  4 20:40:52 2021 -> main.cld database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Mon Oct  4 20:40:52 2021 -> bytecode.cvd database is up-to-date (version: 333, sigs: 92, f-level: 63, builder: awillia2)

**Comment by fmartin-linagora** [comment]
freshclam is the daemon responsible to update clamav database. So you need to install clamav daemon.

Then edit the file /etc/clamav/clamd.conf and check the parameters:
TCPSocket 3310
TCPAddr localhost
StreamMaxLength 50M

**Comment by fmartin-linagora** [comment]
Hi,
You can also increase a little bit the antivirus max size (StreamMaxLength 51M) and set LinShare to skip the antivirus when size is over 50M (virusscanner.limit.filesize=50000000)

Regards,

**Comment by georgej77** [comment]
Thanks. I have updated the configuration accordingly.
