### ISSUE TITLE
Mise à jour 4.1.1 vers 4.2.2

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#185]
Bonjour,
J'ai upgradé la version 4.1.1 en 4.2.2. J'ai donc exécuter la requête "Migration_4.1.0_to_4.2.0.sql
Lorsque j'exécute les tâches de mises à jour, la dernière renvoie cette erreur :
 10/13/2021 - 3:01:22 PM   INFO    : Task is starting ...
10/13/2021 - 3:01:22 PM   ERROR   : 1/1:Unhandled Exception in batch : org.linagora.linshare.core.upgrade.v4_2.AddMissingPropertiesToWorkGroupNodesUpgradeTaskImpl
10/13/2021 - 3:01:22 PM   ERROR   : Critical error for the current task. Task stopped.
10/13/2021 - 3:01:22 PM   ERROR   : Summary : success: 0, skipped: 0, errors: 0, unhandled errors: 1 
Est-ce que cela est bloquant (je peux quand même me connecter sur la plateforme utilisateur) ?
Comment corriger le problème ?

En vous remerciant d'avance pour vos réponses

**Comment by EPTBSGL** [comment]
Bonjour, j'ai toujours le même problème en passant de la version 4.1.1 à 4.2.3.
J'ai fait le test avec le smtp paramétré sur le port 25 sans authentification mais le pb persiste.
Je vous transmets les 1000 dernières lignes du catalina.out. Les opérations de mise à jour ont été faites en mode debug. 
[PbMAJ4.1-4.3.docx](https://github.com/linagora/linshare/files/7459068/PbMAJ4.1-4.3.docx)
[catalina.out.log](https://github.com/linagora/linshare/files/7459153/catalina.out.log)
Cordialement

**Comment by EPTBSGL** [comment]
Bonjour,
Je viens d'essayer avec cette dernière version : toujours le même problème.
[catalina.out.log](https://github.com/linagora/linshare/files/7463814/catalina.out.log)
Cordialement

**Comment by fmartin-linagora** [comment]
Bonjour,
Voici un nouveau correctif : https://nexus.linagora.com/content/repositories/linshare-snapshots/org/linagora/linshare/linshare-core/4.2.4-SNAPSHOT/linshare-core-4.2.4-20211103.102058-3.war
Pourriez-vous le tester ?
Cdt,
Fred

**Comment by EPTBSGL** [comment]
Bonjour,

Je viens de tester : je n'ai plus d'erreur mais des skipped. Je vais maintenant tester les envois de notifications en anonyme (port 25) et en authentifié Outlook (port 587). Je vous joins quand-même le Catalina.out
[catalina.out.log](https://github.com/linagora/linshare/files/7468592/catalina.out.log)
Cordialement

**Comment by EPTBSGL** [comment]
Re-bonjour,
Je viens de faire les tests fonctionnels : les envois de notifications se font bien en anonyme (port 25) comme en authentifié (port587 avec starttls activé et ssl désactivé dans le linshare.properties).
Reste 2 petits problèmes d'affichage à régler sur l'interface d'invitation de dépôt (voir document joint).
[PbMAJ-4.4.docx](https://github.com/linagora/linshare/files/7469039/PbMAJ-4.4.docx)
En vous remerciant pour tout votre travail, je reste à votre disposition pour d'autres tests si nécessaire.
Cordialement

**Comment by fmartin-linagora** [comment]
Re,
Oui, en effet j'ai "skipped" certains éléments.

Pouvez-vous cloturer ce ticket et en ouvrir un autre pour le problème d'invitation de dépot ? L'idée étant de ne pas mélanger les sujets.
Cdt,
