### ISSUE TITLE
upload-request - deposit size limit bug

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#186]
Hello,
I have created an deposit of 500MB with no file size limit and when I try to upload a file of ~250MB, it says that I have reached the max deposit size limit (no other file in it). 
It works up to ~220MB.
It seems there is a bug in limitation process.
the parameters of my deposit:
![image](https://user-images.githubusercontent.com/33221710/138287643-c9141076-d6dc-41aa-9633-799f617e228d.png)

Kind regards

**Comment by fmartin-linagora** [comment]
Hi,

LinShare 4.2.3 was released and should have fix it.
Can you confirm it to us ?

Regards,

**Comment by matdemb** [comment]
Hi,
yes it's ok on 4.2.3
Thanks.

**Comment by fmartin-linagora** [comment]
Perfect. I'm closing this issue.
