### ISSUE TITLE
Le dépôt à échoué

### ISSUE THREAD

**Issue by oliviermarie** [linagora/linshare#19]
Bonjour,

Sur certains fichiers pdf qui contiennent des plans et dont le poids faire environ 8Mo j'obtiens le message d'erreur "Le dépôt à échoué"

Le pdf est autorisé au niveau du type mime et le poids maxi des fichiers et positionné à 2Go

Je ne vois pas ce qui peut bloquer. J'ai tenter de trouver les logs mais je ne suis pas sûr d'être au bon endroit.

Dans le fichier /var/lib/tomcat7/logs/localhost.2018-01-12.log j'obtiens le message d'erreur. Je ne sais pas si le problème vient de là.

janv. 12, 2018 3:21:16 PM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: "Servlet.service()" pour la servlet CXFServlet a gÃ©nÃ©rÃ© une exception
java.lang.RuntimeException: org.apache.cxf.interceptor.Fault: Java heap space

dans le répertoire /var/log/apache2 rien de probant.

J'utilise linshare en version 1.12.3

C'est la première fois que je rencontre ce problème

Avez-vous une piste à explorer ?

D'avance merci

**Comment by fmartin-linagora** [comment]
Bonjour,

Quelles sont les options de démarrage que vous avez défini pour le tomcat ?
Je vous recommande d'effectuer une mise à jour vers la dernière version 1.12 dans le doute.

Cordialement,

**Comment by oliviermarie** [comment]
Bonjour,

Voici les options définies dans le fichier /etc/default/tomcat7

JAVA_OPTS="-Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC"
JAVA_OPTS="${JAVA_OPTS} -XX:MaxPermSize=256m -Djava.awt.headless=true -Xms512m -Xmx1538m -XX:-UseSplitVerifier"
JAVA_OPTS="${JAVA_OPTS} -Dlinshare.config.path=file:/etc/linshare/"
JAVA_OPTS="${JAVA_OPTS} -Dlog4j.configuration=file:/etc/linshare/log4j.properties"

Pensez-vous qu'il puisse y a voir un problème à ce niveau ?

Sinon je tenterai de mettre à jour la version comme vous le préconisez. 

Cordialement,

**Comment by fmartin-linagora** [comment]
Bonjour,

Les logs de l'applicatif sont normalement dans le fichier /var/log/tomcat7/catalina.out. Ce fichier vous permet de comprendre les erreurs que vous pouvez rencontrer sur LinShare.

Par ailleurs vous pouvez déjà tenter d'augmenter la mémoire allouer au tomcat : -XX:MaxPermSize=512m  -Xmx2048m 
Cordialement,

**Comment by fmartin-linagora** [comment]
Bonjour,
Le problème de mémoire Java heap space est géré par l'autre paramètre -XX:MaxPermSize=512m . Avez-vous également modifié ce paramètre ?
Si vous avez un exemple de document pdf non-confidentiel que vous pouvez me transmettre, je pourrais alors tenter de reproduire et analyser votre probleme.
Cordialement,

**Comment by oliviermarie** [comment]
Je viens de tenter d’augmenter la taille dans le paramètre -XX:MaxPermSize=1546m. Idem

Je vous joins ci-dessous un des fichier qui pose problème

[Plan_SIG-Arconnay.pdf](https://github.com/linagora/linshare/files/1646272/Plan_SIG-Arconnay.pdf)

**Comment by fmartin-linagora** [comment]
Bonjour,

Je viens de tenter de déposer votre pdf sur notre dernière version de LinShare et j'ai la même erreur que vous.
Nous allons tenter d'investiguer ce problème dès que possilbe. En attendant, je peux vous proposer un contournement. Vous pouvez désactiver l'aperçu des pdfs sur votre serveur en ajoutant la clé de configuration suivante :  `linshare.documents.thumbnail.pdf.enable=true`, en dernier recours vous pouvez désactiver totallement les aperçus : `linshare.documents.thumbnail.enable=true`.

Cordialement,

**Comment by oliviermarie** [comment]
Merci pour ce retour.

Concernant la configuration que je dois modifier. Me confirmez-vous que je dois la rajouter dans le fichier /etc/linshare/linshare.properties ?

Merci grandement pour votre aide.

**Comment by fmartin-linagora** [comment]
Oui, il s'agit bien de ce fichier.
