### ISSUE TITLE
Admin Interface : Can't open "Contacts Lists"

### ISSUE THREAD

**Issue by georgej77** [linagora/linshare#191]
Hi Team,

When I try to open "Contacts Lists", getting the below error from Admin console. Kindly help.

Error is "COMMON.NOTIFICATION.ERROR.20005"
Product Version = 4.1.2
Core Version = 4.1.2

![image](https://user-images.githubusercontent.com/41739394/141730524-da3da632-fba4-4c04-9699-2144a73c903e.png)

This is for deleting one of the contact list of end user. The user got the below error when tried to modify the contact list.
 
User console error is " 20005: Bad data format : null, exception: java.lang.NullPointerException"
![image](https://user-images.githubusercontent.com/41739394/141731207-5d7f27e2-85b6-403e-a300-9e71cf717a5d.png)

Thanks,
George.

**Comment by fmartin-linagora** [comment]
Hi, 

Can you try to update and use the latest 4.1.x version available because I think it is a problem that we already solved ? 
You can download LinShare here : http://download.linshare.org/versions/

Regards,

**Comment by georgej77** [comment]
Thanks.

**Comment by fmartin-linagora** [comment]
Hi,
Can we close this issue ?

**Comment by georgej77** [comment]
Yes please.
