### ISSUE TITLE
migration to 4.2.3 and guests quota

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#192]
Hello,
I did a migration test from  2.3.4 to 4.2.3 (2.3.4 -> 4.0 ->4.1 ->4.2).
It's ok for most af functionnalities but I have something bad with guests quota user space.
It seems that files are not purged correctly.
I used a backup of last June, documents expires after 10 days but I have still 10GB of space used by guests for there user space.
It should be purged for a while.
Can it be linked with the fact I use an old backup, not enough "fresh".
How can I check it?
Thanks,

**Comment by fmartin-linagora** [comment]
Hi,
I suppose you are talking about the value for the space used by the guest domain in the admin interface ?
Regards,

**Comment by matdemb** [comment]
Hi,
yes,that's it.
Little precision, it was in maintenance mode. I disabled it when I wrote the ticket and now the space is full free, so the purge has been done.
The maintenance mode disable the purge?
Regards,

**Comment by matdemb** [comment]
Hi,
yes it is.
Now all file have been purged...
I don't understand when it really delete files from disk.
Dispite I configure 10 days, it seems it is not that. Maybe because of the migration?
When I did tests file disappear in guest space after the configured time.
Maybe it doesn't delete immediatly?
I will do a test to be sure.
Regards,

**Comment by fmartin-linagora** [comment]
Hi,
Guests are not deleted immediately,  they are marked to be deleted and these accounts are purged 7 days later (by default).
For file deletion, it is also done asynchronously,. Removed documents are added to a garbage collector, and then every night a batch is running to remove this documents if there is no more references. Indeed, LinShare stores only once a file even if it is referenced by multiple documents or users.
Regards,
