### ISSUE TITLE
Upgrade Linshare 2.6.1 --> version xxx ?

### ISSUE THREAD

**Issue by Laurent689** [linagora/linshare#193]
Bonjour,

Nous utilisons Linshare (Product version 2.6.1, Core version 1.12.8) et nous souhaitons l'upgrader en dernière version.
Pouvez-vous svp nous dire quelle est la dernière version de Linshare que vous recommandez ?
Quelle version PostgreSQL supporte-elle ?
Pouvons-nous facilement réaliser un InPlace Upgrade ?

Cordialement.
LP

**Comment by fmartin-linagora** [comment]
Bonjour,

La dernière version disponible est la version 4.2. Vous avez donc 2 sauts majeurs à effectuer.
Vous trouverez ici l'ensemble des [guides de migrations](https://github.com/linagora/linshare/tree/master/documentation/FR/upgrade) pour chaque version. Depuis la version 2.0, LinShare ne supporte plus MySql, on ne supporte que PostgreSql.

Vous devez passez par les étapes intermédiaires.

Cdt,
Fred.

**Comment by Laurent689** [comment]
Bonjour,

Nous allons installer la dernière version stable Linshare sur un nouveau serveur.
S'agit-il de la version 4.2.3 ?  Peut on l'installer  sur RedHat8 ?

Cdt,
LP

**Comment by fmartin-linagora** [comment]
Bonjour,

Oui en effet la version 4.2.3 est la dernière version sortie. Nous avons jamais essayé de l'installer sur RedHat8 mais si vous arrivez à satisfaire touts les pré-requis [ci-joint](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/requirements.md), vous devriez pouvoir faire fonctionner LinShare sans problème.

Cdt,
Fred
