### ISSUE TITLE
Notification de nouveaux documents dans le groupe de travail de travail

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#194]
Bonjour,

Quand un document est ajouté au groupe de travail, aucune notification n'est envoyé aux membres. Y a-t-il une possibilité de le faire ?

**Comment by fmartin-linagora** [comment]
Bonjour,
Actuellement il n'y a en effet aucune notification. Il s'agit bien entendu d'une fonctionnalité que nous aimerions introduire a moyen terme. Malheureusement je n'ai pas de visibilité sur le développement de celle-ci.

PS: Pourriez-vous rédiger vos futures demandes d'information et d’assistance en anglais ? En effet, cela permettrait à l’ensemble de la communauté de vous lire et de profiter des réponses.  ;)  

Merci d'avance.

Cordialement,

**Comment by EPTBSGL** [comment]
Merci pour votre réponse claire et rapide. Je note que je devrai rédiger mes futures demandes dans la langue de Shakespeare.
Je clos le ticket.
Cordialement
