### ISSUE TITLE
LDAP multiple OU request

### ISSUE THREAD

**Issue by Nniicolas** [linagora/linshare#195]
Hi all,
I've 2 OU with user in my AD.
Actually, the OU is mentioned in the BaseDN field and i can attribute a differente domain for each user.
I search the solution to have 2 OU in one query ldap.
Any idea?

**Comment by fmartin-linagora** [comment]
Hi,
I can only suggest to create two domains, one per OU.
It will be very simple.
Regards,

**Comment by Nniicolas** [comment]
ok, i'll try it
thank you for your answer
