### ISSUE TITLE
Linshare version 4 compatible RedHat 8  ?

### ISSUE THREAD

**Issue by Laurent689** [linagora/linshare#196]
Bonjour,

Nous allons installer la dernière version stable Linshare sur un nouveau serveur.
S'agit-il de la version 4.2.3 ? Peut on l'installer sur RedHat8 ?

Cdt,
LP

**Comment by fmartin-linagora** [comment]
Bonjour,

Oui en effet la version 4.2.3 est la dernière version sortie. Nous avons jamais essayé de l'installer sur RedHat8 mais si vous arrivez à satisfaire touts les pré-requis [ci-joint](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/requirements.md), vous devriez pouvoir faire fonctionner LinShare sans problème.
Cdt,
Fred
