### ISSUE TITLE
Vulnerability Apache Log4j

### ISSUE THREAD

**Issue by kevin-m87** [linagora/linshare#197]
Hello,

Do you have some instructions for update Apache Log4j about Linshare ?

Thanks.

**Comment by aduprat** [comment]
Hi,

Thank you for your report.

I can confirm that LinShare is not subject to this security issue.
We are using Log4j 1.x (slf4j-log4j12) which doesn't offer JNDI look-up mechanism at the message level,
hence we are safe !!!

Here is the official communication from Slf4j regarding log4j vulnerability:
http://slf4j.org/log4shell.html

Antoine
