### ISSUE TITLE
Problème d'accès à l'interface utilisateur : linshare 4.2.3

### ISSUE THREAD

**Issue by Laurent689** [linagora/linshare#198]
Bonjour,

J'ai déployé linshare 4.2.3 suivant la procédure.

J'ai bien accès à l'interface d'administration mais je n'ai pas accès à l'interface utilisateur:

J'ai le message : "Welcome to Linshare Core. Linshare is up and running! Please install linshare-ui-admin component to configure Linshare."

Dans les fichiers des vhosts  : linshare-ui-user.conf et linshare-ui-admin.conf la balise <Location /linshare> est la même, est-ce normal ? 

    ProxyPass http://127.0.0.1:8080/linshare
    ProxyPassReverse http://127.0.0.1:8080/linshare
    ProxyPassReverseCookiePath /linshare /

    # Workaround to remove httpOnly flag (could also be done with Tomcat)
    Header edit Set-Cookie "(JSESSIONID=.*); Path.*" "$1; Path=/"
    # For https, you should add Secure flag.
    # Header edit Set-Cookie "(JSESSIONID=.*); Path.*" "$1; Path=/; Secure"

    #This header is added to avoid the  JSON cache issue on IE.
    Header set Cache-Control "max-age=0,no-cache,no-store"

 Comment fait-on pour avoir accès à l'interface utilisateur et aussi à l'interface d'administration ?

Cdt,
LP

**Comment by matdemb** [comment]
Bonjour,
les deux interfaces ont bien été mises sur des servername différents? Perso j'ai mis aussi sur des ports différents.
L'interface utilisateur a bien été activée côté apache?
Que disent les logs d'apache et de tomcat?
Cdlt,

**Comment by Laurent689** [comment]
Bjr,

Oui, les servername sont différents : admin sur linshare-admin.local et user sur linshare-user.local

Que faut il faire de particulier pour activer l'interface utilisateur côté apache ?

Pour le moment j'ai:

 Si j'accède depuis l'URL : http://nomdemonserveur/linshare

"Welcome to LinShare Core. LinShare is up and running ! please Install linshare-ui-admin component to configure LinShare."

 Si j'accède depuis l'URL : http://linshare-user.local/linshare

"Ce site est inaccessible Impossible de trouver l'adresse IP du serveur de linshare-user.local."


je ne vois rien de particulier dans les logs

cdt
LP

**Comment by Laurent689** [comment]
Problème réglé, lié à une mauvaise résolution dns des servername des vhosts.

**Comment by fmartin-linagora** [comment]
:+1:
