### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by nigel-v-thomas** [linagora/linshare#2]
Hello,

On Chrome in OSX, while navigating to the website, I do not progress past the login screen. These are the steps to reproduce:
1) Navigate to web app, get redirected to http://<address>/index.html#/dashboard with login prompt
2) Enter credentials user1@linshare.org and password1 then connection
3) There is a loading red line on the top, but the login box remains:
![screen shot 2016-11-14 at 16 05 03](https://cloud.githubusercontent.com/assets/1025109/20271900/36abe44a-aa84-11e6-8a53-9d21e990a4d2.png)

If I manually reload the page I see a blank page:
![screen shot 2016-11-14 at 16 06 30](https://cloud.githubusercontent.com/assets/1025109/20271978/6ade4af0-aa84-11e6-9dd5-aac0671e1bff.png)

Checked tomcat logs, I can see user John Doe has authenticated:
![screen shot 2016-11-14 at 16 11 58](https://cloud.githubusercontent.com/assets/1025109/20272217/2cec09ac-aa85-11e6-82ca-d3aeeee82905.png)

Not sure why the app isn't loading. Can you help?

Many thanks,
Nigel

**Comment by fmartin-linagora** [comment]
Hello,
You can not login into admin interface with a user account. You should login root@localhost.localdomain account.
Sorry for the delay.
Fred.

**Comment by nigel-v-thomas** [comment]
Hello Fred,
Sorry wasn't obvious that was the admin page, I have tried accessing  http://http://192.168.xx.xxx//linshare this time I get a basic http password challenge, on entering credentials I get a HTTP Status 403 - Access is denied.
Logs suggest successful authentication:
![screen shot 2016-11-16 at 23 35 51](https://cloud.githubusercontent.com/assets/1025109/20370235/88d2e89a-ac55-11e6-8117-fe326e11f244.png)
Any ideas what is wrong?
Nigel

**Comment by nigel-v-thomas** [comment]
Thanks Fred, I am using the vagrant copy https://github.com/linagora/linshare/blob/master/virtual-machines/README.md, and unable to login into this.
I can try Docker as well.
Nigel

**Comment by fmartin-linagora** [comment]
Ok, now I understand. Have you add these lines into /etc/hosts  ?
127.0.0.1    linshare-user.local
127.0.0.1    linshare-admin.local

Then you must access to linshare user portail throught http://linshare-user.local and linshare admin portail throught http://linshare-admin.local.

If you are using the 192.168.x.x adress, you can only access to admin portal.

**Comment by nigel-v-thomas** [comment]
Thanks Fred, the /etc/hosts entries worked fine.
192.168.x.x linshare-user.local
192.168.x.x linshare-admin.local

I guess these notes may prove useful for other vagrant installs in the future.
Nigel

**Comment by tamalindia** [comment]
Hi All,

I have installed Linshare to my Centos7 system and user interface is working fine. But in the admin interface it showing blank.

**Comment by Hrsolim** [comment]
> 

Dear Nigel, how do we connect to linshare from outside in the LAN, since it is only opening Admin section not User section?
