### ISSUE TITLE
Option accusé de partage non prise en compte

### ISSUE THREAD

**Issue by oliviermarie** [linagora/linshare#20]
Bonjour,

Je suis en version Linshare 1.12.3 et mes utilisateurs m'alertent sur le fait que bien qu'ils décochent la case "Recevoir un accusé contenant les détails du partage", ils reçoivent quand même un mail lors du téléchargement du fichier.

Est-ce un bug connu ou bien y a t-il un élément de paramétrage dans la partie administration à régler pour pallier à ce problème ?

Vous remerciant par avance

Olivier MARIE

**Comment by fmartin-linagora** [comment]
Bonjour,

La fonctionnalité "Recevoir un accusé contenant les détails du partage" permet à l'emetteur de recevoir un mail de synthèse du partage qu'il vient de réaliser, contenant les documents et les destinaires du partage. 

La notification de de téléchargement par le peut

**Comment by oliviermarie** [comment]
Merci pour cette précision, je n'ai donc pas bien interprété le sens de cette option.

Du coup je précise ma demande, mes collèges ne souhaitent plus recevoir de mail lorsque les personnes avec qui elles ont partagés du contenu téléchargent un document.

Elles estiment que cela polluent leurs boîte mail. Je n'ai pas trouvé un tel paramétrage dans la partie d'administration.

Est-ce possible de désactiver le mail de notification lors d'un téléchargement d'un document ?

Merci

**Comment by fmartin-linagora** [comment]
Oui biensur, vous pouvez désactiver n'importe quel mail dans le menu "Courries / Activation des notifications".

Par ailleurs, je ne peux que vous conseiller de mettre à jour votre version car nous avons corrigé un bug critique en version 1.12.6 concernant les taches planifiées en charge de la suppression des partages expirés par exemple. La mise à jour est très simple, vous trouverez de la documentation à cette adresse : https://github.com/linagora/linshare/blob/master/documentation/FR/upgrade/linshare-upgrade.md.
Cordialement,

**Comment by oliviermarie** [comment]
Cela marche comme je veux.

J'étais passé à côté de ce menu de configuration des alertes mails.

Encore merci
