### ISSUE TITLE
ajouter un logo dans l'interface utilisateur

### ISSUE THREAD

**Issue by Laurent689** [linagora/linshare#201]
Bonjour,

Nous avons installé la dernière version de linshare.

Nous souhaitons ajouter le logo de notre entreprise à côté du logo Linshare dans l'interface utilisateur.

J'ai modifié le fichier /var/www/linshare-ui-user/config/config.js  (voir ci-dessous)

 // To override the application logo set the url of the image corresponding
 // to the sizes (small 155x29 and big 500x192)
    applicationLogo: {
       small: 'app/images/common/linshare-logo-white.png','app/images/common/ellisphere.png'
       large: 'app/images/ls-logo-big.png'
    },
    // To override the background image of the login screen set the url of the image
    loginBackground: 'app/images/bg-linshare-desktop.png'

Et j'ai ajouté le logo ici :     /var/www/linshare-ui-user/app/images/common

-rw-r--r-- 1 apache apache  765 Oct 28 17:06 community.png
-rw-r--r-- 1 apache apache 4369 Sep  6  2016 ellisphere.png
-rw-r--r-- 1 apache apache 2100 Oct 28 17:06 linshare-logo-white.png

puis relancé apache

Mais le logo ne s'affiche pas ?

Cdt
LP

**Comment by fmartin-linagora** [comment]
Hi,
can you explain to us your problem in english please, not all of us speak french ;)

Regards,

**Comment by Laurent689** [comment]
Hello,

In English in the text .. 

We installed the latest version of linshare.

We want to add our company logo next to the Linshare logo in the user interface.

I modified the file : /var/www/linshare-ui-user/config/config.js

// To override the application logo set the url of the image corresponding
// to the sizes (small 155x29 and big 500x192)
applicationLogo: {
small: 'app/images/common/linshare-logo-white.png','app/images/common/ellisphere.png'
large: 'app/images/ls-logo-big.png'
},
// To override the background image of the login screen set the url of the image
loginBackground: 'app/images/bg-linshare-desktop.png'

And I added the logo "Ellisphere.png" here : /var/www/linshare-ui-user/app/images/common

-rw-r--r-- 1 apache apache 765 Oct 28 17:06 community.png
-rw-r--r-- 1 apache apache 4369 Sep 6 2016 ellisphere.png
-rw-r--r-- 1 apache apache 2100 Oct 28 17:06 linshare-logo-white.png

And I restarted the apache service

However the logo is not displayed?

We want to display our company logo into the mails wich are sent by linshare too ? 

Regards
LP

**Comment by RockyMeadow** [comment]
Hello @Laurent689,

What you described seems to be a known issue. The core reason is how we package the user app, default images are bundled a long with the entire app, losing the ability to customize. It has been fixed recently in version 5.00-beta. What version of LinShare are you using?

**Comment by Laurent689** [comment]
Thank you for your answer,

We are using the 4.2.3 version of linshare, isnt' it the lasteste version ? 

Version du produit : 4.2.3
Version du core : 4.2.3

**Comment by RockyMeadow** [comment]
Version 5.00 is the latest version and on active development. For your issue, the fix will be included in the next minor release, which is v4.2.4.

> We want to display our company logo into the mails wich are sent by linshare too ?

You can refer to this [document](https://github.com/linagora/linshare/blob/master/documentation/EN/administration/how-to-use-mail-attachment.md#2-how-to-use-mail-attachment) to change the logo displayed in the mails.

I hope it helps.

**Comment by Laurent689** [comment]
ok thanks ! 

For the mail yes I succed to add our company logo in the mails in following the document

**Comment by fmartin-linagora** [comment]
Hi,

LinShare 4.2.4 is released and available here : http://download.linshare.org/versions/4.2.4/

Fred
