### ISSUE TITLE
[4.2.3] - share link

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#204]
Hi,
This is more question not issue:
Is it possible to generate shared link to file without sending an email ?
Thanks

**Comment by fmartin-linagora** [comment]
Hi,
Not it is not possible, LinShare is creating one link per recipient.
There is no common link that you can get and then share manually.
Sorry,
Fred.

**Comment by lacrimal** [comment]
Thank you for quick response, from other hand - great job!
