### ISSUE TITLE
Option : "Guest creation permission"  for all users of a domaine ? 

### ISSUE THREAD

**Issue by Laurent689** [linagora/linshare#205]
Hi,

We have the 4.2.3 version of Linshare.

Can we activated this option : "Guest creation permission"  for all users of a domaine ?   how ?

By default this option is présent but is not checked for a user

Regards
LP

**Comment by fmartin-linagora** [comment]
Hi,

When the functionality "Guest creation permission" is enabled, it means it will be enabled for all NEW users.
Unfortunately, for existing users, you need to edit their profiles and enable the checkbox.

Does it answer to your question ? 

Regards,
Fred

**Comment by Laurent689** [comment]
yes this is what I wanted to know thank you.
