### ISSUE TITLE
Guest account, password ?

### ISSUE THREAD

**Issue by Laurent689** [linagora/linshare#206]
Hello,

We can create guest accounts, an email is sent in their email asking them to activate their account and they are directed to the user portal. At no time they receive their IDs, their passwords   ?  

Can you explain to me how a guest receives their login credentials to log into Linshare  ?  (version 4.2.3)

Hello xxxxx,

xxxxxx has created a LinShare guest account that allows you to share files securely.
To log in, you must complete your registration by creating your password using the link below.
Activate my account

Regards,
LP

**Comment by fmartin-linagora** [comment]
Hi,

You must click on the link below, an dedicated page in LinShare will ask you to provide a password in order to validate and activate the guest account.

Regards,

**Comment by Laurent689** [comment]
Hi,
Thanks for your answer.
Unfortunaly, when i click on the link, i dont have a dedicated page asking me to provide a password. I have the classic page of connection to linshare

![Capture](https://user-images.githubusercontent.com/94609248/149906623-569ce384-fcd9-47ab-8edb-5e9cbf4c0639.JPG)

**Comment by fmartin-linagora** [comment]
Hi,
In the mail, you should have a link like: https://server/#!/external/reset/adfdb869-a71e-476c-b15f-4ad08090cec0

It will look like:

![image](https://user-images.githubusercontent.com/6229766/149907836-221f3942-2e8a-4f80-ba96-4dd98ca76b9e.png)

**Comment by Laurent689** [comment]
yes I have this link https://server/#!/login/#!/external/reset/1a54e0f9-37a7-4641-a1ed-d21d3d9ab96f but after 5 seconds it is redirected to https://server/#!/login

**Comment by Laurent689** [comment]
i have thislink   https://server/#!/login/#!/external/reset/1a54e0f9-37a7-4641-a1ed-d21d3d9ab96f

**Comment by fmartin-linagora** [comment]
You may have a bad configuration. go to ui-admin, in the functionalities, you need to setup a proper URL for notification. Please use just " https://server"

**Comment by Laurent689** [comment]
Ok i find a bad URL in the admin : Notification URL , now it's work

Regards
LP

**Comment by fmartin-linagora** [comment]
perfect !
