### ISSUE TITLE
Minor UI bug: year mentioned in the footer should be updated

### ISSUE THREAD

**Issue by yeganathan18** [linagora/linshare#208]
It's a minor UI bug on the website of linshare, the years mentioned in the footer should be replaced with **2009-2022**. I have also attached a screenshot of the issue kindly refer it.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/63534555/151994460-b0521449-d60a-4cbb-a818-0a2a910da918.png">

**Comment by yeganathan18** [comment]
Perhaps, this issue can be labeled as **good-first** issues.

**Comment by fmartin-linagora** [comment]
Hi,

Indeed we forgot to update it. tks. we will do it asap.

**Comment by yeganathan18** [comment]
@fmartin-linagora sure, no issues!

**Comment by fmartin-linagora** [comment]
it was fixed it latest releases.
