### ISSUE TITLE
missing file on linshare-core-2.1.0-1.war

### ISSUE THREAD

**Issue by hjacas** [linagora/linshare#21]
On Centos 7 install document say:
"unzip -c linshare.war WEB-INF/classes/sql/postgresql/import-postgresql.sql | psql -U linshare -W -d linshare
Password for user linshare: {PASSWORD}"

And then file import-postgresql.sql is missing

**Comment by fmartin-linagora** [comment]
Hi,
The fle import-postgresql.sql is now in the archive file named linshare-core-sql-{VERSION}.tar.bz2.
We forget to update install documentation according to this modification. I'll update it asap.
Regards.
Fred.

**Comment by fmartin-linagora** [comment]
Fixed.
