### ISSUE TITLE
Remettre à zéro pass root@localhost.localdomain

### ISSUE THREAD

**Issue by si-pg** [linagora/linshare#210]
Bonjour,

Sur une installation qui tourne chez nous depuis 1 an nous ne retrouvons pas le pass de l'admin.
Avec PGadmin je peux modifier la table accounts mais impossible de recoder la password {bcrypt}
Quel est le moyen de pouvoir re-acceder à root@localhost.localdomain ?

Merci pour votre aide

**Comment by fmartin-linagora** [comment]
Bonjour,

Il suffit d'utiliser le mot de passe par défaut du script d'import initial:

`UPDATE account set password = '{bcrypt}$2a$10$LQSvbfb2ZsCrWzPp5lj2weSZCz2fWRDBOW4k3k0UxxtdFIEquzTA6' where id = 1`

Cdt,
