### ISSUE TITLE
LinshareADmin 5.0 cohabitant avec la version 4

### ISSUE THREAD

**Issue by xlyric** [linagora/linshare#211]
Bonjour Frédéric, 

Je n'ai pas trouvé comment faire tourner l'admin 5 et 4 en même temps.
y a t'il une procédure particulière au niveau du server web ? 

Cordialement
Cyril

**Comment by fmartin-linagora** [comment]
Bonjour,

Dans la documentation nous avons détaillé comment déployer les 2 applications, cf [ici](https://github.com/linagora/linshare/blob/master/documentation/FR/installation/linshare-install-debian.md#ui-admin).

Cordialement,
Fred.

**Comment by fmartin-linagora** [comment]
Bonjour,
Je suppose que ma réponse a résolu vos problèmes.
Je clos le ticket
