### ISSUE TITLE
Can't login to web.linshare.app

### ISSUE THREAD

**Issue by TotesRandomer** [linagora/linshare#212]
Can't log in to my LinShare account - I keep getting "INTERNAL SERVER ERROR" looping with "SSO authentication failed.

I'm on Chrome OS v98

**Comment by tanandy** [comment]
Hi, sorry for your inconvenience. We had SSO outage, we fixed it.

**Comment by TotesRandomer** [comment]
I know Andy!

Thank you for your reply. ;)

**Comment by Clem-** [comment]
Hi,
I am facing the same issue.

Here are some errors from the browser: 
```
[Error] Blocked autofocusing on a form control in a cross-origin subframe. (authorize, line 1451)
[Error] Blocked a frame with origin "https://auth.twake.app" from accessing a frame with origin "https://web.linshare.app". Protocols, domains, and ports must match.
[Error] Failed to load resource: Vous n’êtes pas autorisé à accéder à la ressource requise.
[Error] Failed to load resource: the server responded with a status of 404 () (crypto-js.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (enc-base64.min.js.map, line 0)
```

**Comment by tanandy** [comment]
Hi @Clem- , it is not the same root cause. I can connect on my side sso is answering.

I dont have the same behavior than you, can you give us more details your env details

OS, Browser, url you connect ...

Can you check in private browsing to confirm you have the same trouble ?

**Comment by Clem-** [comment]
Hi,
I tried private browsing but same trouble.
I also tried different OS and browser (macOS+safari, Windows 11 + Chrome) and the same issue occurred.

It seems that my linID was "converted" from an old Twake registration, maybe my linID is not fully compatible with SSO?

**Comment by Clem-** [comment]
It works with a fresh account in private browsing.

Here's a screenshot with my first account:
![image](https://user-images.githubusercontent.com/1936021/187941320-ca75588d-a5ac-4716-a96e-aa5b8cc8386a.png)

**Comment by tanandy** [comment]
sure, i will contact console team to investigate on it. It could be linked to migration indeed.

note: some of them are in holidays and come back next week

**Comment by tuanlc** [comment]
Hello @Clem- 

Would you mind giving me your email? 

I need to check what is wrong with your account. If you don't want to public your information, please send a direct message to tlcong@linagora.com mailbox.

**Comment by tuanlc** [comment]
Hi @Clem- 

I've checked your account. You are currently owning 2 companies that only subscribe to Twake app but none of them subscribe to LinShare application.

1. Are you sure you register and use LinShare app with your account before? I need to check if the issue from our side.
2. If you want to experience LinShare app while waiting for more investigation, you can do it easily by going to T-Board (Console) and subscribe to LinShare app. Bellow is the demo for how to do it:

   https://user-images.githubusercontent.com/7950991/188541733-62680d5c-79a1-4ea8-a783-08863d8da9f7.mp4

  After successfully subscribe to LinShare app, you are able to access to LinShare app

**Comment by Clem-** [comment]
Thank you very much for your investigation Tuan!

I indeed never subscribed to LinShare.
When I first launch LinShare, I was redirected to LinID. Since I know I had a LinID from Twake, I simply filled in my credentials.
It was not clear to me that I had to subscribed the way you show.

It would be really useful, IMO, to be redirected to the Console or maybe just print a message regarding this instead of the blank page seen on my screenshot.

I followed your instructions but I am still facing the issue. I only subscribed from one of my companies. I am waiting for your feedback to subscribe the other, if needed.

**Comment by tanandy** [comment]
Interesting, were you a twake user initially or a linshare user ? or you were already using both product separately

**Comment by Clem-** [comment]
I am a Twake user and I wanted to use LinShare for the first time recently.

 

Btw, the fact that I have two companies seems to go back to Twake official launch after the beta when my company was duplicated.

 

De : Andy Tan ***@***.***> 
Envoyé : mardi 6 septembre 2022 10:29
À : linagora/linshare ***@***.***>
Cc : Clément E. ***@***.***>; Mention ***@***.***>
Objet : Re: [linagora/linshare] Can't login to web.linshare.app (Issue #212)

 

Interesting, were you a twake user initially or a linshare user ? or you were already using both product separately

**Comment by tanandy** [comment]
so yes indeed you need to subscribe and i agree that we should put a message to tell user to subscribe to it and be more user friendly

**Comment by Clem-** [comment]
The thing is, as I mentionned, I subscribed from the console but the issue is still present.

 

It might be due to the fact that I have two companies?

 

De : Andy Tan ***@***.***> 
Envoyé : mardi 6 septembre 2022 10:49
À : linagora/linshare ***@***.***>
Cc : Clément E. ***@***.***>; Mention ***@***.***>
Objet : Re: [linagora/linshare] Can't login to web.linshare.app (Issue #212)

 

so yes indeed you need to subscribe and i agree that we should put a message to tell user to subscribe to it and be more user friendly

**Comment by tuanlc** [comment]
@Clem- I've checked and see you've subscribed to LinShare app correctly.

Now, Can you try to login to LinShare app in a private browser with you account?

**Comment by Clem-** [comment]
This is what I've done and described at [the end of my post](https://github.com/linagora/linshare/issues/212#issuecomment-1237755874). It still spins forever.

**Comment by tuanlc** [comment]
@Clem- Yes, I read your previous post. However, the most important part of my question is can you try it in a `private` browser (with fresh cache)?

If you already did that, please tell me.

**Comment by Clem-** [comment]
I've done it in private browsing, yes :)

**Comment by tuanlc** [comment]
Hi @Clem- 

Can you try again?

**Comment by Clem-** [comment]
Still experiencing the issue.

**Comment by Clem-** [comment]
Hi guys, any updates on this issue?
I still can't log in to LinShare with my LinID.
