### ISSUE TITLE
[5.0.0] legacy admin interface - change password lost translation

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#215]
Trying to change password with legacy interface getting below instead of message:
![obraz](https://user-images.githubusercontent.com/22749391/157439361-22a1bba9-949a-473b-8812-efec74b1e7e1.png)

linshare log clearly said:
`Exception was caught : code=RESET_ACCOUNT_PASSWORD_INVALID_PASSWORD,  [Password must be 12 or more characters in length., Password must contain 1 or more uppercase characters., Password must contain 1 or more digit characters., Password must contain 1 or more special characters.]`

**Comment by RockyMeadow** [comment]
Hi @lacrimal ,

The fix has been included in the newly released version 4.2.6 and legacy part of 5.0.3
