### ISSUE TITLE
change email atachement

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#216]
Hi,

Is linsharecli still only option to change attachment in linshare email ?

**Comment by fmartin-linagora** [comment]
Hi,

Yes, for now it is. in the futur we will provide a configuration screen in the new admin interface but it is not planned on short term.

Regards,

**Comment by lacrimal** [comment]
Ok,

I'm trying to use CLI now. with super administrator data and getting empty response for every query
I'm not sure which http address I should use - should it be the one pointing to linshare-ui-user ?

`debug>>>----------- config -------------------
Configuration of linshare-admin-cli :

        Section SERVER
         - host : https://linshare.local/linshare
         - api_version : 2.2
         - user : root@localhost.localdomain
         - password : xxxxxxxx
         - auth_type : plain
         - base_url : None
         - verify : True
         - nocache : False
         - verbose : None
         - debug : 3

debug----------- processing --------------<<<<

Available sections:
===================`

**Comment by fmartin-linagora** [comment]
For host you just need : host : https://linshare.local

You can run `linshareadmcli domains list` to check if you can retrieve the default root domain. You will know if your config is good.

**Comment by lacrimal** [comment]
Got it - it is working
