### ISSUE TITLE
Unable to create guest account (2205: you are not authorized to create an entry)

### ISSUE THREAD

**Issue by Harckange** [linagora/linshare#220]
Hello,

I'm unable to create a guest account in Linshare 4.2.1

![image](https://user-images.githubusercontent.com/101645660/158384952-47bddb28-dd67-4d8b-a697-f73750bb307e.png)

From the admin side, the Guest functionality is enabled : 

![image](https://user-images.githubusercontent.com/101645660/158385179-46c43105-4d6c-4bc1-8f2c-01eb0c5e3252.png)

And i have the right to create guest account : 

![image](https://user-images.githubusercontent.com/101645660/158385410-6741880b-ea5b-49c7-bd8c-c16af24f0c4a.png)

I tried to delete the user from "Manage users", then connect again (Linshare is linked to Active Directory). When i go back to "Manage users", the "Guest creation permission" box is already checked but the error is still here.

This issue is present for all users.

Any idea ?

Thank you !

**Comment by lacrimal** [comment]
Don't know what is the path driving you to first screenshot so cant advice you more.
But i believe that:
You can add account to Workgroup when you are administrator of it - if this is the case - check if you are administrator of particular Worgroup, when not - ask someone who is to change permission.
You can add account when you are administrator in domain - if this is the case then switch Simple to Admin (visible on your third screen).

Anyway keep in mind that Workroup Admin is not same that system admin.

**Comment by tanandy** [comment]
@fmartin-linagora

**Comment by Harckange** [comment]
> Don't know what is the path driving you to first screenshot so cant advice you more. But i believe that: You can add account to Workgroup when you are administrator of it - if this is the case - check if you are administrator of particular Worgroup, when not - ask someone who is to change permission. You can add account when you are administrator in domain - if this is the case then switch Simple to Admin (visible on your third screen).
> 
> Anyway keep in mind that Workroup Admin is not same that system admin.

Hello lacrimal,

The path is : Contacts --> Guests, then i click on the " + " sign, i fill in the firstname, lastname and email then i click on Create :

![linshare_guest](https://user-images.githubusercontent.com/101645660/159429734-58a94581-d210-4a6a-b6fb-a79f8ad8f3bd.png)

I gave the "Administrator" Role to the user, but i get the same error when i try to create a guest account.

**Comment by lacrimal** [comment]
Ok, now understand - it is contact list.
You can safely remove administration right then - it has nothing to common with this.
However it is strange, because if you do not have 'Guest creation permission' set in administration portal - option is not visible at all.
Currently have 5.0.0 version so no chance to check is it bug or not.
You need to wait for response from guys from linagora.

**Comment by fmartin-linagora** [comment]
Hi,
You must also create a guest domain in the domain tree. otherwise you can not create guests even if the functionality is enabled.
Fred.

**Comment by Harckange** [comment]
> Hi, You must also create a guest domain in the domain tree. otherwise you can not create guests even if the functionality is enabled. Fred.

That worked perfectly, thank you !
