### ISSUE TITLE
upload request version 5.0.2

### ISSUE THREAD

**Issue by EPTBSGL** [linagora/linshare#223]
Hello,
the area indicated "message body" actually contains the subject. 
On the other hand, in the sent notification appears the subject instead of the number of days (see attached images) 
<a href="https://imgbb.com/"><img src="https://i.ibb.co/YNchZ5K/invitation-de-d-p-t.png" alt="invitation-de-d-p-t" border="0"></a>
<a href="https://ibb.co/MGc7DMw"><img src="https://i.ibb.co/P9cgZwX/Pb-Invitation-de-d-p-t.png" alt="Pb-Invitation-de-d-p-t" border="0"></a>
Thank you for your answers

**Comment by tanandy** [comment]
Hi, are you using LinShare SaaS or self installed ?

**Comment by EPTBSGL** [comment]
I installed this version myself on a Debian 11 server

**Comment by Yoni19** [comment]
Hi, thanks for your feedback, the problem will be fixed in the next version.
