### ISSUE TITLE
Sécurité : Envoi du mot de passe séparé 

### ISSUE THREAD

**Issue by nlonge** [linagora/linshare#224]
Bonjour, 

Lors d'un partage d'un fichier, il est possible de sécuriser le partage via mot de passe. Ainsi le destinataire reçoit un mail avec le lien du partage + un mot de passe pour y accéder. 
Je n'ai pas trouvé de solution et j'aurai aimé savoir si c'est quelque chose de faisable : 
- je voudrais que le lien du partage ne soit pas dans le même mail que le mot de passe 
- Par exemple en envoyant un premier mail avec le lien et un second avec le mot de passe sécurisé 

Merci d'avance

**Comment by fmartin-linagora** [comment]
Bonjour,
L'utilisation de mot de passe pour les partages anonymes n'est utile que pour se protéger de quelqu'un qui surveillerait les journaux applicatif du serveur web. La personne aurait donc facilement accès l'URL mais ne pourrait télécharger le document. Ce fonctionnement reste très simple, il n'y pas de second mail à retrouver pour un partage "oneshot". Dans le cas d'une compromission de la boite mail de l'utilisateur, l'envoi en deux mails n’empêcherait pas l'accès au mot de passe.

Dans le cas d'une sécurisation plus forte, je vous recommande de passer par les comptes invités. Il est possible de créer un compte invité à la volé depuis le formulaire d'ajout de destinataire lors d'un partage. L'invité devra alors s’enrôler et définir un mot de passe via un premier mail. Le second mail contiendra le lien vers le partage. Aucun mot de passe ne transitera par mail.

Cordialement,
