### ISSUE TITLE
upload request version 4.2.6

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#228]
Hi,
I just update from 4.2.3 to 4.2.6 and for the upload request, the password is not send in the invitation mail as it was:
![image](https://user-images.githubusercontent.com/33221710/164240317-26994010-c224-474c-801c-5f4bd13fda8d.png)

Annoying when the interface ask it :-).

Mat

**Comment by marwanJebahi** [comment]
Hello,
Thank you for your feedback.
Can you, please, give us more detail about the test scenario to get this kind of issue. Because i couldn't reproduce the bug.
Regards

**Comment by matdemb** [comment]
Hello,
I did 3 more tests this morning, the password appear this times...
Strange...
It was a simply indiviual upload, with an expiration date modified, as I did this time too.
We can close the case, probably a temporary bug...
Regards,
