### ISSUE TITLE
[5.0.0] locked Superadministrator accout

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#229]
It is only account in my test instance, now what is proper way to unlock it ?

![obraz](https://user-images.githubusercontent.com/22749391/164421446-7c11b07a-6487-461c-a3a7-0586ddb0de29.png)

**Comment by fmartin-linagora** [comment]
Hi,
You can wait or reset the failure counter for the root account: `update account set authentication_failure_count = 0 where id =1;`
Fred

**Comment by lacrimal** [comment]
Working
