### ISSUE TITLE
how to remove Russian and Vietnamese languages from the user interface ?

### ISSUE THREAD

**Issue by laurent889** [linagora/linshare#230]
Hi,

We have the 4.2.3 version of Linshare, could you tell us how to remove Russian and Vietnamese languages from the user interface ?

We want only the language choices to appear: English and French

Regards
LP

**Comment by lacrimal** [comment]
you can disable it editing config/config.js in your ui-user www folder:
example below leaves English only:
```
    // Manage language handle by the application, see documentation.
    languages: {
      en: {
        key: 'us',
        fullKey: 'en-US',
        country: 'English'
      }
    },
    extLink: {
      enable: false,
      newTab: true,
      icon: 'zmdi zmdi-home',
      href: 'https://fileshare-t.upc.pl',
      name: {
        'en-US': 'Name'
      }
    },
```

**Comment by RockyMeadow** [comment]
Hi @laurent889, it is pretty much what @lacrimal said. In `config/config.js`, removing languages you don't want to display in `languages` property. For your case:

``` javascript
      languages: {
        fr: {
          key: 'fr',
          fullKey: 'fr-FR',
          country: 'Français',
        },
        en: {
          key: 'us',
          fullKey: 'en-US',
          country: 'English'
        }
      },
```
