### ISSUE TITLE
tmpdir configuration 

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#231]
Hi,
linshare.properties as well as github help says that location of temporary folder can be set using:
```
# If you want to change the location of tmp directory
# JAVA_OPTS="${JAVA_OPTS} -Djava.io.tmpdir=/tmp/"
```
Installation instructions on:
https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-centos.md#tomcat
says this can be set using /etc/sysconfig/tomcat

This will not take effect with at least with tomcat 9+, -Djava.io.tmpdir will be still overridden.

bellow should be used instead:
```
CATALINA_TMPDIR='/path/to/tmp/'
```

Tomcat recommended way is to use/create tomcat bin/setenv.sh file.

Also - is there any circumstance to use JAVA_OPTS instead CATALINA_OPTS for any tomcat specific settings ?

**Comment by lacrimal** [comment]
> The information is well in the Debian version.
> I will not modify the CentOS installation guide, as we are not supporting this OS anymore (marking it has deprecated).

So only supported platform will be Debian ?

**Comment by fmartin-linagora** [comment]
Officially only Debian version will be supported, but of course LinShare should work on other Linux Distribution. So it just mean that we won't provide/update documentation for CentOS.
