### ISSUE TITLE
Blank Admin Interface Without Menus

### ISSUE THREAD

**Issue by eokpara** [linagora/linshare#233]
I just newly installed Linshare 5.0.0 on Debian 10 and cannot access the admin interface. 

Attached is the "/var/log/tomcat9/catalina.out" log file
[catalinaOut.txt](https://github.com/linagora/linshare/files/8748053/catalinaOut.txt)

Attached is a screenshot of the interface. 
<img width="1428" alt="Screen Shot 2022-05-21 at 12 46 02 AM" src="https://user-images.githubusercontent.com/105962643/169637669-8b82874f-1178-4da7-bee1-9072cc912404.png">

I will appreciate any help, PLEASE!

Thank you.

**Comment by fmartin-linagora** [comment]
Hi,
You did not grant tomcat access to the storage directory:

```
[2022-05-21 12:20:18] [info] Caused by: java.nio.file.AccessDeniedException: /var/lib/linshare/filesystemstorage/e0531829-8a75-49f8-bb30-4539574d66c7
```

The following command should fix it: 
`chown tomcat:tomcat -R /var/lib/linshare/`

Regards

**Comment by eokpara** [comment]
Tomcat already owns and has access to the directory:

$ ls -l /var/lib/linshare/
total 8
drwxr-xr-x 2 tomcat tomcat 4096 May 21 11:58 filesystemstorage
drwxr-xr-x 2 tomcat tomcat 4096 May 21 11:58 tmp

**Comment by fmartin-linagora** [comment]
Can you run the following commands ?

```
ls -l /var/lib/linshare/filesystemstorage
getent passwd |grep tomcat
getent group |grep tomcat
```

**Comment by fmartin-linagora** [comment]
have you find your issue ?

**Comment by fmartin-linagora** [comment]
I hope you found your issue.
If you still struggling,  you can use our [docker-compose environnement](https://github.com/linagora/linshare-docker) or our [Saas offer](https://linshare.app/en/).
