### ISSUE TITLE
Product version mismatch ?

### ISSUE THREAD

**Issue by Harckange** [linagora/linshare#234]
Hello,

I just upgraded Linshare from 4.2.1 to 4.2.6 but i have this showing in the bottom left in the user interface : 
Product version : 4.2.1
Core version : 4.2.6

![image](https://user-images.githubusercontent.com/101645660/169991718-1254daaa-6581-497c-a132-f83e6bdc0c99.png)

On the other gand in the admin panel, the versions match : 

![image](https://user-images.githubusercontent.com/101645660/169992256-0eb37baa-36f9-41a2-a573-d44242a4dbe6.png)

I took these archives from here : http://download.linshare.org/versions/4.2.6/

![image](https://user-images.githubusercontent.com/101645660/169992963-e0749d49-44e1-4c91-a83f-52b9a898e9ad.png)

Any thoughts ?

Thank you 

Julien

**Comment by RockyMeadow** [comment]
Hi @Harckange,

For your case, you should also download archive for linshare-ui-user namely: linshare-ui-user-4.2.6.tar.bz2.

Regards,

**Comment by Harckange** [comment]
Sorry i circled the wrong one... here are the good ones

![image](https://user-images.githubusercontent.com/101645660/169995557-065bad88-d733-4dad-9141-be26774a76fc.png)

**Comment by Harckange** [comment]
`{
  "name": "linshare-ui-user",
  "version": "4.2.1",
  "repository": {},
  "license": "http://download.linshare.org/LinShare-License_AfferoGPL-v3_en.pdf",
  "contributors": [
    {
      "name": "Ismail Anwar-Baig"
    },
    {
      "name": "Kévin Lemele"
    },
    {
      "name": "Alpha Oumar Sall"
    },
    {
      "name": "Sarra Mamlook-Sanchez"
    },
    {
      "name": "Frédéric Martin",
      "email": "fmartin@linagora.com"
    },
    {
      "name": "Dũng T. Phạm",
      "email": "dtpham@linagora.com"
    },
    {
      "name": "Ngọc B. Phạm",
      "email": "bnpham@linagora.com"
    },
    {
      "name": "Tuấn Lê Công",
      "email": "tlcong@linagora.com"
    }
  ],
  "devDependencies": {
    "@babel/core": "7.11.1",
    "@babel/preset-env": "7.11.0",
    "autoprefixer": "6.5.4",
    "babel-loader": "8.1.0",
    "clean-webpack-plugin": "3.0.0",
    "copy-webpack-plugin": "6.0.3",
    "css-loader": "4.2.1",
    "eslint": "7.7.0",
    "eslint-loader": "4.0.2",
    "file-loader": "6.0.0",
    "glob": "7.1.6",
    "html-loader": "1.1.0",
    "html-webpack-plugin": "4.3.0",
    "imagemin-webpack-plugin": "2.4.2",
    "mini-css-extract-plugin": "0.9.0",
    "ng-annotate-loader": "0.7.0",
    "ng-annotate-patched": "1.12.0",
    "node-sass": "4.14.1",
    "optimize-css-assets-webpack-plugin": "5.0.3",
    "postcss-loader": "3.0.0",
    "sass": "1.26.10",
    "sass-loader": "9.0.3",
    "serve-static": "1.14.1",
    "style-loader": "1.2.1",
    "terser-webpack-plugin": "4.1.0",
    "uglifyjs-webpack-plugin": "2.2.0",
    "webpack": "4.44.1",
    "webpack-cli": "3.3.12",
    "webpack-dev-server": "3.11.0",
    "webpack-merge": "5.0.9"
  },
  "scripts": {
    "serve": "webpack-dev-server --watch --progress",
    "serve:prod": "webpack-dev-server --env=prod",
    "build:dev": "webpack",
    "build:prod": "webpack --env=prod"
  },
  "engines": {
    "node": ">=12.18.2"
  },
  "dependencies": {
    "@flowjs/flow.js": "2.14.1",
    "@flowjs/ng-flow": "2.7.8",
    "@uirouter/angularjs": "^1.0.28",
    "angular": "1.8.2",
    "angular-animate": "1.8.2",
    "angular-aria": "1.8.2",
    "angular-cookies": "1.8.2",
    "angular-dragdrop": "1.0.13",
    "angular-http-auth": "1.5.0",
    "angular-local-storage": "0.7.1",
    "angular-material": "1.2.2",
    "angular-messages": "1.8.2",
    "angular-promise-extras": "0.1.9",
    "angular-resource": "1.8.2",
    "angular-route": "1.8.2",
    "angular-sanitize": "1.8.2",
    "angular-touch": "1.8.2",
    "angular-translate": "2.18.4",
    "angular-translate-interpolation-messageformat": "2.18.4",
    "angular-translate-loader-partial": "2.18.4",
    "angular-ui-bootstrap": "2.5.6",
    "bootstrap": "3.4.1",
    "flag-icon-css": "2.8.0",
    "font-awesome": "4.7.0",
    "jquery": "3.6",
    "jquery-ui-touch-punch": "0.2.3",
    "jquery.qrcode": "1.0.3",
    "jqueryui": "1.11.1",
    "js-base64": "2.1.9",
    "lodash": "4.17.21",
    "material-design-iconic-font": "2.2.0",
    "moment": "2.25.2",
    "ng-device-detector": "5.0.1",
    "ng-table": "4.0.0",
    "ngclipboard": "2.0.0",
    "node-waves": "0.7.5",
    "oidc-client": "1.10.1",
    "restangular": "1.6.1",
    "roboto-fontface": "0.10.0",
    "sweetalert": "2.1.2",
    "uuid": "8.3.2"
  }
}`

**Comment by fmartin-linagora** [comment]
Hi,
It is probably a cache issue. Empty your browser's cache and it will work ;)
