### ISSUE TITLE
Change generator of second factor authentification 

### ISSUE THREAD

**Issue by nlonge** [linagora/linshare#237]
Hi guys, 

I want to change the default generator (FreeOTP) on web interface but I didn't find where we can change this on the server. 
The goal is to change the QR code FreeOTP by other.
Someone have an idea please ?
Thanks you

**Comment by RockyMeadow** [comment]
Hello @nlonge,

Unfortunately, the usage of FreeOTP in web interface is not customizable. However using parameter in `Can't scan it` section, you can still manually setup OTP generator in other authenticator apps
