### ISSUE TITLE
SMTP : Fatal HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by Max59C** [linagora/linshare#238]
Hello, 
New fresh install on debian bullseye with Linshare 5.0.4 and i don't know how to fix the errors on sending notifications (guest creation no possible) : 

_[info] javax.net.ssl|ERROR|2A|http-nio-8080-exec-1|2022-06-10 12:52:47.272 UTC|TransportContext.java:345|Fatal (HANDSHAKE_FAILURE): Couldn't kickstart handshaking (
"throwable" : {
 javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
..._

I tried to force TLSv1.3 ou TLSv1.2, same issue.

I tried also to send to send email with other program => no problem

Have you hotfix available?

**Comment by fmartin-linagora** [comment]
Hi,
For what I understand, the issue is on the email server side. It is not using enough recent cyphers. We had the same issue few month ago because our internal relay was using TLS1.1. So we upgraded the smtp relay to support at least TLS 1.2 and it was working perfectly.
Regards,

**Comment by Max59C** [comment]
The service is provided by ovhcloud and works fine with linshare 4.2.6. That's the same i try to use.
Only the configuration "mail.smtp.ssl.protocols" does not exist in 4.2.6 so version 4.2.6 use TLSv1.1?

Few warnings in tomcat logs when loaded linshare and check tls protocols, examples : 
_[2022-06-10 12:48:45] [info] javax.net.ssl|WARNING|01|main|2022-06-10 12:48:45.154 UTC|ServerNameExtension.java:261|Unable to indicate server name
[2022-06-10 12:48:45] [info] javax.net.ssl|DEBUG|01|main|2022-06-10 12:48:45.155 UTC|SSLExtensions.java:260|Ignore, context unavailable extension: server_name
[2022-06-10 12:48:45] [info] javax.net.ssl|WARNING|01|main|2022-06-10 12:48:45.156 UTC|SignatureScheme.java:295|Signature algorithm, ed25519, is not supported by the underlying providers
[2022-06-10 12:48:45] [info] javax.net.ssl|WARNING|01|main|2022-06-10 12:48:45.157 UTC|SignatureScheme.java:295|Signature algorithm, ed448, is not supported by the underlying providers
[2022-06-10 12:48:45] [info] javax.net.ssl|ALL|01|main|2022-06-10 12:48:45.159 UTC|SignatureScheme.java:383|Ignore unsupported signature scheme: ed25519
[2022-06-10 12:48:45] [info] javax.net.ssl|ALL|01|main|2022-06-10 12:48:45.160 UTC|SignatureScheme.java:383|Ignore unsupported signature scheme: ed448
[2022-06-10 12:48:45] [info] javax.net.ssl|ALL|01|main|2022-06-10 12:48:45.161 UTC|SignatureScheme.java:402|Ignore disabled signature scheme: rsa_md5_

**Comment by Max59C** [comment]
If i verify starttls for smtp with command "openssl s_client -tls1_2 -connect ex-mail.biz:587 -starttls smtp"
_CONNECTED(00000003)
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
verify return:1
depth=0 CN = ex-mail.biz
verify return:1
---
Certificate chain
 0 s:CN = ex-mail.biz
   i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
 1 s:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
   i:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHLzCCBhegAwIBAgIQUYmgDrSs1UUmLhKnHOS0QjANBgkqhkiG9w0BAQsFADCB
jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
MB4XDTIyMDMyMTAwMDAwMFoXDTIzMDMyMTIzNTk1OVowFjEUMBIGA1UEAxMLZXgt
bWFpbC5iaXowggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDJivJUI08a
B4569Pg7nUgXDBgIdao5KMUtUVxDEoSEZrcpvypVRnLBYDhJfRoBHEucgoZwg8s7
iv+bKX/yDyKH/3n3NxE3QehI6v1bWqLZF4YkjIAc1tWOkvKUEnJlPheOBEEaB8DX
jjllIRvb/b20GazHsXr+tHwaD4TxIT4qamf8iRiV+CX8pvZO/xOKEbrqraqA7v8q
Ko8oEFhbhBEJ8s4SfRgsRCmThOw1Mws6tH7Q0JH6+4ZYiB9lv/YkbqjLUJDvfKlQ
b3nTAzClKzem3qWzhI4+diUL0hpU2ePS2XoPNL+IbmZy01e6YCSCDqb/6J6XVN5p
X+JugTp5uzDHznIogbc8OwQcnJs46tPxiY35GXp/eVwCHMvA/50OI3tPDIzZZnTZ
iVrcD/1Y8DCeGj5xniHOcO23CFtXvQ6TNMH7ZLyvD9PYmQC63M3inx+HdLMJDhbt
tq4c+gr42bTVcYju1ihfbAeg1BL5opOihIa4oPmFayqEDftSVRvYESh37zC0gPCs
LyvAdBFkawnCKYVSDVcOSQ3aus6FOcctK7Z6vRinPLMPoNzt1Wb4D7dlh3IX5CEa
3dwbZpGpRF5cZcJHTWjkkvlrPH+xoFrS6gPtQRQlg17JerOny4rqqgwQXLWf6XD9
QFkHE6hiPxf9QY7vgoxhTo2aUwR4AO44oQIDAQABo4IC/TCCAvkwHwYDVR0jBBgw
FoAUjYxexFStiuF36Zv5mwXhuAGNYeEwHQYDVR0OBBYEFHwO4V1uuWvXLPz2H/xI
PJe/i6niMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQG
CCsGAQUFBwMBBggrBgEFBQcDAjBJBgNVHSAEQjBAMDQGCysGAQQBsjEBAgIHMCUw
IwYIKwYBBQUHAgEWF2h0dHBzOi8vc2VjdGlnby5jb20vQ1BTMAgGBmeBDAECATCB
hAYIKwYBBQUHAQEEeDB2ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LnNlY3RpZ28u
Y29tL1NlY3RpZ29SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0
MCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNvbTAnBgNVHREEIDAe
ggtleC1tYWlsLmJpeoIPd3d3LmV4LW1haWwuYml6MIIBfQYKKwYBBAHWeQIEAgSC
AW0EggFpAWcAdQCt9776fP8QyIudPZwePhhqtGcpXc+xDCTKhYY069yCigAAAX+s
sVwyAAAEAwBGMEQCIGq84WYO7SEZePLdkSB05M16X7LRO40xhp7wS/S+wc2RAiBx
Ym/49FLwMwiqCVM59poBovjQH4lMtoArg6CV0CYXxgB2AHoyjFTYty22IOo44FIe
6YQWcDIThU070ivBOlejUutSAAABf6yxXDkAAAQDAEcwRQIhAMeykZ+bsFfIM/2g
5ue3LnJXAlZITi9KtXm8eoSFvkq4AiBwwozVHVNDjapZzQc+Oc2G5KL408UC/snZ
fn/1YmfYvgB2AOg+0No+9QY1MudXKLyJa8kD08vREWvs62nhd31tBr1uAAABf6yx
XAsAAAQDAEcwRQIhANrLexkZD3A1PXYpwS+uvxIZjYo+pqkAK/ErnciDTyVmAiB8
58BnajpsNVjqFdKGtqBbk1BPORlvHLPZ/bolw+WfbDANBgkqhkiG9w0BAQsFAAOC
AQEAC6eMUxJTgEUPQO4SUlE6Iu7psfk0Xemq8P2TDbFwNGbOS5gCqExQ9pRo9UI2
ETwbBYURzH5l4zZyYUm/FBXJ1IhSgnXd1oI+Dzwch1ULKSr/ogLQCbfOJvzc+8QG
plXKGTjQKhN4++jYr9gZsuLCWLf24EzbNPK1J7fnV/oi+aunZIe6Zf0ZXDMbX1TV
vDZlmmKKErx0yCQnNzA9lkGcqmBSpd9A8AmjSboqbk91v22WwNeKvurgyunWXZZ5
lOJTVMXARSBm6nGWMGODSkMhIIW9dQdwr1WvG39Ryt6tbv5Od0+B9B7KK8Hk6hze
r8+tVRKHcWhBL+lTfPkHqBR2Sw==
-----END CERTIFICATE-----
subject=CN = ex-mail.biz

issuer=C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4421 bytes and written 429 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 683C000028846EF1030981CAE0CCECEAA10A5264213CC2B9CDC8C58A26277F6D
    Session-ID-ctx:
    Master-Key: 0B5261E969066524A2031006D2C587AF1229B21C3A5D8F9CE95AD8E63DCEEC75BA8757AAD2FFDD09657C1C9106B4EE51
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1654869952
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes_

The return seems work with TLSv1.2

But not with TLSv1.3 "openssl s_client -tls1_3 -connect ex-mail.biz:587 -starttls smtp"

__CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 305 bytes and written 268 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)__

**Comment by Max59C** [comment]
TLS 1.3 is not supported on server side but 1.2 only : https://www.ssllabs.com/ssltest/analyze.html?d=ex-mail.biz
Do you think this server is compatible for linshare 5.0.4?

**Comment by Max59C** [comment]
Hello,
I'm encounter the same issue with smtp.office365.com. So perhaps a bad default configuration on my debian bullseye ?

**Comment by Max59C** [comment]
My fault, bad configuration...
