### ISSUE TITLE
Délai de finalisation des comptes invités

### ISSUE THREAD

**Issue by Max59C** [linagora/linshare#240]
Bonjour,
Lorsqu'un invité est créé, il n'a que 1 heure pour finaliser son compte.
En cas d'utilisation du lien après ce délai, il arrive sur une page de réinitialisation du mot de passe et il ne peut pas finaliser son compte.
Ai-je un défaut de configuration? Est-il possible de modifier ce délai et/ou d'afficher une information explicite du style "Votre lien a expiré"?
Linshare v5.0.4 / Debian 11

**Comment by fmartin-linagora** [comment]
I hope it was the answer you were looking for.
