### ISSUE TITLE
[5.1.0] Formulaire de création de "Filtre Utilisateur LDAP" inutilisable.

### ISSUE THREAD

**Issue by Pingoo31** [linagora/linshare#241]
Pour tester les fonctionnalités de la V5, je viens de déployer un nouveau serveur en 5.1.0.
Lors de la configuration LDAP pour l'authentification des utilisateurs, le fomlulaire de création d'un nouveau filtre est impossible à valider dés lors qu'on modifie certains champs numériques :
![image](https://user-images.githubusercontent.com/43337711/180226430-1f3af403-92da-48f7-8b50-f0e72e195d74.png)
La validation de ces champs se met en erreur "Ce champ ne peut pas être vide" dès qu'on change la valeur par défaut, quelque soit la valeur saisie.
Impossible de finaliser l'installation dans ces conditions.

**Comment by fmartin-linagora** [comment]
@RockyMeadow FYI

**Comment by Yoni19** [comment]
Hello, thank you for reporting this bug, we have fixed it in version 5.1.1
