### ISSUE TITLE
LinShare on kubernetes

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#245]
Second broad question today:

Can I run LinShare on kubernetes (now or in future) ?

Thanks

**Comment by fmartin-linagora** [comment]
Hi,
Yes, it is possible. I thought the helm package was available but it was not. I created it and it is available [here](https://github.com/linagora/linshare-helm).
NB: you may need to update the value.yam file with public images
This is not perfect but you can help up to improve it ! ;)
Regards.
