### ISSUE TITLE
5.1.0 User quota no change after deletion

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#247]
I have another problem with user quota this time:

Few months ago he deleted huge file (2,9GB) from his user space (Quota 4GB).
I have received email about deletion it was looking normal.
Few days ago he logged once again to upload next huge file but his occupied space showed that there is still 2,9GB space busy.
No file on list (no files at all), but user is unable to upload anything over 1,1GB left in quota. 
Also looking to file storage there is no file this size so I'm pretty sure at least physical file is deleted.
What I should do r deliver to resolve this issue ?

**Comment by fmartin-linagora** [comment]
Hi,
it is weird.
Can you provide me the result of "select * from version" ? 
Regards,

**Comment by lacrimal** [comment]
` psql -d linshare
psql (13.6)
Type "help" for help.

linshare=# select * from version;
  id   | version |       creation_date
-------+---------+----------------------------
     1 | 5.0.0   | 2022-03-07 09:55:14.296223
 20196 | 5.1.0   | 2022-07-11 22:16:49.741163
(2 rows)
`
If I see correctly - migration script was never fired between 5.0.0 and 5.1.0 by our dba.
What problems will we have to deal with if we start the script now?

**Comment by fmartin-linagora** [comment]
and the result of : 
```
select id, identifier, modification_date, priority, status from upgrade_task;
```

**Comment by lacrimal** [comment]
```
=# select id, identifier, modification_date, priority, status from upgrade_task;
 id |                           identifier                           |     modification_date      | priority | status
----+----------------------------------------------------------------+----------------------------+----------+---------
 65 | OPTIONAL_POPULATE_EXTERNAL_FAVOURITE_RECIPIENT                 | 2022-07-11 22:16:49.741163 | OPTIONAL | SUCCESS
 53 | UPGRADE_5_1_ADD_INTERNAL_ACCOUNT_TYPE_TO_SHARED_SPACE_MEMBER   | 2022-07-11 22:16:49.741163 | REQUIRED | SUCCESS
 54 | UPGRADE_5_1_ADD_GUEST_ACCOUNT_TYPE_TO_SHARED_SPACE_MEMBER      | 2022-07-11 22:16:49.741163 | REQUIRED | SUCCESS
 55 | UPGRADE_5_1_RENAME_WORKGROUP_TO_WORK_GROUP                     | 2022-07-11 22:16:49.741163 | REQUIRED | SUCCESS
 57 | UPGRADE_5_1_ADD_FIRST_NAME_AND_LAST_NAME_TO_AUDIT_ACTOR_FIELD  | 2022-07-11 22:16:49.741163 | REQUIRED | SUCCESS
 58 | UPGRADE_5_1_ADD_DOMAIN_UUID_TO_SHARED_SPACE_ACCOUNT_IN_MEMBERS | 2022-07-11 22:16:49.741163 | REQUIRED | SUCCESS
 59 | UPGRADE_5_1_ADD_DOMAIN_UUID_TO_SHARED_SPACE_ACCOUNT_IN_NODES   | 2022-07-11 22:16:49.741163 | REQUIRED | SUCCESS
 60 | UPGRADE_5_1_ADD_RELATED_DOMAIN_FIELD_TO_AUDIT                  | 2022-07-11 22:16:49.741163 | REQUIRED | SUCCESS
 61 | UPGRADE_5_1_ADD_DOMAIN_UUID_TO_WORK_GROUP_LAST_AUTHOR_IN_NODES | 2022-07-11 22:16:49.741163 | REQUIRED | SUCCESS
(9 rows)
```

**Comment by fmartin-linagora** [comment]
SQL scripts and upgrade tasks have been run successfully, it seems.

**Comment by fmartin-linagora** [comment]
[fix.quota.sql.txt](https://github.com/linagora/linshare/files/9489961/fix.quota.sql.txt)

Can you try to run this tiny function (from upgrade 4.2 to 5.0 script) ?

**Comment by lacrimal** [comment]
We get few:
```
INFO:  account mail : ug@mydomain.pl (account_id=3718)
INFO:  Sum of de_size and ure_size  : 0
INFO:  Difference between current value and sum of de_size and ure_size  : -2815577600
INFO:  If difference between current_value and sum of document entries size and upload request entries size different than 0, we insert a new entry into operation_history to recalculate account's quota
```
Should I do something more  ?

**Comment by fmartin-linagora** [comment]
Nope, everything should be fine now. Quota are synchronized again.

**Comment by lacrimal** [comment]
Is this some kind of task that we need do periodically ?

**Comment by lacrimal** [comment]
Ok, thanks
