### ISSUE TITLE
Change email "From" value

### ISSUE THREAD

**Issue by urinbar** [linagora/linshare#25]
Hi there,

Thank you for creating such a beautiful project. We are testing out LinShare and after finally getting up to work, found that it uses a constant address "linshare-noreply@linagora.com" as its from address in all outgoing email messages.

Can this constant be changed to something of our own? The most preferable situation would be to use the logged-in sender user's email address (such that replies by destination users will return correctly to the original sender)

Thanks!
Uri

**Comment by fmartin-linagora** [comment]
Hi,
You can change this email address in the LinShare administration interface, Parameters/Functionalities/Domains.
All mails are sent with this email address as sender and for some emails we added the user's address as reply-to.
Regards.
