### ISSUE TITLE
OIDC on AZURE

### ISSUE THREAD

**Issue by Max59C** [linagora/linshare#255]
Hello,

I try to use OIDC feature with AZURE... It seems that the autorization phase work, AZURE send the autorization code to linshre (https://url/?code=...). But nothing else are done...
Is it the good callback url? If i try to manually modify the URL by https://url/#!/oidc/callback?code=...) I receive an error from linshare 'L'authentification SSO a échoué".
I try to enable DEBUG but no more logs :/
I run Linshare 5.1.2

**Comment by Max59C** [comment]
Do i need to try with SPA app on AZURE to use MSAL.js V2 (or V1) ?

**Comment by rlittrell** [comment]
I recently got this working after digging through lots of code and visiting various issues on the go OIDC library github.

Inside Azure Portal, setup a new App registration.  Copy the Directory (tenant) ID from there and use that below for the issuer URL. Copy the Client ID and Client secret and make secrets in Kubernetes. Add your callback url in Azure portal, click on Authentication, click web app, enter Redirect URI.
`  sso: |
    # This is the root URL of the OIDC provider (required).
    issuer: https://sts.windows.net/YOUR-TENET-ID/
    # This is name of the secret and the key in it that contain OIDC client
    # ID issued to the application by the provider (required).
    clientId:
      name: sso-credentials
      key: clientid
    # This is name of the secret and the key in it that contain OIDC client
    # secret issued to the application by the provider (required).
    clientSecret:
      name: sso-credentials
      key: clientsecret
    # This is the redirect URL supplied to the provider (required). It must
    # be in the form <argo-server-root-url>/oauth2/callback. It must be
    # browser-accessible.
    redirectUrl: https://YOUR-HOST/oauth2/callback
    # Additional scopes to request. Typically needed for SSO RBAC. >= v2.12
    scopes:
     - email
    # RBAC Config. >= v2.12
    rbac:
      enabled: false`
      
      Adjust your argo-server deployment to use the sso auth method.
      `
    spec:
      containers:
        - name: argo-server
          image: quay.io/argoproj/argocli:v3.2.8
          args:
            - server
            - '--auth-mode=sso'
            - '--auth-mode=client'
`

**Comment by wboudiche** [comment]
Hello,

Azure authentication using OIDC is supported from the 6.0.2 release.

**Comment by fabienmoyon** [comment]
Hello @Max59C 

You can found the documentation [here](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/sso-microsoft-azure-using-OIDC.md) 

Regards,
Fabien

**Comment by Max59C** [comment]
Thanks a lot!
