### ISSUE TITLE
6.X.X question

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#258]
Can you give little information about 6.X.X version - will 5.1.2 be continued or 6.X.X is natural increment ?

**Comment by fabienmoyon** [comment]
Hello @lacrimal,

You have information in the [CHANGELOG](https://github.com/linagora/linshare/blob/master/CHANGELOG.md#600-alpha1-2022-09-07-download-link)

the 6.0.0 in the next one of the 5.1.2. You have the upgrade guide available [from-v5.1-to-v6.0](https://github.com/linagora/linshare/blob/master/documentation/EN/upgrade/linshare-upgrade-from-v5.1-to-v6.0.md) and  [from-v6.0-to-v6.0.2](https://github.com/linagora/linshare/blob/master/documentation/EN/upgrade/linshare-upgrade-from-v6.0-to-v6.0.2.md)

Regards,
Fabien
