### ISSUE TITLE
i18n Not translating correctly

### ISSUE THREAD

**Issue by samson4649** [linagora/linshare#27]
![image](https://user-images.githubusercontent.com/12725953/40699922-6f5178b8-641a-11e8-9e22-2c0beca0fe9a.png)

i18n tags not being translated in the web interface. 
xhr calls returning 404. 
extracting the filesystem of the docker images and searching for the files returns nothing.

any assistance with the missing files in the xhr calls?

**Comment by Klemele** [comment]
Hello there! 

Pretty weird behavior, look like you miss only the json files...
Could be an issue related to the building process.

But to be sure can you provide me with some extra information? 

In order for me to reproduce and help you I will need the following information:
 - LinShare version installed
 - How did you install it ? (Docker vs Old way, build from source)
 - Which browser with version
 - Extra information about your install/network

**Comment by samson4649** [comment]
Extra information:
We are using the docker-compose file provided though we have removed the frontend service and are exposing port 80 from both the admin and user services to the host instead of going through the tomcat proxy on 8080. We are then doing external SSL handoff with a letsencrypt compatible proxy. 

Please see below the docker-compose.yml file used:

`
# Docker compose file for a full-featured Linshare architecture
version: '2'

services:

    database:
        container_name: linshare_database
        image: linagora/linshare-database:2.1
        networks:
            - linshare-backend-tier
        volumes:
            - ./data/postgres_data/lib:/var/lib/postgresql/data
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=linshare
            - POSTGRES_PASSWORD=PWD_linshare

    backend:
        container_name: linshare_backend
        image: linagora/linshare-backend:2.1
        links:
            - database:linshare_database
            - mongodb:linshare_mongodb
            - thumbnail-server:linshare_thumbnail-server
        networks:
            - linshare-web-tier
            - linshare-tomcat-tier
            - linshare-service-tier
            - linshare-backend-tier
        volumes:
            - ./data/linshare_data/lib:/var/lib/linshare
            - ./conf/catalina.properties:/usr/local/tomcat/conf/catalina.properties
            - ./conf/log4j.properties:/etc/linshare/log4j.properties
        environment:
            # These variables are mandatory
            - SMTP_HOST=192.168.119.223
            - SMTP_PORT=25
            - CLAMAV_HOST=linshare_clamav
            - POSTGRES_HOST=linshare_database
            - POSTGRES_PORT=5432
            - POSTGRES_USER=linshare
            - POSTGRES_PASS=PWD_linshare
            - CLAMAV_PORT=3310
            - MONGODB_HOST=linshare_mongodb
            - MONGODB_PORT=27017
            - THUMBNAIL_ENABLE=true
            # - THUMBNAIL_HOST=thumbnail-server
            # - THUMBNAIL_PORT=8080
            # Default variables can be overriden if needed.
            #- SMTP_USER=<undefined>
            #- SMTP_PASS=<undefined>
            #- CLAMAV_PORT=3310
            #- POSTGRES_PORT=5432

    thumbnail-server:
        container_name: linshare_thumbnail-server
        image: linagora/linshare-thumbnail-server:2.0
        networks:
            - linshare-backend-tier

    ui-admin:
        container_name: linshare_ui-admin
        image: linagora/linshare-ui-admin:3.1
        networks:
            - linshare-web-tier
            - linshare-tomcat-tier
        volumes:
            - ./ssl/redacted/pub.crt:/usr/local/apache2/conf/server.crt
            - ./ssl/redacted/priv.key:/usr/local/apache2/conf/server.key
            - ./ssl/ca.pem:/usr/local/apache2/conf/ssl/server-ca.crt
        ports:
            - 127.0.0.1:8081:80
        environment:
            - EXTERNAL_URL=REDACTED
            - TOMCAT_URL=linshare_backend
            - TOMCAT_PORT=8080

    ui-user:
        container_name: linshare_ui-user
        image: linagora/linshare-ui-user:2.1
        volumes:
            - ./ssl/redacted/pub.crt:/usr/local/apache2/conf/server.crt
            - ./ssl/redacted/priv.key:/usr/local/apache2/conf/server.key
            - ./ssl/ca.pem:/usr/local/apache2/conf/ssl/server-ca.crt
        ports:
            - 127.0.0.1:8080:80
        networks:
            - linshare-web-tier
            - linshare-tomcat-tier
        environment:
            - EXTERNAL_URL=REDACTED
            - TOMCAT_URL=linshare_backend
            - TOMCAT_PORT=8080

    mongodb:
        container_name: linshare_mongodb
        image: mongo:3.2
        volumes:
            - ./data/mongodb_data/db:/data/db
        networks:
            - linshare-backend-tier
        command: mongod --smallfiles

    smtp:
        container_name: linshare_smtp
        image: linagora/opensmtpd
        networks:
            - linshare-service-tier
        volumes:
            - ./conf/smtpd.conf:/etc/smtpd/smtpd.conf
            - ./data/smtp_data/spool:/var/spool/mail

    clamav:
        container_name: linshare_clamav
        image: mkodockx/docker-clamav
        networks:
            - linshare-backend-tier

networks:
    linshare-tomcat-tier:
        driver: bridge
    linshare-web-tier:
        driver: bridge
    linshare-service-tier:
        driver: bridge
    linshare-backend-tier:
        driver: bridge
`

Nothing has been build - just using the docker images: 
- linagora/linshare-database:2.1
- linagora/linshare-backend:2.1
- linagora/linshare-thumbnail-server:2.0
- linagora/linshare-ui-admin:3.1
- linagora/linshare-ui-user:2.1
- linagora/opensmtpd
- mongo:3.2
- mkodockx/docker-clamav

Browsers are:
- firefox dev 61.0b3
- chrome 66.0.3359.181

**Comment by samson4649** [comment]
Is there anyone that can assist with this? 

It appears that there is simply some files missing from the FS volume that is mounted that cant be retrieved when the page loads?

**Comment by fmartin-linagora** [comment]
Hi,
Yes, it's a bug ! LinShare Ui User supports en-US but does not support en-AU. We know, we will fix it but I don't know when !

**Comment by samson4649** [comment]
If anyone comes across this and requires a fix in the meantime; this can be completed with a rewrite rule

# caddy 
 # Rewrite for Great Britain English (en-GB) #
        rewrite /i18n/original/en-GB {
                r (.*)
                to /i18n/original/en-US/{1}
        }

        # Rewrite for Australian English (en-AU) #
        rewrite /i18n/original/en-AU {
                r (.*)
                to /i18n/original/en-US/{1}
        }
