### ISSUE TITLE
[6.0.3] Guest password reset page issue (again)

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#275]
Hi,
I uploaded my server oin 6.0.3 version  and I have an annoying issue:
New guests can't access the reset password page.
There are redirected to login page after a 401 http error.
I didn't test in previous version between 4.2.6 and 6.0.3.
How to correct that?
Regards,

**Comment by matdemb** [comment]
My problem is because the link contain a "//" ex: https://mon.domaine.fr//#!/xxxxxxx.
It wasn't a problem before.
I try to find why there is this "//".

**Comment by matdemb** [comment]
modified in domain/URL Notification.
Strange that it previously worked .

**Comment by fabienmoyon** [comment]
Hello @matdemb,

You are too fast! 

Yes in 6.0.3 we make a breaking change : `ui-user` urls changed for OIDC, we removed the `#!` charaters into `linshare-default.properties` **except** for uploadrequests urls.

You can have a look the documentation here : https://github.com/linagora/linshare/blob/master/documentation/EN/upgrade/linshare-upgrade-from-v6.0-to-v6.0.2.md#update-linshare-defaultproperties-guide 

Regards,
Fabien

**Comment by matdemb** [comment]
Hi,
during the upgrade I modified the apache part (adding the rewrite) but I forgot this part.
I add this in my linshare.properties file.
Thanks.
