### ISSUE TITLE
Problem with integration with LDAP

### ISSUE THREAD

**Issue by jakub-miziolek** [linagora/linshare#3]
I have problem with integration of Linshare 2.0 beta with LDAP. I managed to connect and find users, but authentication doesn't work. Does Linshare support hashed passwords in LDAP database? It works fine with LDAP included in demo VM downloaded, but that LDAP have unencrypted password in its database. I can't find any docs about it.

**Comment by fmartin-linagora** [comment]
LinShare works fine with passwords store with hash methods SHA-1, SHA-256, SSHA-1 and SSHA-256 in ldap directory. 
The authentication process is simple, we search the user with the login using a dedicated ldap query store in the domain pattern. Then we make a bind with the user dn and the password against the ldap directory.

**Comment by jakub-miziolek** [comment]
OK. But we have somehow old md5 hashes. Is it possible to use it? I think it needs to be specified in some docs.

**Comment by fmartin-linagora** [comment]
Yes, I think. There is no dependencies with LinShare. LinShare send dn and plain text password to the LDAP directory. The authentication (bind) is made by the ldap directory with its supported algorism.

**Comment by jakub-miziolek** [comment]
I don't know why, but it looks it is not working with md5. When I created another tree with the same LDAP server and the same data, but where passwords are hashed with SHA it works fine. With md5 it can find users, but authentication fails.

**Comment by fmartin-linagora** [comment]
Hi,
It is weird, it should work because md5 algorism support is embedded in openldap servers.
Which version of openldap are you using ? Which operation system, name  and version, are you using ?

**Comment by jakub-miziolek** [comment]
It is OpenLDAP installed from Ubuntu packages version 2.4.31-1+nmu2ubuntu8.3, Ubuntu Linux 14.04.5 LTS. What's more interesting - LinShare 1.9.5 works fine and authenticates against those md5 passwords. Now I have problems and LinShare 2.0.0 doesn't also with SHA hashed passwords. It first logs in, shows user's dashboard and immediately logs out. In catalina.out I can see first login successful, and in the same second Bad credentials. Really weird.

**Comment by fmartin-linagora** [comment]
Indeed. It is very weird. Could you send me the catalina.out file ?

**Comment by jakub-miziolek** [comment]
I've sent it to you in an email.

**Comment by fmartin-linagora** [comment]
Hi,
First you may need to add the following lines to your log4j.properties files in order to avoid unnecessary traces : 
`
log4j.category.org.hibernate.engine.StatefulPersistenceContext.ProxyWarnLog=ERROR
`

At the end of this file, you also can update this line log4j.category.org.linagora.linshare to debug. it cans help to understand what is going on.

Have you test authentication with linshare 1.12 ?

**Comment by jakub-miziolek** [comment]
I changed log level to debug, but it doesn't seem to log more in catalina.out. There are no real time messages in other Tomcat logs.

I haven't tried LinShare 1.12, but 1.9.5 works fine. Is 1.12 somehow stable release? It looks to be really outdated.

When I try to log in in catalina.out I get:
2016-12-20 15:55:34.924 WARN  [http-nio-8080-exec-1] StatefulPersistenceContext.
java:663 Narrowing proxy to class org.linagora.linshare.core.domain.entities.Lda
pUserProvider - this operation breaks ==
2016-12-20 15:55:35.241 WARN  [http-nio-8080-exec-1] StatefulPersistenceContext.
java:663 Narrowing proxy to class org.linagora.linshare.core.domain.entities.Lda
pUserProvider - this operation breaks ==
2016-12-20 15:55:35.360 INFO  [http-nio-8080-exec-1] LogEntryServiceImpl.java:85
 USER_ACTIVITY:USER_AUTH:5731b953-17ee-4505-a384-7923b84a271e:jxmcio@gmail.com:Successfull authentification
2016-12-20 15:55:35.852 INFO  [http-nio-8080-exec-1] TimingOutInterceptor.java:60 GET:/linshare/webservice/rest/user/v2/authentication/authorized : Request time: 346 ms
2016-12-20 15:55:35.961 INFO  [http-nio-8080-exec-2] TimingOutInterceptor.java:60 GET:/linshare/webservice/rest/user/v2/authentication/authorized : Request time: 48 ms
2016-12-20 15:55:36.006 WARN  [http-nio-8080-exec-4] StatefulPersistenceContext.java:663 Narrowing proxy to class org.linagora.linshare.core.domain.entities.LdapUserProvider - this operation breaks ==
2016-12-20 15:55:36.057 WARN  [http-nio-8080-exec-4] StatefulPersistenceContext.java:663 Narrowing proxy to class org.linagora.linshare.core.domain.entities.LdapUserProvider - this operation breaks ==
2016-12-20 15:55:36.126 INFO  [http-nio-8080-exec-4] LogEntryServiceImpl.java:85 USER_ACTIVITY:USER_AUTH_FAILED:5731b953-17ee-4505-a384-7923b84a271e:jxmcio@gmail.com:Bad credentials.
2016-12-20 15:55:36.139 ERROR [http-nio-8080-exec-4] LdapAuthenticationProvider.java:112 Bad credentials.
2016-12-20 15:55:36.453 INFO  [http-nio-8080-exec-3] TimingOutInterceptor.java:60 GET:/linshare/webservice/rest/user/v2/functionalities : Request time: 535 ms

**Comment by fmartin-linagora** [comment]
LinShare 1.9.x is outdated, there is a lot of version more recent, at least three minor versions : 1.10.x, 1.11.x and 1.12.x. The last stable release for now is LinShare 1.12.3.

**Comment by suresh406** [comment]
what is the password of ldap admin  in Linshare 2.0 beta

**Comment by jakub-miziolek** [comment]
OK - it looks I can't count for more than ten. I've seen a dot and it was 1.1.2 for me. :) I've installed LinShare 1.12.3 and it works fine with our LDAP server regardless of password hashing (plain, md5, sha).

**Comment by fmartin-linagora** [comment]
@suresh406 : please create your own related topic the next time. I finally remeber the answer : ldapsearch -x -bdc=linshare,dc=org -Dcn=admin,dc=linshare,dc=org -wrootpwd
