### ISSUE TITLE
[Linshare 2.1.1] The user interface displays HTML code

### ISSUE THREAD

**Issue by fredo-m** [linagora/linshare#30]
Hi,

In the user interface, in the management of guest accounts, the right column displays the javascript code. See screenshot attached.

Linshare Core : 2.1.1
Linshare UI User : 2.1.1

Regards.

![bug-invite-1](https://user-images.githubusercontent.com/16595693/41147554-fa294414-6b06-11e8-8d86-3c6d59724947.jpg)

**Comment by fmartin-linagora** [comment]
Hi,
It's weird, did you try to clean the cache of your brower ? (do not use shortcut, use the preference menu because i've sometime seen some side effects.)
Our [demo](https://demo.linshare.org/#/administration/adminguests) is up to date, and we do not face this kind of issue.

**Comment by marwanJebahi** [comment]
Hi,
Without any feedback, I m guessing your issue is fixed. I am closing this issue, feel free to reopen it if it is not the case.
Regards
