### ISSUE TITLE
Langue des mails de notification

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#33]
Bonjour,
les mails de notifications d'ajout ou de suppression d'un utilisateur à un groupe ne prend pas en compte la langue de l'utilisateur. Du moins ils sont systématiquement en anglais.
je suis sur la version 2.1.1 de Linshare

**Comment by fmartin-linagora** [comment]
Bonjour,
En effet, après un rapide coup d'oeil, il y avait bien un bug. C'est corrigé sur la branche de maintenannce et ce sera présent dans la prochaine release : https://github.com/linagora/linshare-core/commits/maintenance-2.1.x.
Cordialement,
