### ISSUE TITLE
expiration des utilisateurs invités

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#34]
Bonjour,
est-il normal qu'un utilisateur invité dont la date d'expiration est dépassée de plus de 3 mois accède encore à son espace personnel?
Je suis en 2.1.1.
![image](https://user-images.githubusercontent.com/33221710/43076590-f2810e62-8e84-11e8-8d2b-eae41cde6974.png)

Merci d'avance

**Comment by matdemb** [comment]
j'ai trouvé la cause.
Il s'avère que suite à une des mise à jour (je ne sais pas laquelle), un paramètre a été ajouté dans le paramètre -Dspring.profiles.active du JAVA_OPTS .
Pour que le batch soit activé, il faut ajouter "batches" en plus d'activer la fonction dans le fichier de conf de Linshare.
Bizarre de devoir l'activer à deux endroits différents...

**Comment by fmartin-linagora** [comment]
Bonjour,
Le profile "batches" permet d'activer/désactiver tous les batches de l'application (expiration de partages, fichiers, documents, notifications, ...) Dans le fichier de configuration vous pouvez configurer la fréquence de ces batches.
Cdt,
