### ISSUE TITLE
Probléme de démarrage linshare admin

### ISSUE THREAD

**Issue by chezmohamed** [linagora/linshare#36]
j'ai suivi les étapes d'installation pour Debian 8.9 jessie sans aucune erreur 
version de linshare  2.1.1
https://github.com/linagora/linshare/blob/master/documentation/FR/installation/linshare-install.md

quand j’accède a  linterface d'administration j'ai une fenetre vide login en root
![image](https://user-images.githubusercontent.com/26858857/43203438-7e86d802-901e-11e8-9860-42fb7b9d2ddf.png)

voila le journal de démarrage /var/log/tomcat8/catalina.out
https://pastebin.com/Up4KgZiA

c'est la 10éme fois que je refais l'installation sans aucun resultat toujours le méme probléme

**Comment by fmartin-linagora** [comment]
Bonjour,

Dans les logs du serveur Tomcat, il est possible de constater la ligne suivante : `Unsupported major.minor version 52.0 ` ce qui signifique que vous n'avez pas la bonne version de java installée (ou que Tomcat ne démarre pas avec la vonne version).
Pour vérifier le bon démarrage du tomcat, vous pouvez vous rentre sur la page http://localhost:8080/linshare. Un message d'accueil vous indiquera si le backend fonctionne correctement : "Welcome to LinShare Core. LinShare is up and running ! please Install linshare-ui-admin component to configure LinShare."

Cordialement,

**Comment by chezmohamed** [comment]
Merci d'avoir répondre 
quand j'ai accédé a la page http://localhost:8080 j'ai cet message d'erreur 
![image](https://user-images.githubusercontent.com/26858857/43252969-12e8c46a-90c4-11e8-8642-bb12f7253e66.png)

et concernant la version de java et Tomcat comment je peut télécharger la bonne version qui marche avec Tomcat, puisque j'ai une seul commande pour installer (apt-get install Tomcat),
esque je doit changer les dépôts dans le fichier sourcelist de debian?

Merci encore une fois

**Comment by fmartin-linagora** [comment]
Auriez-vous plusieurs versions de Java installée ? voici la commande pour tester : `dpkg -l | grep openjdk`

**Comment by chezmohamed** [comment]
voici le resultat:
root@debian:~# dpkg -l | grep openjdk
`root@debian:~# dpkg -l | grep openjdk
ii  openjdk-7-jdk:amd64                   7u181-2.6.14-1~deb8u1                      amd64        OpenJDK Development Kit (JDK)
ii  openjdk-7-jre:amd64                   7u181-2.6.14-1~deb8u1                      amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-7-jre-headless:amd64          7u181-2.6.14-1~deb8u1                      amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
`

**Comment by chezmohamed** [comment]
`
root@debian:~# update-alternatives --config java
Il existe 2 choix pour l'alternative java (qui fournit /usr/bin/java).

  Sélection   Chemin                                          Priorité  État
------------------------------------------------------------
  0            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      mode automatique
  1            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      mode manuel
* 2            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      mode manuel
`

**Comment by chezmohamed** [comment]
`
root@debian:~# update-alternatives --config java
Il existe 2 choix pour l'alternative java (qui fournit /usr/bin/java).

  Sélection   Chemin                                          Priorité  État
------------------------------------------------------------
  0            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      mode automatique
  1            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      mode manuel
* 2            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      mode manuel
`

**Comment by fmartin-linagora** [comment]
Il semblerait que le tomcat ignore ce paramétrage. Une solution rapide (surement pas la plus propre) est de supprimer le paquet java-7-openjdk.

**Comment by chezmohamed** [comment]
j'ai refais l'installation a nouveau dans un Ubuntu 16.4 c'est la méme version que la machine virtuel de linshare 
j'ai copier sourcelist de ubuntu de linshare et copier dans ma nouvelle installation
j'ai réussi à installer openjdk-8-jre
`
root@ubuntu:~# dpkg -l | grep openjdk
ii  openjdk-8-jre:amd64                8u171-b11-0ubuntu0.16.04.1      amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64       8u171-b11-0ubuntu0.16.04.1      amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
`
et maintenant j'ai un autre message d'erreur :+1: 
https://pastebin.com/Jcij9BjT

**Comment by chezmohamed** [comment]
le problème de 'Unsupported major.minor version 52.0' est résolu 

linshare admin n'a pas encor démarrer
j'ai tombé sur un autre problème 
https://pastebin.com/9myq03bd

**Comment by fmartin-linagora** [comment]
Bonjour,
Lorsque vous avez une erreur référençant la variable LINSHARE_HOME, cela signifique que vous n'avez pas fourni le fichier de configuration de linshare (linshare.properties) au Tomcat. Le war démarre sans fichier de configuration externe et utilise sa configuration par défaut qui contient cette variable.
Cdt.

**Comment by chezmohamed** [comment]
Merci infiniment mon problème est réglé  vous m'avez sauvé la vie  :)
