### ISSUE TITLE
[2.1.1] English interface acting weird

### ISSUE THREAD

**Issue by fir3wall** [linagora/linshare#37]
Hi, 

Got a problem with a brand new installation that currently testing, followed installation guide and installed it on t2.large (EC2) and Centos7. Translation acting really weird.

Example below:
* Login to website
* No 404 errors on Network activity list
* Some of the strings are not translated
![screenshot1-translation-not-working](https://user-images.githubusercontent.com/8287900/43255077-c130fbfe-90c0-11e8-930d-16c749cb31d4.png)
* Hit F5
* Can see some 404 errors on Network Tab
![screenshot2-translation-working-f5](https://user-images.githubusercontent.com/8287900/43255110-d7d1b812-90c0-11e8-9218-d7d12de145ad.png)
* Can see something weird in apache error log for user interface
![screenshot3-httpd-error-log](https://user-images.githubusercontent.com/8287900/43255121-dc02fc2a-90c0-11e8-92c7-cb15b0fca540.png)
* ... but translation works

Tomcat log does not show any problems (just normal INFO level messages), httpd config is exactly same like provided in example (only ServerName changed) and the machine is not over-utilized (LinShare is only stack running there).

I think the problem is related (based on errors from apache log) to reverse proxy? Can anyone advise on how we can fix this issue as it's now not a great presentation for potential clients who will use solution?

Thanks
Dariusz

**Comment by fir3wall** [comment]
Additional information: Could not replicate this using FR language version (always working out of the box).

Thanks
Dariusz

**Comment by fir3wall** [comment]
Anyone got idea on this? Is github correct place or should be Linshare Redmine to raise that kind of problems?

What is annoying is that does not work after login, but then you just need to flip through pages few times and it works on pages it was not previously :-)

Thanks
Dariusz

**Comment by fmartin-linagora** [comment]
Hi,
This is the right place to ask questions, we may very busy sometimes and do not anwser very quickly. sorry for the delay.
Which language do you use ? I mean the language of your browser.

**Comment by fir3wall** [comment]
Hi @fmartin-linagora 

The good track just found that there is en-US json file but not en-GB . So my browser (Chrome) regional setttings would be GB one 

Thanks
Dariusz

**Comment by fir3wall** [comment]
@fmartin-linagora 
I've tmp fix it with a hack to my F5 proxy, basically, I'm rewriting everything that asking for i18n/original/en-GB/general.json to ask for i18n/original/en-US/general.json

But correct me if I'm wrong I should not do that or provided apache config should maybe cover this bug?

Don't wanted to push it through my F5 so maybe if somebody have idea with quick fix would be better. And understood you busy, you doing great open source work! Many thanks for that

Thanks
Dariusz

**Comment by fmartin-linagora** [comment]
Hi,You did right, it is a good workaround. Using Apache to do the rewrite is also a good solution.
It seems to be an issue, we should be able to support en-GB and en-US. I created an issue here : https://github.com/linagora/linshare-ui-admin/issues/5
