### ISSUE TITLE
problem with anonymous share

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#38]
Hi,
my anonymous shares didn't works anymore.
I thought it was because I disabled the "linshare.datastore.class=org.linagora.linshare.core.dao.EncDbDataStore" parameter but after enabling it again it works for some tests but now it didn't works anymore.
The link show only a white page without any error message in the browser.

Any idea of what's wrong?

Thanks.

**Comment by matdemb** [comment]
I don't know if it's not a cache issue with some web browser...

**Comment by matdemb** [comment]
I came back to the v.2.1.0 of the user UI and the guest share works well.
The first access works correctly without having to open the main page.

**Comment by fmartin-linagora** [comment]
Hello,
Sorry for the delay the team was very busy these past weeks. There was an issue to access to anonymous url page when you are not authenticated on LinShare (which is by default the main goal, not to be authenticated). we fixed it in [2.1.3](https://github.com/linagora/linshare/blob/master/CHANGELOG.md) release.
