### ISSUE TITLE
Pas de prévisualisation

### ISSUE THREAD

**Issue by pelise** [linagora/linshare#40]
Bonjour,

j'ai installé la version 2.1 de linshare sur une machine centOS 7. 

Je rencontre des problèmes avec la prévisualisation. J'ai pourtant suivi l'installation et la configuration de thumbnail décrites sur ce lien https://github.com/linagora/linshare/blob/master/documentation/FR/installation/linshare-install-centos-7.md#thumbnail.

Y a t-il des configurations supplémentaires à faire pour que l'outil marche ? Le problème semble venir du service : il ne reste pas actif plus d'une minute et semble être stoppé par la commande javac qui renvoie de "multiple exceptions".

systemctl status linshare-thumbnail.service
● linshare-thumbnail.service - LinShare thumbnail server
   Loaded: loaded (/etc/systemd/system/linshare-thumbnail.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since ven. 2018-08-03 12:12:01 CEST; 2h 31min ago
  Process: 29661 ExecStart=/usr/bin/java -jar /usr/local/sbin/linshare-thumbnail-server.jar server /etc/linshare/linshare-thumbnail-server.yml (code=exited, status=1/FAILURE)
 Main PID: 29661 (code=exited, status=1/FAILURE)

août 03 12:10:58 TSTSRXW03 systemd[1]: linshare-thumbnail.service: main process exited, code=exited, status=143/n/a
août 03 12:10:58 TSTSRXW03 systemd[1]: Unit linshare-thumbnail.service entered failed state.
août 03 12:10:58 TSTSRXW03 systemd[1]: linshare-thumbnail.service failed.
août 03 12:10:58 TSTSRXW03 systemd[1]: Started LinShare thumbnail server.
août 03 12:10:58 TSTSRXW03 systemd[1]: Starting LinShare thumbnail server...
août 03 12:12:01 TSTSRXW03 java[29661]: Multiple exceptions
août 03 12:12:01 TSTSRXW03 systemd[1]: linshare-thumbnail.service: main process exited, code=exited, status=1/FAILURE
août 03 12:12:01 TSTSRXW03 systemd[1]: Unit linshare-thumbnail.service entered failed state.
août 03 12:12:01 TSTSRXW03 systemd[1]: linshare-thumbnail.service failed.

Cordialement,

Elise

**Comment by fmartin-linagora** [comment]
Bonjour Elise,
Pour plus de détails sur le fonctionnement du serveur, vous devez regarder dans le fichier de logs : /var/log/thumbnail-server.log
Cdt,
Fred.

**Comment by pelise** [comment]
Bonjour,

J'ai trouvé le fichier de log mais je n'arrive pas à corriger les warning pour avoir la prévisualisation. Libreoffice est dans le répertoire /usr/lib64/libreoffice. J'ai l'impression que jod cherche libreoffice dans le dossier /usr/lib/libreoffice. J'ai donc créé un lien pour que /usr/lib/libreoffice pointe sur /usr/lib64/libreoffice. Mais j'obtiens toujours des warning, dont un avec le code d'erreur 81 pour libreoffice. Je ne sais pas comment corriger ces erreurs.

 Voici le contenu du fichier de logs:

INFO  [2018-08-13 08:47:21,457] org.eclipse.jetty.util.log: Logging initialized @2832ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2018-08-13 08:47:21,582] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2018-08-13 08:47:21,583] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2018-08-13 08:47:21,589] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2018-08-13 08:47:21,589] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2018-08-13 08:47:21,594] io.dropwizard.server.ServerFactory: Starting LinShare-Thumbnail-Server
INFO  [2018-08-13 08:47:21,869] org.eclipse.jetty.setuid.SetUIDListener: Opened application@2241f05b{HTTP/1.1,[http/1.1]}{0.0.0.0:8090}
INFO  [2018-08-13 08:47:21,870] org.eclipse.jetty.setuid.SetUIDListener: Opened admin@761956ac{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}
INFO  [2018-08-13 08:47:21,878] org.eclipse.jetty.server.Server: jetty-9.4.z-SNAPSHOT
INFO  [2018-08-13 08:47:21,892] org.linagora.LinThumbnail.ServiceOfficeManager: Start the service...
INFO  [2018-08-13 08:47:21,895] org.artofsolving.jodconverter.util.PlatformUtils: Jod will be using /usr/lib/libreoffice
INFO  [2018-08-13 08:47:21,905] org.artofsolving.jodconverter.office.ProcessPoolOfficeManager: ProcessManager implementation is LinuxProcessManager
WARN  [2018-08-13 08:47:21,941] org.artofsolving.jodconverter.process.LinuxProcessManager: no process found for query [ ProcessQuery[command='soffice.bin',argument='socket,host=127.0.0.1,port=2002'] ]
INFO  [2018-08-13 08:47:21,942] org.artofsolving.jodconverter.office.OfficeProcess: starting process with acceptString '{}' and profileDir '{}'
INFO  [2018-08-13 08:47:22,011] org.artofsolving.jodconverter.office.OfficeProcess: started process; pid = 19665
INFO  [2018-08-13 08:47:22,012] org.artofsolving.jodconverter.office.OfficeConnection: connecting with connectString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
INFO  [2018-08-13 08:47:22,321] org.artofsolving.jodconverter.office.OfficeConnection: connecting with connectString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
WARN  [2018-08-13 08:47:22,324] org.artofsolving.jodconverter.office.ManagedOfficeProcess: office process died with exit code 81; restarting it
WARN  [2018-08-13 08:47:22,335] org.artofsolving.jodconverter.process.LinuxProcessManager: no process found for query [ ProcessQuery[command='soffice.bin',argument='socket,host=127.0.0.1,port=2002'] ]
INFO  [2018-08-13 08:47:22,335] org.artofsolving.jodconverter.office.OfficeProcess: starting process with acceptString '{}' and profileDir '{}'
INFO  [2018-08-13 08:47:22,385] org.artofsolving.jodconverter.office.OfficeProcess: started process; pid = 19677
INFO  [2018-08-13 08:47:22,636] org.artofsolving.jodconverter.office.OfficeConnection: connecting with connectString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
INFO  [2018-08-13 08:47:22,701] org.artofsolving.jodconverter.office.OfficeConnection: connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
INFO  [2018-08-13 08:47:22,702] org.linagora.LinThumbnail.ServiceOfficeManager: service started
INFO  [2018-08-13 08:47:23,879] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    GET     /linthumbnail (org.linagora.linshare.thumbnail.server.ThumbnailResource)
    POST    /linthumbnail (org.linagora.linshare.thumbnail.server.ThumbnailResource)

INFO  [2018-08-13 08:47:23,883] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@654c7d2d{/,null,AVAILABLE}
INFO  [2018-08-13 08:47:23,888] io.dropwizard.setup.AdminEnvironment: tasks =

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

INFO  [2018-08-13 08:47:23,902] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@707e4fe4{/,null,AVAILABLE}
INFO  [2018-08-13 08:47:23,918] org.eclipse.jetty.server.AbstractConnector: Started application@2241f05b{HTTP/1.1,[http/1.1]}{0.0.0.0:8090}
INFO  [2018-08-13 08:47:23,918] org.eclipse.jetty.server.AbstractConnector: Started admin@761956ac{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}
INFO  [2018-08-13 08:47:23,918] org.eclipse.jetty.server.Server: Started @5295ms

Cordialement,

Elise

**Comment by fmartin-linagora** [comment]
Bonjour,
Pour tester que le service fonctionne correctement, vous pouvez tenter les commandes CURL [suivantes](https://github.com/linagora/linshare-thumbnail-server-dockerfile#test) ainsi que le healthcheck : http://127.0.0.1:8081/healthcheck.

NB: pour installation locale, les ports sont 8090 et 8091 alors que dans le conteneur docker c'est 8080 et 8081.

**Comment by pelise** [comment]
Les commandes curl me donnent:
  curl -i 'http://localhost:8090/linthumbnail/?mimeType=image/png'
HTTP/1.1 204 No Content
Date: Mon, 13 Aug 2018 12:22:30 GMT

curl -i 'http://localhost:8090/linthumbnail/?mimeType=image/png' -X POST -H "Content-Type: multipart/form-data" -F"file=@Tux-G2b.png" --output /tmp/preview.multipart.binary
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (26) couldn't open file "Tux-G2b.png"

Et avec le healthcheck j'obtiens ça:
{"MimeType":{"healthy":true},"Service Office Manager":{"healthy":true},"deadlocks":{"healthy":true}}

Donc théoriquement le service devrait fonctionner ? Comment cela se fait-il dans ce cas que je n'obtienne aucune prévisualisation ?

Cordialement, 

Elise

**Comment by pelise** [comment]
Je peux maintenant visualiser des documents png, pptx, ,xlsx, mais pas les pdf et docx.

Cordialement,

Elise

**Comment by fmartin-linagora** [comment]
Bonjour,
Le fichier Tux-G2b.png doit exister pour que cela fonctionne mais oui tout semble fonctionner correctement.

Le thumbnail d'un fichier n'est généré que lors du premier dépot de celui, vous devez déposer un nouveau document que LinShare ne connait pas pour pouvoir générer un thumbnail. 
Vous pouvez forcer la génération des thumbnails pour les documents existants via la requête postgresql suivante : 
`update document set compute_thumbnail = true;`
Les thumbnails seront recalculés pendant la nuit.

**Comment by pelise** [comment]
D'accord merci beaucoup !
