### ISSUE TITLE
calendar bug on 2.1.3

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#42]
Hello,
in the 2.1.3 version of the user UI, I saw a bug with the calendar. 
The colored circle that show the current date and the selected one is bad placed.
See in attached file.
I didn't have this bug on the 2.1.0 version.
I have this bug with all updated web browser (IE, FF, Opera, Chrome).
![pb-calendrier](https://user-images.githubusercontent.com/33221710/45410053-1e41f980-b671-11e8-950c-f31effe9fe6e.png)

**Comment by marwanJebahi** [comment]
Hello,
Sorry for the delay, the team has been very busy lately, 
our team is working on solving this issue.
Thank you for letting us know.

**Comment by marwanJebahi** [comment]
Hello,
The bug was fixed on our last release 2.2.4, see the changelog:
https://github.com/linagora/linshare/blob/master/CHANGELOG.md#224-2019-04-29-download-link
Regards.
