### ISSUE TITLE
unable to login linsahre-user console

### ISSUE THREAD

**Issue by annmaria1** [linagora/linshare#44]
Hi Team, 

I'm unable to login linshare-user console. The error is " The server is temporary not responding". There is no issue to login admin console and uploadproposition console.
Please find the tomcat error log. 
"No root resource matching request path /linshare/webservice/rest/user/v2/authentication/authorized has been found"
The below are the Linshare Version used for it.
linshare-ui-user-2.1.1
Admin Product version : 3.1.1
Core version : 1.12.8
linshare-core-1.12.8-sql.tar.bz2

Please help me to resolve it.

Regards,
George.

**Comment by alamartiniere-Linagora** [comment]
Hello @annmaria1,

The components linshare-ui-user-2.1.1 and linshare-ui-admin-3.1.1 are not compatible with the core version 1.12.8 but with the 2.1.1 version.

In case you are updating LinShare, please follow these upgrade guides https://github.com/linagora/linshare/blob/master/documentation/EN/upgrade/README.md.
If this is your first LinShare installation, please give a go to our last 2.2 version by following this guide https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install.md.

Regards,
Alvin

**Comment by annmaria1** [comment]
Hi Alvin,

I required to use linshare upload request and upload proposition. As per
the information from linshare team, it will available only on version 1.
Thats why i have installed  core version 1.12.8. After the configuration, i
can see the upload request and upload proposition features from admin
console.
Kindly let me know which version is compatible for
linshare-ui-user  console for version 1. I didn't find the package of
version 1 for linshare-ui-user from download repository.

Please help.

Thanks,
George.

**Comment by alamartiniere-Linagora** [comment]
Ok I see your point. 
For LinShare 1.x, the component linshare-ui-user is contained in linshare-core. 
So all you need is linshare-core v1.12.8 and linshare-ui-admin v1.12.8.
Please see this documentation https://github.com/linagora/linshare/blob/maintenance-1.12.x/documentation/EN/installation/linshare-install.md

Regards, 
Alvin

**Comment by annmaria1** [comment]
Thanks for your reply.
Now i understood that  linshare-ui-user contained in linshare-core
(redirect to  v1.12.8.war in apache configuration)
But I didn't find linshare-ui-admin v1.12.8 in download repository.
Can you please help me to share the download url for it

Thanks
George.

**Comment by annmaria1** [comment]
Hi Alvin,

One more question, Is it work Java version 8?

*+ 1           java-1.8.0-openjdk.x86_64
(/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java)

Thanks,
George.

**Comment by fmartin-linagora** [comment]
Hi George,
All 1.12..x components are available here : http://download.linshare.org/versions/1.12.6/
LinShare 1.12.x works only with Java 1.7. The installation guide for this old version is available in a specific branch here : https://github.com/linagora/linshare/tree/maintenance-1.12.x/documentation/EN/installation
Fred.

**Comment by annmaria1** [comment]
Thank you Fred.
Its working now.
Let me try to configure Windows AD authentication based on security group
(Distribution list.)


[image: image.png]

Thanks
George.
