### ISSUE TITLE
anonymous share issue

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#48]
Hi,
I still have an issue with the anonymous share function (on 2.2.1 version).
When I create an anonymous share for a file, when I try to access to the generated link (https://FQDN/#/external/anonymous/xxxxxxxxxxxxx) I'm redirected to the main login page.
In log file, I can see
[ERROR]:http-bio-8080-exec-6:20190114.112849:org.linagora.linshare.webservice.interceptor.BusinessExceptionMapper:toResponse:A BusinessException was caught : code=ANONYMOUS_URL_FORBIDDEN,  You do not have the right to get this anonymous url : 57e73c3a-0c84-464f-b94d-49c749eaf8ca

The functionality is activated in the configuration, I don't understand why it still doesn't work.
bug or error of configuration?
I think it previously works but not sure.

Thanks for any help.

**Comment by matdemb** [comment]
my server is an updated one (from 2.1.3 I think).
I've just test with a clone, deleting all databases and doing a new fresh install (only for dB conf, all others, java and apache, are the same) and the problem doesn't occure...

**Comment by fmartin-linagora** [comment]
Hello,
I can't reproduce this issue with the same version  ?  2.2.1 ?

**Comment by matdemb** [comment]
my server is an updated one (from 2.1.3 I think).
I've just test with a clone, deleting all databases and doing a new fresh install (only for dB conf, all others, java and apache, are the same) and the problem doesn't occure...

**Comment by fmartin-linagora** [comment]
Sorry, but I don't understand at all what you did. :s Which version are you using ? which upgrade are you trying to do ?

**Comment by matdemb** [comment]
I was in version 2.1.3 and I previously update to 2.2.1.
On this server the anonymous URL doesn't work (redirection to home page).
I did a clone of this machine, delete all databases and rebuild them and the problem disappear.
I hope it's more clear.

**Comment by fmartin-linagora** [comment]
Ok. Maybe a cache issue in the brower. Anyway if it is solved, it's perfect.

**Comment by matdemb** [comment]
After many tests, I have some case it works and some other one where it doesn't.
in fact it depends of the name machine used.
in my apache, I have:
ServerName partage.domaine.fr
ServerAlias partage.domaine.net linshare01 linshare01.mipih.net

the server real name is linshare01.mipih.net (in /etc/hostname).

It work when the request is done with linshare01 and linshare01.mipih.net but not with partage.domaine.fr and partage.domaine.net (redirection to home page).

I think it's a naming issue with my configuration but there is no such parameter in linshare side and the Apache one seems OK (it work fine for everything but anonymous URL).
So I don't understand...

**Comment by matdemb** [comment]
The only difference I see is that url that doesn't works are going through a nginx proxy server.
I'll watch requests received by the server...

**Comment by matdemb** [comment]
apparently, our issue is caused by our reverse proxy nginx but no idea why...
everything works except url_anonymous in this configuration.
We would try to redirect directly from nginx to tomcat but this configuration is totally unusable and for that to, we doesn't find why.
Any help would be great.
