### ISSUE TITLE
Trouble installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by obrochard** [linagora/linshare#53]
OS : Ubuntu 18.04
linshare version : 2.2.3

tomcat8 start with error :
Unresolvable class definition for NamespaceHandler class [org.apache.cxf.jaxrs.spring.NamespaceHandler] for namespace [http://cxf.apache.org/jaxrs]

Could you help me

tail /var/log/tomcat8/catalina.out

[ERROR]:localhost-startStop-1:20190207.104847:org.springframework.web.context.ContextLoader:initWebApplicationContext:Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from file [/var/lib/tomcat8/webapps/linshare/WEB-INF/classes/springContext-webservice-admin.xml]; nested exception is org.springframework.beans.FatalBeanException: Unresolvable class definition for NamespaceHandler class [org.apache.cxf.jaxrs.spring.NamespaceHandler] for namespace [http://cxf.apache.org/jaxrs]; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:413)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:335)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:187)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:223)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:194)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)

**Comment by rouazana** [comment]
Hi,
Which Java version are you using?
Regards,
Raphaël.

**Comment by obrochard** [comment]
java -version

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Comment by fmartin-linagora** [comment]
Hi,
Please can you execute the following command and return us the result : 
`dpkg -l |grep openjdk`
Fred.

**Comment by obrochard** [comment]
dpkg -l |grep openjdk
ii  openjdk-11-jdk:amd64                  10.0.2+13-1ubuntu0.18.04.4                 amd64        OpenJDK Development Kit (JDK)
ii  openjdk-11-jdk-headless:amd64         10.0.2+13-1ubuntu0.18.04.4                 amd64        OpenJDK Development Kit (JDK) (headless)
ii  openjdk-11-jre:amd64                  10.0.2+13-1ubuntu0.18.04.4                 amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-11-jre-headless:amd64         10.0.2+13-1ubuntu0.18.04.4                 amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-8-jdk:amd64                   8u191-b12-2ubuntu0.18.04.1                 amd64        OpenJDK Development Kit (JDK)
ii  openjdk-8-jdk-headless:amd64          8u191-b12-2ubuntu0.18.04.1                 amd64        OpenJDK Development Kit (JDK) (headless)
ii  openjdk-8-jre:amd64                   8u191-b12-2ubuntu0.18.04.1                 amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64          8u191-b12-2ubuntu0.18.04.1                 amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

**Comment by fmartin-linagora** [comment]
Hi,
You can either remove java 11 or make tomcat use java 8.
Ex:
`sudo vim /etc/default/tomcat8`
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
Then restart tomcat 
```
sudo systemctl restart tomcat8.service
sudo systemctl status tomcat8.service
```

**Comment by obrochard** [comment]
Hi,
It's works better, no error on tomcat8

But i had error on user interface :

elinks http://127.0.0.1/linshare

cf screenshot.

Do you have an idea ?

![tomcat_error](https://user-images.githubusercontent.com/7044359/52940486-fadd5200-3366-11e9-8766-12b3fc544d36.png)

**Comment by obrochard** [comment]
It's works
