### ISSUE TITLE
Admin interface empty on debian 8 install

### ISSUE THREAD

**Issue by LucNig** [linagora/linshare#54]
On my fresh install on debian 8 my admin panel is empty (only the frame is visible)
It asks for username and password, i can auth but afther that nothing happends.

I cannot see any errors in my catalina.out log which point me in right direction.:

see attached 
[catalina.txt](https://github.com/linagora/linshare/files/2850299/catalina.txt)

**Comment by yazidsebahi** [comment]
Hello,
Can you tell me which version of java and LinShare are you using, please?

**Comment by LucNig** [comment]
Hello,
Java version:
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

linshare version is latest: 2.2.3

**Comment by yazidsebahi** [comment]
ok, can you send me the errors on your browser console, please

**Comment by LucNig** [comment]
That's my problem, I only see the framework with some icons in upper right corner.
The menu on left is empty. I can auth, but after that noting show up. 
After do some reading and investigating, i would say it's a problem with connecting to tomcat but i don't see corresponding errors...

With log do you suggest to dive into?

**Comment by LucNig** [comment]
this is the browser console:

1549876219751	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1549876219751	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
UpdateUtils.getAppUpdateAutoEnabled - Unable to read app update configuration file. Exception: Win error 2 during operation open on file C:\ProgramData\Mozilla\updates\308046B0AF4A39CB\update-config.json (Het systeem kan het opgegeven bestand niet vinden.

) UpdateUtils.jsm:180
Content Security Policy: Instructie ‘child-src’ wordt niet meer ondersteund. Gebruik instructie ‘worker-src’ voor het beheren van workers, respectievelijk instructie ‘frame-src’ voor het beheren van frames.
(intermediate value).messages is undefined ASRouter.jsm:116
Toetsgebeurtenis niet beschikbaar op sommige toetsenbordindelingen: key=‘i’ modifiers=‘accel,alt,shift’ id=‘key_browserToolbox’ browser.xul
Wachtwoordvelden aanwezig op een onveilige pagina (http://). Dit vormt een beveiligingsrisico dat het stelen van gebruikersreferenties mogelijk maakt.[Meer info]
afs.netways.nl
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/authentication/authorized?ignoreAuthModule=true
Regelnummer 1, kolom 1:
authorized:1:1
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/authentication/authorized
Regelnummer 1, kolom 1: authorized:1:1
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/upgrade_tasks
Regelnummer 1, kolom 1: upgrade_tasks:1:1
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/authentication/version
Regelnummer 1, kolom 1: version:1:1
1549876851054	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242
1549876851061	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242
1549876851062	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242
Error while detaching the browsing context target front: Connection closed, pending request to server1.conn0.parentProcessTarget1, type detach failed

Request stack:
request@resource://devtools/shared/protocol.js:1384:14
generateRequestMethods/</frontProto[name]@resource://devtools/shared/protocol.js:1545:14
BrowsingContextTargetFront<.detach<@resource://devtools/shared/fronts/targets/browsing-context.js:84:24
destroy/this._destroyer<@resource://devtools/client/framework/target.js:800:17
destroy@resource://devtools/client/framework/target.js:775:24
eventSource/proto.emit@resource://devtools/shared/client/event-source.js:128:9
onClosed@resource://devtools/shared/client/debugger-client.js:900:5
close@resource://devtools/shared/transport/local-transport.js:154:9
close@resource://devtools/shared/transport/local-transport.js:150:7
close@resource://devtools/shared/transport/local-transport.js:150:7
cleanup@resource://devtools/shared/client/debugger-client.js:300:9
detachClients@resource://devtools/shared/client/debugger-client.js:325:9
safeOnResponse@resource://devtools/shared/client/debugger-client.js:519:14
listenerJson@resource://devtools/shared/client/debugger-client.js:542:26
emit@resource://devtools/shared/event-emitter.js:178:15
emit@resource://devtools/shared/event-emitter.js:255:5
emitReply@resource://devtools/shared/client/debugger-client.js:823:31
callFunctionWithAsyncStack@resource://devtools/shared/platform/stack.js:61:10
onPacket@resource://devtools/shared/client/debugger-client.js:825:9
send/<@resource://devtools/shared/transport/local-transport.js:64:11
exports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
exports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
browsing-context.js:86:7
Wachtwoordvelden aanwezig op een onveilige pagina (http://). Dit vormt een beveiligingsrisico dat het stelen van gebruikersreferenties mogelijk maakt.[Meer info]
afs.netways.nl
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/authentication/authorized?ignoreAuthModule=true
Regelnummer 1, kolom 1:
authorized:1:1
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/authentication/authorized
Regelnummer 1, kolom 1: authorized:1:1
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/upgrade_tasks
Regelnummer 1, kolom 1: upgrade_tasks:1:1
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/authentication/version
Regelnummer 1, kolom 1: version:1:1

**Comment by yazidsebahi** [comment]
You need to connect to one interface at the same time. (or use another browser)

**Comment by LucNig** [comment]
Yes i know, Thats why i use firefox for admin console to test and chrome for user.

I see some XML parse errors where is says element no found, but 
Another browser dump which is slightly different:

<unavailable> be72a9b3.vendor.js:8:19408
Error: can't assign to property "date" on "": not an object
addError@http://afs.netways.nl/scripts/36e34a29.scripts.js:3:4628
@http://afs.netways.nl/scripts/36e34a29.scripts.js:1:2856
errorCallback@http://afs.netways.nl/scripts/be72a9b3.vendor.js:26:31428
wrappedErrback@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:27562
wrappedErrback@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:27562
then/<@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:29094
$eval@http://afs.netways.nl/scripts/be72a9b3.vendor.js:9:5398
$digest@http://afs.netways.nl/scripts/be72a9b3.vendor.js:9:3252
$apply@http://afs.netways.nl/scripts/be72a9b3.vendor.js:9:5823
done@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:3280
completeRequest@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:7165
createHttpBackend/</xhr.onreadystatechange@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:8109
be72a9b3.vendor.js:8:19408
<unavailable> be72a9b3.vendor.js:8:19408
Error: can't assign to property "date" on "": not an object
addError@http://afs.netways.nl/scripts/36e34a29.scripts.js:3:4628
@http://afs.netways.nl/scripts/36e34a29.scripts.js:1:2856
fetchFunction/<@http://afs.netways.nl/scripts/be72a9b3.vendor.js:26:29542
wrappedErrback@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:27562
wrappedErrback@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:27562
then/<@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:29094
$eval@http://afs.netways.nl/scripts/be72a9b3.vendor.js:9:5398
$digest@http://afs.netways.nl/scripts/be72a9b3.vendor.js:9:3252
$apply@http://afs.netways.nl/scripts/be72a9b3.vendor.js:9:5823
done@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:3280
completeRequest@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:7165
createHttpBackend/</xhr.onreadystatechange@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:8109
be72a9b3.vendor.js:8:19408
<unavailable> be72a9b3.vendor.js:8:19408
Error: can't assign to property "date" on "": not an object
addError@http://afs.netways.nl/scripts/36e34a29.scripts.js:3:4628
@http://afs.netways.nl/scripts/36e34a29.scripts.js:1:2856
errorCallback@http://afs.netways.nl/scripts/be72a9b3.vendor.js:26:31428
wrappedErrback@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:27562
wrappedErrback@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:27562
then/<@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:29094
$eval@http://afs.netways.nl/scripts/be72a9b3.vendor.js:9:5398
$digest@http://afs.netways.nl/scripts/be72a9b3.vendor.js:9:3252
$apply@http://afs.netways.nl/scripts/be72a9b3.vendor.js:9:5823
done@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:3280
completeRequest@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:7165
createHttpBackend/</xhr.onreadystatechange@http://afs.netways.nl/scripts/be72a9b3.vendor.js:8:8109
be72a9b3.vendor.js:8:19408
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/authentication/authorized
Regelnummer 1, kolom 1: authorized:1:1
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/upgrade_tasks
Regelnummer 1, kolom 1: upgrade_tasks:1:1
XML-parsefout: geen hoofdelement gevonden
Locatie: http://afs.netways.nl/linshare/webservice/rest/admin/authentication/version
Regelnummer 1, kolom 1:

**Comment by fmartin-linagora** [comment]
Hi,
Which version are you attempting to install ?
For the record, we published Friday a new security release [2.2.3](http://download.linshare.org/versions/2.2.3/) and you can find the latest installation guide [there](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install.md). You could install LinShare on Debian Stretch (9), we will update the documentation about that.

**Comment by LucNig** [comment]
Hi Fmartin,

I had same issue with 2.2.2
I downloaded the latest release and applied it today.

Running debian 8 know, think this should work fine?

everything seems quite straightforward but can find where it goes wrong

**Comment by LucNig** [comment]
Hi,

After studying for several hours i decided to test with docker, which works fine. After that i reinstalled the machine with debian 9 and it works fine. So not sure wat caused my problem but thread can be closed...
