### ISSUE TITLE
Reset password page empty

### ISSUE THREAD

**Issue by Thomaslne** [linagora/linshare#55]
Hello, 

I make a new install of linshare on debian 9.6.
I use these products : 
linshare-core-2.2.3.war
linshare-ui-admin-3.2.1.tar.bz2
linshare-ui-user-2.2.2.tar.bz2
thumbnail-server-2.0.3.jar
linshare-core-2.2.3-sql.tar.bz2

The installation is working properly (part admin and user).
We declared a domain with AD and then shared files without problems.
Currently, we can create a guest account in the contact section, the recipient receives an email.
When the recipient tries to initialize their account, the LinShare application launches, but only the background image appears.
Here is the link used 'http://dl.lne.fr/#/external/reset/e8aa8784-9bf7-403e-9dab-768d90ae972e'.
We found the following errors in the log file of the user part:
172.22.22.1 - - [14/Feb/2019:13:23:30 +0100] "GET /linshare/webservice/rest/user/v2/authentication/authorized HTTP/1.1" 401 1338 "https://dl.lne.fr/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36"

**Comment by yazidsebahi** [comment]
Hello, 
Thank you for letting us know, I confirm this bug, we will fix it soon.

**Comment by yazidsebahi** [comment]
Hello, 
The bug was fixed on our last release 2.2.4, see the [changelog](https://github.com/linagora/linshare/blob/master/CHANGELOG.md#224-2019-04-29-download-link) 
Regards.
