### ISSUE TITLE
[Linshare 2.2.3] No guest menu

### ISSUE THREAD

**Issue by fredo-m** [linagora/linshare#56]
Hi,
I updated Linshare from version 2.1.1 to version 2.2.3 hoping that the guest function will work, and it still is not.
The guest domains are created under each domain and the guest functionality is enabled at the "LinShareRootDomain" level and in the domains.
The sub-menu for guests does not appear in the "Contacts" menu.

I use:
- linshare-core-2.2.3
- linshare-ui-admin-3.2.1
- linshare-ui-user-2.2.2

![linshare-ui-admin-3 2 1](https://user-images.githubusercontent.com/16595693/53257452-78d48c80-36ca-11e9-9e47-6287a7816fda.png)

![linshare-ui-user-2 2 2](https://user-images.githubusercontent.com/16595693/53257453-78d48c80-36ca-11e9-9b69-ae73f2576817.png)

Have I forgotten something?

Regards.

**Comment by fmartin-linagora** [comment]
Hello,
It is very weird, maybe a browser cache issue because I applied the same settings to the [demo](https://demo.linshare.org/#/home) and I have the menu.
Can you try to empty your cache ?

**Comment by fredo-m** [comment]
Hi,

Thank you for your reply.

I emptied the cache and tested in another browser with private browsing and I still have no link for guests.

Regards.

**Comment by marwanJebahi** [comment]
Hello,
The problem here is if you enable the guest functionality after being connected with this user, this functionality will be not overrided for this user, but it will be for the next users.
So to solve this,  if this account does not have a data, you can delete it, enable the guest functionality, and then connect with it.
Or you can easly turn the field can_create_guest to True in your DB.
Regards.

**Comment by fredo-m** [comment]
Hi,

Great, it's the solution!

I deleted the user, reconnected and the link for the guests is visible. Thank you !

I created a guest, I have received the activation link, I clicked on the link, the Linshare test site is displayed (http://linshare-test.XXX.com/#/external/reset/f93338d9-5347-474a-b4ce-3e18d573065b), but I only have the background image. Ctrl+F5 does not change anything. I do not have the login form. See the screenshot.

![screenshot_2019-02-27 linshare](https://user-images.githubusercontent.com/16595693/53496070-89597e00-3aa1-11e9-9470-a7218c38294d.png)

The source code of the page:

`<!doctype html><!--[if IE 9 ]><html class="ie9" x-ng-app="linshareUiUserApp" x-ng-controller="materialAdminController as mactrl"><![endif]--> <![if IE 9 ]><html x-ng-app="linshareUiUserApp" x-ng-controller="materialAdminController as mactrl"><![endif]> <head> <meta charset="utf-8"> <title>LinShare</title> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0"> <meta name="description" content=""><!-- Place favicon.ico and apple-touch-icon.png in the root directory --> <link rel="stylesheet" href="styles/vendor.5f96fb7e.css"> <link rel="stylesheet" href="styles/materialAdmin.181f57c9.css"> <link rel="stylesheet" href="styles/theme.default.9b4cd70f.css"> </head> <body data-ng-controller="UiUserMainController as mainVm" data-ng-class="{'sw-toggled': mactrl.layoutType === '1', 'lock-scroll': mactrl.sidebarToggle.left}" flow-init flow-object="mainVm.flowUploadService.flowObj" flow-prevent-drop> <data ui-view x-ng-cloak=""> </data><!--<footer class="footer">--><!--<p>Powered by <a href="http://www.linagora.com">Linagora ©</a> 2009–2015.</p>--><!--</footer>--> <script src="scripts/vendor.9856b9fe.js"></script> <script src="scripts/scripts.23a71574.js"></script> <script src="config/config.js"></script>`


Do you prefer that I open another ticket?

Regards.

**Comment by marwanJebahi** [comment]
Hello,
It was working in the LinShare's 2.1 version, our team is currently working on it.
Regards.

**Comment by aroussel62** [comment]
hello, we also have this bug (reported by  fredo-m  on Feb 27) with : 
- core = 2.2.3
- ui = 2.2.2
is this issue still open in 2.2.4 ? didnt see it on changelog
Regards

**Comment by marwanJebahi** [comment]
Hello,
The bug was fixed on our last release 2.2.4, see the https://github.com/linagora/linshare/blob/master/CHANGELOG.md#224-2019-04-29-download-link
Regards.
