### ISSUE TITLE
autocompletion issue

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#59]
Hello,
I observe an issue with completion functionality.
When I type first letters of a name, the list of corresponding users appear and at the end of the list, some blanks lines appears too.
If I select one of them, I see that it's old guests (or anonymous?) users that have been deleted.
Is it possible to delete references of all old guests or anonymous users from the completion.
my version is 2.2.1 .
![image](https://user-images.githubusercontent.com/33221710/54025864-28fec680-419c-11e9-8e30-1b7ad4e588d8.png)

Thanks

**Comment by marwanJebahi** [comment]
Hello,
Thank you for letting us know, our team will investigate about this issue.
Regards,

**Comment by marwanJebahi** [comment]
Hello,
Issue already fixed.
I'm closing this issue, if it is not the case feel free to reopen it.
Regards
