### ISSUE TITLE
problème avec les mails de changement de droits sur les workgroup

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#60]
Bonjour,
le message reçu par un utilisateur lorsqu'on lui change les droits sur un workgroup est erroné.
Si on lui met les droits en lecture, le mail indique qu'on lui a mis les droits en écriture.
si on lui met les droits en écriture, ca lui indique lecture, contribution indique lecture. 
Seuls les droits admin sont bien indiqués dans le mail.
v2.2.1
Cordialement

**Comment by marwanJebahi** [comment]
Hello, 
Yes i confirm this bug and we will fix it in the shortest time. Thank you for informing us this issue
Regards,

**Comment by yazidsebahi** [comment]
Hi, bug fixed on our latest release 2.3.0  version. 

Regards.
