### ISSUE TITLE
Issue Starting LinShare for the first time on CentOS 7

### ISSUE THREAD

**Issue by macinapp2** [linagora/linshare#62]
Hello,

I have followed all setup instructions but have run into trouble at this section:

> To start LinShare, first start the Tomcat service :
> 
> [root@localhost ~]$ systemctl restart tomcat
> 
> To verify that LinShare works, consult the logs file :
> 
> [root@localhost ~]$ tail -f /var/log/tomcat/catalina.out
> 
> If the service start correctly, you should have those following messages:
> 
> [...]
> org.apache.coyote.http11.Http11Protocol start
> INFO: Démarrage de Coyote HTTP/1.1 sur http-8080
> org.apache.catalina.startup.Catalina start
> INFO: Server startup in 23151 ms
> 

My catalina.out file is blank after restarting tomcat. How can I figure out why nothing happens when I restart Tomcat? I am attaching my linshare.properties and /etc/sysconfig/tomcat files. 

Thank you
[Linshare_Files.zip](https://github.com/linagora/linshare/files/3085823/Linshare_Files.zip)

**Comment by yazidsebahi** [comment]
I think your issue is resolved according to our discussion on https://github.com/linagora/linshare/issues/46#issuecomment-486270076  ?
