### ISSUE TITLE
issue on password initialization for guest users 2.2.3

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#64]
Hello,
we have an old issue that appear again on 2.2.3.
When we create a guest user and try to open the initialization password page (xx/#/external/reset/xxx), we have a blank page (only the background).
No errors in tomcat logs.
annoying...
back in 2.2.1, it comes back to normal.

**Comment by marwanJebahi** [comment]
Hello,
Thank you for your report, the team will check and fix it soon.
Regards,

**Comment by yazidsebahi** [comment]
Hello, 

The bug was fixed on our last release 2.2.4, see the [changelog](https://github.com/linagora/linshare/blob/master/CHANGELOG.md#224-2019-04-29-download-link) 

Regards.

**Comment by matdemb** [comment]
Hello,
I will test it.
That's strange this bug (or something like it) appear regularly every 2-3 subversion in guest creation process...
Thanks
