### ISSUE TITLE
no expiration date

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#69]
Hello,
since several versions (2.2.1 now), I have an issue with the expiration date.
Some documents have an "undefined". It seems it's when a share is applied to the file.
The problem is that some of them are not deleted automatically (I don't know if there is a link).
The expiration date is 10 days but some documents have been imported a month ago and still in user space.
Thanks.

**Comment by matdemb** [comment]
Hello,
 same issue on the 2.3 version.
Best regards,

**Comment by fmartin-linagora** [comment]
Hi,

I suppose this issue has been fixed since a long time, but just in case. 
You need to enable the functionality in the admin interface for your domain and also enable the batch in the linshare.properties file:

```
# job.document.cleaner.activation=false
```
Regards,

**Comment by matdemb** [comment]
Hi,
I think so.
Regards,
