### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by franshesco** [linagora/linshare#7]
Hi, 

I have tested the linshare installation and I have the two interfaces but i face two issues:
1- my linshare administration interface is empty. I just have the header "LinShare administration interface" with icons (home. language, user) but no content on the page. I don't know if it is normal.
2- I can not access to the user interface with the login parameters.

thx

**Comment by fmartin-linagora** [comment]
Hi,
When you try to access to the administration interface, you load all html, css and javascript assets in your brower and then the application try to access to the tomcat. if the tomcat is reached, it require authentification and the login popup is displayed. If the application can not reach the tomcat nothing happen. You shoud check tomcat logs (catalina.out file).
Administration and user interface both require to access to Tomcat.
Fred.

**Comment by franshesco** [comment]
Hi @fmartin-linagora ,

thx for your reply. my tomcat works fine. Below is the output of my catalina.out file
`# tail -f /var/log/tomcat/catalina.out 
tomcat-7.0.76 RPM installed`

And below is the output of another catalina log file
`tail -f /var/log/tomcat/catalina.2017-09-27.log 
Sep 27, 2017 5:13:38 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/linshare] startup failed due to previous errors
Sep 27, 2017 5:13:39 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat/webapps/linshare.war has finished in 35,989 ms
Sep 27, 2017 5:13:39 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Sep 27, 2017 5:13:39 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Sep 27, 2017 5:13:39 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 36671 ms`

I still have the same issue.

thx

**Comment by franshesco** [comment]
hello everybody, 

nothing to do ?

**Comment by fmartin-linagora** [comment]
Hi,
When I read the first line of your catalina.2017-09-27.log, I see an error : 
`SEVERE: Context [/linshare] startup failed due to previous errors`.

I suggest you to look deeper in this file to know why it failed.

**Comment by franshesco** [comment]
thx @fmartin-linagora

**Comment by ndcsilent** [comment]
Hi 
I have same problem until now i can find the error
How do i check the file? im newbie in linux
