### ISSUE TITLE
I cant find default linshare-ui-user

### ISSUE THREAD

**Issue by ndcsilent** [linagora/linshare#70]
Hi, I'm new here I can't copy the default linshare ui-user.conf 
Error:: cannot stat default: no such file or directory

where can I find the linshare ui-user.conf

**Comment by marwanJebahi** [comment]
Hello,
You are trying to deploy LinShare on Centos or Debian?
Regards

**Comment by ndcsilent** [comment]
Hi, marwanjebahi,
I'm installing it on ubuntu beaver 18.04.

**Comment by marwanJebahi** [comment]
Hello,
You can copy the ui-user.conf in `/etc/apache2/sites-available/` and then configure the `VirtualHost`
Regards

**Comment by fmartin-linagora** [comment]
Hi,
Without any feedback, I guessing your issue is fixed. I am closing this issue, feel free to reopen it if it is not the case.
