### ISSUE TITLE
Minor Typo spotted on homepage

### ISSUE THREAD

**Issue by mtpiercey** [linagora/linshare#73]
On https://www.linshare.org/en/index.html, I noticed a textbox that said (under the *Modern Design* box): ```intuive```.

I'm fairly sure the word in question should be ```intuitive```. Just thought I'd mention that. 

At any rate, keep up the good work!

**Comment by yazidsebahi** [comment]
Hello, Thank you for your remark, We will fix it soon. 

Regards.

**Comment by marwanJebahi** [comment]
Hello,
Sorry for the delay, the team has been very busy lately.
The bug is fixed. Im closing this ticket, don't hesitate to submit other issues or proposition.
Regards.
