### ISSUE TITLE
2.3 upgrade issue

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#75]
Hello,
I have updated my test server from 2.2.1 to 2.3 and I have an issue on upgrade task UPGRADE_2_3_UPDATE_DOCUMENT_STRUCTURE_FOR_VERSIONING

I obtain:
 07/11/2019 - 12:08:03 PM   INFO    : Task is starting ...
07/11/2019 - 12:08:03 PM   ERROR   : 1/10:Unhandled Exception in batch : org.linagora.linshare.core.upgrade.v2_3.UpgradeDocumentForVersionningImpl
07/11/2019 - 12:08:03 PM   ERROR   : Critical error for the current task. Task stopped.
07/11/2019 - 12:08:03 PM   ERROR   : Summary : success: 0, skipped: 9, errors: 0, unhandled errors: 1

The system seems to work correctly despite this error. 

Best regards

**Comment by yazidsebahi** [comment]
Hello, 

Thank you for the report, we will fix it soon.

Regards.

**Comment by yazidsebahi** [comment]
Hello @matdemb, Can you share with us your error log, please? 
Thanks.

**Comment by matdemb** [comment]
Hello,
where can I find it?
I don't find it in tomcat logs...
Regards,

**Comment by yazidsebahi** [comment]
On catalina.out

**Comment by matdemb** [comment]
Hello,
I previously did something wrong with my logs, there are all empty.
I check that and come back with the logs

**Comment by matdemb** [comment]
[log-update.txt](https://github.com/linagora/linshare/files/3401833/log-update.txt)
logs in attachment

**Comment by yazidsebahi** [comment]
Hello @matdemb, 

The problem has been fixed and will be published in our next release. 
However, you can download and try it using our snapshot. 
https://nexus.linagora.com/service/local/repositories/linshare-snapshots/content/org/linagora/linshare/linshare-core/2.3.1-SNAPSHOT/linshare-core-2.3.1-20190801.141022-3.war
Regards,

**Comment by matdemb** [comment]
Hello,
good news, thanks.
Regards,
