### ISSUE TITLE
workspace duration

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#76]
Hello,
is it in the roadmap the functionnality to put an expiration date for workgroup (and modify it after creation)?
The Sharedspace quota can be saturated and we have no way to know which workgroup saturate the space.
An automatic deletion of files or workspace will be great.

Best regards

**Comment by fmartin-linagora** [comment]
Hi,
No sorry, it is not planned at all. Expiration policy in shred spaces is a complicated stuff. They do not belong to some users in particular. they were designed to let people collaborate together on long term range.
Maybe a dashboard with some statistics and reporting will help you to monitor these shared spaces ?

**Comment by matdemb** [comment]
Hi,
a dashboard will be great!
Regards,

**Comment by faycalBordjah** [comment]
Hello, 
You can see this [EPIC](https://github.com/linagora/linshare/issues/103), related to dashboard feature that you propose, you can add a proposition about the subject.
Regards
