### ISSUE TITLE
Document cleaner

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#79]
Hello,
in the configuration file linshare.properties, we can find the section:
#******** Document cleaner
job.document.cleaner.activation=true
job.document.cleaner.cron.expression=0 0 0 1 1 ?

Is it still used? I tried to modified the cron.expression but the cleaner is always done at 00:30 every days and not at the indicated time of the cron.expression.

I would like to clean manually deleted files several times a day.
How can I do this?

Thanks

**Comment by fmartin-linagora** [comment]
Hello,
I suppose you are using a 2.x version of LinShare, I just take a look the the linshare.properties file and there is a glitch about it. The key `job.document.cleaner.cron.expression` is not used anymore since LinShare 2 release.

I'm updating the documentation right now and it will be available soon on github. you can see the update below:
```
# Batches are launched every days at 0a.m
# This cron is responsible of :
#   - deleting expired ShareEntries
#   - deleting expired AnonymousShareEntries
#   - deleting expired AnonymousUrl
#   - deleting "empty" ShareEntryGroup
#   - deleting expired DocumentEntries if it is activated. See job.document.cleaner.activation.
#   - deleting physically unused files (removing files from the file system, the object storage, ...)
#     aka the File Garbage Collector.
job.shares.cron.expression=0 30 0 * * ?

# There is a fail safe preventing to delete expired personal space documents, aka DocumentEntries.
# Even if the functionality is enabled and the batch/job triggered, YOU MUST allowed to delete them.
job.document.cleaner.activation=false


```

**Comment by marwanJebahi** [comment]
Hello matdemb,
The documentation about document batches are updated. I will close this issue, don't hesitate to back to us if you have questions.
Regards

**Comment by matdemb** [comment]
Hello,
If I delete a file in my personnal space, the suppression of datas on disk occure only at 00h30, whatever the job.shares.cron.expression value (I put 0 0,30 * * * for it).
Is it normal? 
Is it editable somewhere?
Regards,

**Comment by fmartin-linagora** [comment]
Hi,
Have you restarted the tomcat service ?
Which version of LinShare are you using ?

**Comment by matdemb** [comment]
Hi,
Sure I reboot tomcat. I see in logs that it's doing many jobs every 30 minutes.
My core version is 2.3.4.
Best regards,

**Comment by fmartin-linagora** [comment]
Hi,
It seems there is a glitch with your value, you make the job running every 30 minutes.
The defaut value is :  job.shares.cron.expression=0 30 0 * * ?
What is the goal you are trying to achieve ?

**Comment by matdemb** [comment]
Hi,
I configured it to have a clean at xh00 and xh30 . In logs, I see the Schedule works :
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1:20200608.130000:org.linagora.linshare.core.batches.impl.ComputeThumbnailBatchImpl:logInfo:Summary : success: 0, skipped: 0, errors: 0, unhandled errors: 0
[...]
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-3:20200608.133000:org.linagora.linshare.core.batches.impl.ComputeThumbnailBatchImpl:logInfo:Summary : success: 0, skipped: 0, errors: 0, unhandled errors: 0
[…]
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4:20200608.140000:org.linagora.linshare.core.batches.impl.ComputeThumbnailBatchImpl:logInfo:Summary : success: 0, skipped: 0, errors: 0, unhandled errors: 0

The default is to make the job at 00h30.
What I want finally, is when I delete a file in my personnal space, that it is freed on disk not only at 00h30, which is still the case with the parameter I choose.
Other batches (share cleaning,...) is less important for us.
The goal is to exchange several very big files one after one without saturating the server (we delete file after each transfert).
Today with a total space of 100Go, if I transfert and delete 2 files of 40Go, I have to wait the next day to continu because disk space is still 80Go used until 00h30.
I hope my problem is more clear..

Best regards,

**Comment by fmartin-linagora** [comment]
Hi,
Thank for your explanation, your goal is a lot clearer for me. I never faced this kind of needs. :) 

Be careful to not overlap the run of the same batch. Otherwise if there is a lot of data to process, it may takes some time and some resources may be processed twice or be missing. 

This job is not cleaning files it also clean almost all expired data like sharing, anonymous sharing, documents, etc... Maybe you can running it every hour ( job.users.cron.expression=0 0 * * * ?) but I'm not sure about side effects. It was not design for this.

You should look for DocumentGarbageCollectorBatchImpl traces instead of ComputeThumbnailBatchImpl traces in the logs.

Regards,

**Comment by matdemb** [comment]
Hi,
the DocumentGarbageCollectorBatchImpl is well executed every 30 minutes for me but still say "0 documents".
I will see which process delete them at midnight.
regards,

**Comment by matdemb** [comment]
Hi,
here my logs for the deletion of files at midnight:
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4:20200609.230000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Task is starting ...
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4:20200609.230000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:getAll:class org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl job starting ...
[DEBUG]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4:20200609.230000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:getAll:midnight : Tue Jun 09 00:00:00 CEST 2020
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4:20200609.230000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:getAll:0 document(s) have been found.
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4:20200609.230000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Total resource(s) : 0
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4:20200609.230000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:0 resource(s) have been deleted.
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4:20200609.230000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Task complete.
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4:20200609.230000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Summary : success: 0, skipped: 0, errors: 0, unhandled errors: 0
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-7:20200609.233000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Task is starting ...
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-7:20200609.233000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:getAll:class org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl job starting ...
[DEBUG]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-7:20200609.233000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:getAll:midnight : Tue Jun 09 00:00:00 CEST 2020
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-7:20200609.233000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:getAll:0 document(s) have been found.
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-7:20200609.233000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Total resource(s) : 0
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-7:20200609.233000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:0 resource(s) have been deleted.
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-7:20200609.233000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Task complete.
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-7:20200609.233000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Summary : success: 0, skipped: 0, errors: 0, unhandled errors: 0
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Task is starting ...
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:getAll:class org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl job starting ...
[DEBUG]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:getAll:midnight : Wed Jun 10 00:00:00 CEST 2020
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:getAll:4 document(s) have been found.
[DEBUG]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logDebug:1/4:processing resource '5edfb1e23aa2d5b033b38af2' ...
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:1/4:Orphan document Document [uuid=de769e1f-a632-4b25-830d-a8f77bbc837e, type=application/x-iso9660-image, size=4521459712, sha256sum=ec7500d4b006702af6af023b1f8f1b890b6c7ee54400bb98cef968b883cd6546, hasThumbnail=false] was removed.
[DEBUG]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logDebug:2/4:processing resource '5edfb5dd3aa2d5b033b38afd' ...
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:2/4:Orphan document Document [uuid=4161147e-2283-4787-b472-8aef281db869, type=application/zip, size=1205597465, sha256sum=1c6de54d983283e7cf58bd3c3c01d951db5750d8c9298422cfb82ad00dbd7b47, hasThumbnail=false] was removed.
[DEBUG]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logDebug:3/4:processing resource '5edfb5dd3aa2d5b033b38b00' ...
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:3/4:Orphan document Document [uuid=2dab4f5d-3c29-4d69-9dbe-fa20f6818009, type=application/zip, size=8252189311, sha256sum=d3b0848d28fefdba2beb7f637bcd90f839721a8b158011cda48a6fae5353a614, hasThumbnail=false] was removed.
[DEBUG]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logDebug:4/4:processing resource '5edfb5dd3aa2d5b033b38b01' ...
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:4/4:Orphan document Document [uuid=885068d0-bd26-4f1b-ad45-561cc2914776, type=application/zip, size=2525131544, sha256sum=9b120ca339adfdbe32dbb358497a91d32065f2212bf9f2d2f0bd287d0cadedf3, hasThumbnail=false] was removed.
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Total resource(s) : 4
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:4 resource(s) have been deleted.
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Task complete.
[INFO]:org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5:20200610.000000:org.linagora.linshare.core.batches.impl.DocumentGarbageCollectorBatchImpl:logInfo:Summary : success: 4, skipped: 0, errors: 0, unhandled errors: 0

There is this in logs: DocumentGarbageCollectorBatchImpl:getAll:midnight.
Is it why the deletion is at midnight?
Regards,

**Comment by fmartin-linagora** [comment]
Hi,
Yes, the batch is designed to remove orphan documents which have been deleted before midnight of the current day.

That's why the first run does not find any document to remove, and the second run remove them.
Regards,

**Comment by matdemb** [comment]
Hi,
is there a way to execute the batch several times by day?
Regards,

**Comment by fmartin-linagora** [comment]
Hi,
You can execute it as many time you want per day, but it will always remove orphan documents from the day before. Sorry I do not have any solution rght now for your use case.

Regards,
