### ISSUE TITLE
Subject of french-language sharing notification is "[user] vous a partagé un fichier avec vous"

### ISSUE THREAD

**Issue by Xyrop** [linagora/linshare#8]
And basically, the first "vous" is redundant. And grammar is one of the rare fields where redundancy is not a good thing...

**Comment by Klemele** [comment]
Hello!
Thanks for the feedback, we did create a related issue in our private CI and will fix it in the next sprint.
I let this issue open, to avoid redundancy ;).

**Comment by marwanJebahi** [comment]
Hello,
The issue is fixed on LinShare 2.1.1 version, here is the changelog:
https://github.com/linagora/linshare/blob/master/CHANGELOG.md#211-2018-05-28-download-link
Regards
