### ISSUE TITLE
Guest creation permission

### ISSUE THREAD

**Issue by edouard77** [linagora/linshare#83]
Hello
First of all, Thank you for your wonderful project LinShare
i have a question about Guest creation permission
by default, the active directory users have their role user as (SIMPLE), and once they log in the first time, they are added automatically to the LinShare Database however it is done with the option (guest creation permission) enabled
The goal is to limit guest creation permission to the role user (ADMINISTRATOR) only, so i wonder if there is a possibility to disable this option for the role user (SIMPLE)
Thank you

**Comment by marwanJebahi** [comment]
Hello Edouard77,
Thank you for your feedback, The behaviour now of guest creation right is: 
* If the functionality is enabled, all users whose will connect after will have the right to create a guest, except the administrator has the ability to diactive this functionality for some by unchecking this checkbox of `Guest creation permission` as we can see in the attached photo

![guest](https://user-images.githubusercontent.com/25078397/66902165-754a9880-f000-11e9-8e4f-de65d6761188.png)

Regards,

**Comment by edouard77** [comment]
Hi Marwan,
Yes i know i can disable this option user by user
my question is that i seek the opposite
"guest creation permission" disabled by default and enabled upon request by user
Thanks

**Comment by fmartin-linagora** [comment]
Hi Edouard77,
I do not known if it can help but most of the time I create one TopDomain with administrators and two nested (SubDomain) for regular (simple) users and for guests. I define the default profile os user in the TopDomain as ADMIN and let the two other domains with the default value (SIMPLE)
Then I enable the guest functionality only on the top domain.

Does it help ?

**Comment by edouard77** [comment]
Hi Marwan,
Yes it is a great idea, but it is not clear for me
my question is what users do you map for  the TopDomain administrators  ?
i have only one ActiveDirectory so it will be for the SubDomain AD
Thanks

**Comment by edouard77** [comment]
OK i understand, same LDAP mapping but another Base DN for User Provider
Thanks a lot for the tip

**Comment by linashare** [comment]
Yes, or you can use the same basedn but with a different ldap filter (based on an attribute)

**Comment by linashare** [comment]
Hello,
I forget to warn you, a user must be in ONLY one domain. Authentication will failed if the user is found in multiple domains.

Does it solve your issue ? Can we close this issue ?
Fred.

**Comment by marwanJebahi** [comment]
Hello edouard77,
Without any feedback, I guess your issue is fixed. I am closing this issue, feel free to reopen it if it is not the case.
Regards.
