### ISSUE TITLE
Searching Users

### ISSUE THREAD

**Issue by edouard77** [linagora/linshare#84]
Hello
1)
in (Users --> Manage Users), i cannot search by domain, the goal is to list just users from guest domain and i cannot find how to do it

2)
once i open user properties in (Users --> Manage Users), i can see (used space) for the selected user,  is there a way to list and sort users by their (used space) the goal is to have an idea about the users occupying the most space

Thanks

**Comment by linashare** [comment]
Hello,
Sorry, but both requested features are not implemented yet in the product.
Fred.

**Comment by fmartin-linagora** [comment]
I'm closing this issue, please feel free to open new issues, one per feature request.
