### ISSUE TITLE
Possible Bug, Deletion not working from WebGUI

### ISSUE THREAD

**Issue by edouard77** [linagora/linshare#85]
Hello
after i got an answer for my ticket "guest creation permission", i tried to do the following:

my initial domain config
RootDomain --> MyDomain --> GuestDomain
for the test, i was using 5 MyDomain users, 1 GuestDomain, and 1 external user

so i tried to reorganize my domains as:
RootDomain --> AdminDomain --> MyDomain & GuestDomain
(same domain names just different tree)

first operation was deleting GuestDomain, then deleting MyDomain 
i had a warning saying that all the users of the Domain will be deleted, then i agreed

second operation, was recreating the Domains

third operation:
trying to log with one of the 5 MyDomain users i got an unauthorized error
LDAP mapping works fine, i can see thse 5 users, i even added one of them manually to the LinShare Database, but i still cannot log in via the user WebGUI
these 5 users arent present in the inconsistent user list

so, i tried to check directly the database, and surprise !, in the account table all my past users are still here mapped to an old domain_id
the same thing in the domain_abstract table where i found the old domains  MyDomain & GuestDomain are still there

i spent one hour trying to delete the old accounts due to the multiple dependencies between tables
finally after cleaning the account and domain_abstract tables i was able to log without any issue

so is it a bug ? deletion done in the WebGUI but the changes arent reflected in the database

Thank You

**Comment by marwanJebahi** [comment]
Hello edouard77,
Thank you for your feedBack the team will investigate about it, and we will keep you informed about the new updates ASAP.
Regards,

**Comment by marwanJebahi** [comment]
Hello edouard77,
Thank you for your report, the team is working to fix this bug, it will be available in the next release of 2.3.2.
Regards,

**Comment by marwanJebahi** [comment]
Hello edouard77,
The bug was fixed on our last release 2.3.2, see the [changelog](https://github.com/linagora/linshare/blob/master/CHANGELOG.md#232-2019-11-13-download-link)
Regards.
