### ISSUE TITLE
Guest password complexity

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#86]
Hi,
the guest password complexity is still not tested.
So guests can choose a password of 1 character…
When it will be modified?

Regards,

**Comment by marwanJebahi** [comment]
Hello matdemb,
The team is working to improve the guest password complexity, it will be available in the next release of 2.3.2.
Regards,

**Comment by marwanJebahi** [comment]
Hello matdemb,
The bug was fixed on our last release 2.3.2, see the [changelog](https://github.com/linagora/linshare/blob/master/CHANGELOG.md#232-2019-11-13-download-link)
Regards.
