### ISSUE TITLE
init service not starting on docker

### ISSUE THREAD

**Issue by florinceleapca** [linagora/linshare#87]
docker-compose ps
          Name                         Command                   State                         Ports                  
----------------------------------------------------------------------------------------------------------------------
linshare_backend            /usr/local/bin/start.sh          Up (unhealthy)   8080/tcp                                
linshare_clamav             /bootstrap.sh                    Up               3310/tcp                                
linshare_database           docker-entrypoint.sh postgres    Up               5432/tcp                                
linshare_docker-socket      /docker-entrypoint.sh hapr ...   Up               2375/tcp                                
linshare_home               httpd-foreground                 Up               80/tcp                                  
linshare_init               /linagora/wait-for-it.sh - ...   Exit 1                                                   
linshare_ldap               /container/tool/run              Up               0.0.0.0:20389->389/tcp, 636/tcp         
linshare_mongodb            docker-entrypoint.sh mongo ...   Up               27017/tcp                               
linshare_reverse-proxy      /entrypoint.sh traefik           Up               0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
linshare_smtp               /usr/sbin/smtpd -d               Up               25/tcp, 587/tcp                         
linshare_thumbnail-server   java -jar -Djava.io.tmpdir ...   Up (healthy)     8080/tcp, 8081/tcp                      
linshare_ui-admin           httpd-foreground                 Up (unhealthy)   80/tcp                                  
linshare_ui-user            httpd-foreground                 Up (unhealthy)   80/tcp                                  

docker-compose logs init
linshare_init       | 15:48:59 WARNING : Current password is not valid.
linshare_init       | 15:48:59 INFO    : Trying to authenticate with the new provided password
linshare_init       | 15:48:59 ERROR   : Can't update the current password.

Any idea?
Thanks

**Comment by fmartin-linagora** [comment]
Hello,
I found the issue, there is a glitch in the latest backend docker image. I hope I will be able to release a new version of LinShare next week (2.3.2). It will fix this issue.
Fred.

**Comment by marwanJebahi** [comment]
Hello,
The bug was fixed on our last release 2.3.2, see the [changelog](https://github.com/linagora/linshare/blob/master/CHANGELOG.md#232-2019-11-13-download-link)
Regards.
