### ISSUE TITLE
guest expiration date

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#88]
Hello,
is it in the roadmap to have the possibility to modify the expiration date for a guest account?
It will be great to have this function for admin and/or creator account.
We can do that for shares but not for guest account...
Thanks,

**Comment by fmartin-linagora** [comment]
Hello,
It is already the case as a regular user (ui-user), you have a functionality called 'Postpone guest expiry date' which is enabled by default. It allows a regular use to update the guest expiration date. The maximum value is computed as follow : current date more default expiration duration.
Fred.

**Comment by matdemb** [comment]
Ho yes, I forgot this option!
Thanks to refresh my brain :-).
Sorry for this unsuseful ticket.

**Comment by fmartin-linagora** [comment]
No worries.
