### ISSUE TITLE
Cant Setup psql

### ISSUE THREAD

**Issue by ndcsilent** [linagora/linshare#89]
O.S centos 7
linshare 2.3

Hi Anyone can explain how to fix this one? newbie here.
![psql setup](https://user-images.githubusercontent.com/51688278/67774112-c2fee080-fa97-11e9-9f8c-c5ae1b89adf6.png)

**Comment by ndcsilent** [comment]
Hi Thanks for he helpi have a lot of question hope you can guide me.

do i need to make this folder? linshare_data
![linshare_data](https://user-images.githubusercontent.com/51688278/67825299-d6479580-fb03-11e9-87e7-1f5eb614b0b3.PNG)

**Comment by fmartin-linagora** [comment]
Hello ndsilent,
The installation guide was updated : https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-centos.md
Regards,
