### ISSUE TITLE
first login issue with 2.0.3

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#9]
Hi,
after installing linshare, I tried to login with default account but the system respon "bad credential".
I looked at the account table of the database, no entry...
I looked at the import-postgresql.sql file, I copy the insert of the admin account and I obtain an error message. something like
constraint key violation for column purge_step.

There is no value for column purge_step but it should.

What value can I put to make it work?
Is there others errors in the import file?

Thanks.

**Comment by fmartin-linagora** [comment]
Where did your get the import-postgresql script ? from master ? Or did you download this [archive](http://download.linshare.org/service/local/artifact/maven/content?r=linshare-releases&g=org.linagora.linshare&a=linshare-core&v=2.0.3&p=tar.bz2&c=sql) ?

**Comment by matdemb** [comment]
I download it on http://download.linshare.org/versions/2.0.3/ .
In fact after analysing the creation script, I saw that there was a default value on this parameter so this error shouldn't exist.
I delete the database and do the creation/import procedure a second time and this time everything was OK...
I don't know what happened the first time.

**Comment by fmartin-linagora** [comment]
Ok, thank you for your answer.
