### ISSUE TITLE
Workgroup space

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#90]
Hello,
is there a way to configure a workgroup max size?
In "manage domain quota" we can specify the _Personal Spaces quota_ and _Personal Spaces allocated quota_ for user side.
For workgroups, we can configure the _Sharedspace quota_ but not the _Workgroup allocated quota_ .
So with a sharedspace quota of 20GB, if a workspace use 19GB, it only remain 1GB for others workspace.
Am I right?
Regards,

**Comment by fmartin-linagora** [comment]
Without any feedback, I'm closing this issue.
