### ISSUE TITLE
Creation of Folder linshare_data

### ISSUE THREAD

**Issue by ndcsilent** [linagora/linshare#91]
Do i have to create the folder? 

![linshare_data](https://user-images.githubusercontent.com/51688278/67907672-b079c980-fbb3-11e9-8abe-3072eb0d76b0.PNG)

**Comment by fmartin-linagora** [comment]
Hello ndsilent,
The installation guide was updated : https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-centos.md
Regards,
