### ISSUE TITLE
guest password

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#94]
Hi,
I just saw that you correct the password complexity in last version so I wanted to try it.
Bad news.
It seems that some special characters are not considers as it.
for example "!" is not ok.
What are for you "special characters"?
Another thing, the error message is in english even for french interface and is still to fast to disappear (like all error messages).
Thanks.

**Comment by faycalBordjah** [comment]
Hello,
- About the special character "!" , I've created a password with "!" character. I have not the issue, maybe you just not respect the constraint :+1: 
* at least 8 character
* one number 
* mixture of lowercase and uppercase letters 
* special character .

- About the displayed error message, it is the case , even on french version, it is in english.
This issue will be handled as soon as possible.
Regards

**Comment by matdemb** [comment]
Hello,
the only difference between my 2 tests is the last character was "!", and I change to "=".
The first test was bad, the second OK.
One upercase character, 3 lowercase character, 4 Numbers and a one special character.
I will test again later, my test server doesn't work anymore after a security package update…
Something wrong with ldap...

**Comment by matdemb** [comment]
I try again, same result.
If I have "!" in my password, it doesn't work, if I change it for "=" it work, whatever the position of the special character...

**Comment by faycalBordjah** [comment]
OK
I'll investigate, and I give u return.

**Comment by faycalBordjah** [comment]
effectively there is an issue with "!".
We will handle it as soon as possible.
Regards

**Comment by faycalBordjah** [comment]
Fixed, it'll be available on next release 
Regards

**Comment by faycalBordjah** [comment]
Hello,
You can download the last update of LinShare core  [here](https://nexus.linagora.com/content/repositories/linshare-snapshots/org/linagora/linshare/linshare-core/2.3.3-SNAPSHOT/linshare-core-2.3.3-20191029.181111-1.war)
Regards

**Comment by matdemb** [comment]
Hello,
It's ok now. 
Thanks.

**Comment by faycalBordjah** [comment]
Your welcome, don't hesitate to submit other issues, or propositions.
Regards
