### ISSUE TITLE
linshare_ui_user on port 443 problem

### ISSUE THREAD

**Issue by omarie56** [linagora/linshare#95]
Hello,

I use linshare V2.31 and everything work fine. Thanks for excelent job.

I'm just trying to change linshare_ui_user virtualhost to acces web application on port 443.

i just change this
<VirtualHost ***:443**>
ServerName xxx.ville-auray.fr
DocumentRoot /var/www/linshare-ui-user

    SSLengine on
    SSLCertificateFile        /etc/pki/tls/certs/wildcard.ville-auray.fr.crt
    SSLCertificatekeyFile    /etc/pki/tls/certs/wildcard.ville-auray.fr.key

After rebooting httpd, i'm redirect on admin interface when i'm laugthing user interface url.

any idea ? it is possible to have both user and admin interface listening on port 443 ?

i tried to put only user interface on https but the problem is the same.

thanks a lot

**Comment by fmartin-linagora** [comment]
Hi,
You may have a glitch in your Apache configuration. Which distribution are you using ?
Maybe running the following command will help you to know what is going wrong : `apachectl -S`

**Comment by omarie56** [comment]
Hi martin,

I'm using Centos 7 distribution.

This is the result of the apachectl -S command

apachectl -S
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using srv-transfert.localdomain. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   transfert-admin.ville-auray.fr (/etc/httpd/conf.d/linshare-ui-admin.conf:1)
*:443                  is a NameVirtualHost
         default server transfert.ville-auray.fr (/etc/httpd/conf.d/linshare-ui-user.conf:1)
         port 443 namevhost transfert.ville-auray.fr (/etc/httpd/conf.d/linshare-ui-user.conf:1)
         port 443 namevhost srv-transfert.localdomain (/etc/httpd/conf.d/ssl.conf:56)
ServerRoot: "/etc/httpd"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/etc/httpd/logs/error_log"
Mutex mpm-accept: using_defaults
Mutex authdigest-opaque: using_defaults
Mutex proxy-balancer-shm: using_defaults
Mutex rewrite-map: using_defaults
Mutex authdigest-client: using_defaults
Mutex ssl-stapling: using_defaults
Mutex proxy: using_defaults
Mutex authn-socache: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/run/httpd/" mechanism=default
PidFile: "/run/httpd/httpd.pid"
Define: _RH_HAS_HTTPPROTOCOLOPTIONS
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="apache" id=48
Group: name="apache" id=48

the result refert to ssl.conf. Di you think i must remove this configuration file ?

thanks

**Comment by omarie56** [comment]
Martin,

sorry for the disturbance.

I just find my problem. It what only a mozilla firefow caching problem.

Before putting user interface in https, i tried tu put admin interface in https. i thing a had a cookie or any thing else that redirected me in admin interface.

I just clear mozilla cache and every thing is ok now.

Have a good day
