### ISSUE TITLE
document purge issue

### ISSUE THREAD

**Issue by matdemb** [linagora/linshare#97]
Hello,
on my installation, if I look at table document in psql database, I can see documents older than several months.
Documents should be deleted when there are more than 1 month.
Is there a purge issue after a previous update (I have documents before october but nothing after until 2 weeks ago)?
Is it shared workspace documents?
My entry table show only one document.

Thanks.

**Comment by marwanJebahi** [comment]
Hello matdemb,
Thank you for your report, on which version of LinShare please?

**Comment by matdemb** [comment]
Hello,
I have the issue on 3.3.1 and 3.2.0.
Regards,

**Comment by fmartin-linagora** [comment]
Hello,
the psql table `documents` represents all documents stored in LinShare, it could be a document in `My Files` or in `shared spaces` (aka `Workgroups`)

The expiration policy of documents are only apply to `My files`, and these documents(with their expiration dates) are store in the entry/document_entry tables of psql.

One a entry is expired, it is removed and the document_uuid is added to the GarbageCollector collection (mongodb). Then, the GarbageCollector will decide later to remove physically the document if there is no references anymore.

Does it answer to you question ?

**Comment by matdemb** [comment]
Thanks for all this explainations!
The strange thing is that on my test server, nobody use it and I have deleted all old workspaces with adminUI. I only have 1 document in a new shared space on my test user.
So I should have only one document in databases, isn't it?
In entry and document_entry, I have 1 line (normal) but in document table , I have several ones (389).
Is it normal?

**Comment by fmartin-linagora** [comment]
Hi,
By default the garbage collector is running every night at 0h30 and will remove useless documents.
Do you have some entries in the work_group_nodes collection (mongodb) ?

**Comment by matdemb** [comment]
Hi,
I have one entry in this table (the one I created).
The deletion of older Workgroups has been done several days/weeks ago.

**Comment by fmartin-linagora** [comment]
Can you confirm that you have only one entry in the table **workgroups** int pg database and 0 entry in the mongo collection named **work_group_nodes** ?

**Comment by matdemb** [comment]
I have 1 entry in work_group_nodes collection in mongo and there is no workgroups table in pg database:
Schéma |                     Nom                      |   Type   | Propriétaire
--------+----------------------------------------------+----------+--------------
 public | account                                      | table    | linshare
 public | account_permission                           | table    | linshare
 public | alias_func_list_all                          | vue      | linshare
 public | alias_threads_list_active                    | vue      | linshare
 public | alias_threads_list_all                       | vue      | linshare
 public | alias_threads_list_destroyed                 | vue      | linshare
 public | allowed_contact                              | table    | linshare
 public | anonymous_share_entry                        | table    | linshare
 public | anonymous_url                                | table    | linshare
 public | async_task                                   | table    | linshare
 public | batch_history                                | table    | linshare
 public | contact                                      | table    | linshare
 public | contact_provider                             | table    | linshare
 public | cookie                                       | table    | linshare
 public | document                                     | table    | linshare
 public | document_entry                               | table    | linshare
 public | domain_abstract                              | table    | linshare
 public | domain_access_policy                         | table    | linshare
 public | domain_access_rule                           | table    | linshare
 public | domain_policy                                | table    | linshare
 public | entry                                        | table    | linshare
 public | functionality                                | table    | linshare
 public | functionality_boolean                        | table    | linshare
 public | functionality_enum_lang                      | table    | linshare
 public | functionality_integer                        | table    | linshare
 public | functionality_string                         | table    | linshare
 public | functionality_unit                           | table    | linshare
 public | group_provider                               | table    | linshare
 public | hibernate_sequence                           | séquence | linshare
 public | ldap_attribute                               | table    | linshare
 public | ldap_connection                              | table    | linshare
 public | ldap_pattern                                 | table    | linshare
 public | log_entry                                    | table    | linshare
 public | mail_activation                              | table    | linshare
 public | mail_attachment                              | table    | linshare
 public | mail_config                                  | table    | linshare
 public | mail_content                                 | table    | linshare
 public | mail_content_lang                            | table    | linshare
 public | mail_footer                                  | table    | linshare
 public | mail_footer_lang                             | table    | linshare
 public | mail_layout                                  | table    | linshare
 public | mail_notification                            | table    | linshare
 public | mailing_list                                 | table    | linshare
 public | mailing_list_contact                         | table    | linshare
 public | mime_policy                                  | table    | linshare
 public | mime_type                                    | table    | linshare
 public | operation_history                            | table    | linshare
 public | policy                                       | table    | linshare
 public | quota                                        | table    | linshare
 public | recipient_favourite                          | table    | linshare
 public | share_entry                                  | table    | linshare
 public | share_entry_group                            | table    | linshare
 public | share_expiry_rules                           | table    | linshare
 public | signature                                    | table    | linshare
 public | statistic                                    | table    | linshare
 public | technical_account_permission                 | table    | linshare
 public | technical_account_permission_domain_abstract | table    | linshare
 public | thread                                       | table    | linshare
 public | thread_entry                                 | table    | linshare
 public | thread_member                                | table    | linshare
 public | thumbnail                                    | table    | linshare
 public | unit                                         | table    | linshare
 public | upgrade_task                                 | table    | linshare
 public | upload_proposition                           | table    | linshare
 public | upload_proposition_action                    | table    | linshare
 public | upload_proposition_filter                    | table    | linshare
 public | upload_proposition_rule                      | table    | linshare
 public | upload_request                               | table    | linshare
 public | upload_request_entry                         | table    | linshare
 public | upload_request_group                         | table    | linshare
 public | upload_request_history                       | table    | linshare
 public | upload_request_template                      | table    | linshare
 public | upload_request_url                           | table    | linshare
 public | user_provider                                | table    | linshare
 public | version                                      | table    | linshare
 public | welcome_messages                             | table    | linshare
 public | welcome_messages_entry                       | table    | linshare

**Comment by fmartin-linagora** [comment]
Hi,
Is it still the case or can we close this issue ?

**Comment by matdemb** [comment]
Hi,
we can close it yes.
Thanks
