### ISSUE TITLE
Prompting to install linshare-ui-admin even if exists

### ISSUE THREAD

**Issue by arjungprs** [linagora/linshare#98]
Hi,
I am getting this error when I access http://myip/linshare :

Welcome to LinShare Core. LinShare is up and running ! please Install linshare-ui-admin component to configure LinShare.

I am able to see the admin ui in here : http://myip

I followed the exact steps from here : https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-centos.md
Kindly advise what needs to be done.
Thanks
ajp

**Comment by fmartin-linagora** [comment]
Hi,
You must not try to access the service using your IP, you must use the virtual names defined in the documentation, cf https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-centos.md#first-access

**Comment by arjungprs** [comment]
Hi fmartin,
I am using  a Centos 7 VPS and it doensn't have a desktop. You mean, it has to be a centos with desktop to try it out please? I am able to access the admin ui using ip.
Thanks,
Arjun

**Comment by fmartin-linagora** [comment]
Hi,
You must not try to access the service using your IP, you must use the virtual names defined in the README. In your case, you have to add into the /etc/hosts of your computer the following line :

VPS_IP admin.linshare.local user.linshare.local linshare.local traefik.linshare.local

then go to your brower to http://admin.linshare.local.

**Comment by fmartin-linagora** [comment]
I suppose it answered to your questions, i'm closing this issue. Please feel free to reopen it if needed.
