### ISSUE TITLE
page not found when using linshare-docker

### ISSUE THREAD

**Issue by arjungprs** [linagora/linshare#99]
Hi,
I am setting up the linshare -docker in centos 7. I am getting "page not found" when I hit the http://myvpsipaddress. I am using VPS server. Could you please help to start debugging this please

> 
[root@centos-01 linshare-docker]# docker-compose up -d
Starting linshare_mongodb          ... done
Starting linshare_ldap             ... done
Starting linshare_init             ... done
Starting linshare_thumbnail-server ... done
Starting linshare_docker-socket    ... done
Starting linshare_database         ... done
Starting linshare_smtp             ... done
Starting linshare_home             ... done
Starting linshare_reverse-proxy    ... done
Starting linshare_clamav           ... done
Starting linshare_backend          ... done
Starting linshare_ui-user          ... done
Starting linshare_ui-admin         ... done

Thanks,
Ajp

**Comment by fmartin-linagora** [comment]
Hi,
You must not try to access the service using your IP, you must use the virtual names defined in the README, cf:
`127.0.0.1 admin.linshare.local user.linshare.local linshare.local traefik.linshare.local`

**Comment by arjungprs** [comment]
Hi fmartin, 
I am using a vps server, How do I access this from outside please?
Thanks
Arjun

**Comment by arjungprs** [comment]
Hi fmartin,
I setup a virtual machine with centos 7 (desktop) and tried. I was able to get the linshare.local running. But not the admin ui and user ui. Could you please adivise. This is the log :

inshare_backend    | java.io.FileNotFoundException: /etc/linshare/id_rsa (No such file or directory)
linshare_backend    | 	at java.io.FileInputStream.open0(Native Method)
linshare_backend    | 	at java.io.FileInputStream.open(FileInputStream.java:195)
linshare_backend    | 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
linshare_backend    | 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
linshare_backend    | 	at java.io.FileReader.<init>(FileReader.java:58)
linshare_backend    | 	at org.linagora.linshare.core.utils.PemRsaKeyHelper.loadPemKey(PemRsaKeyHelper.java:118)
linshare_backend    | 	at org.linagora.linshare.core.utils.PemRsaKeyHelper.loadPrivateKey(PemRsaKeyHelper.java:63)
linshare_backend    | 	at org.linagora.linshare.core.utils.PemRsaKeyHelper.loadKeys(PemRsaKeyHelper.java:99)
linshare_backend    | 	at org.linagora.linshare.core.service.impl.JwtServiceImpl.<init>(JwtServiceImpl.java:89)
linshare_backend    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
linshare_backend    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
linshare_backend    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
linshare_backend    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
linshare_backend    | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
linshare_backend    | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
linshare_backend    | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:299)
linshare_backend    | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:284)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
linshare_backend    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
linshare_backend    | 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367)
linshare_backend    | 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
linshare_backend    | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:674)
linshare_backend    | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:188)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
linshare_backend    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
linshare_backend    | 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367)
linshare_backend    | 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
linshare_backend    | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:674)
linshare_backend    | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:188)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
linshare_backend    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
linshare_backend    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
linshare_backend    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
linshare_backend    | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
linshare_backend    | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
linshare_backend    | 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
linshare_backend    | 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
linshare_backend    | 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
linshare_backend    | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
linshare_backend    | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
linshare_backend    | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
linshare_backend    | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
linshare_backend    | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
linshare_backend    | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
linshare_backend    | 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:980)
linshare_backend    | 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1851)
linshare_backend    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
linshare_backend    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
linshare_backend    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
linshare_backend    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
linshare_backend    | 	at java.lang.Thread.run(Thread.java:748)
linshare_backend    | [INFO]:localhost-startStop-1:20200121.011752:org.linagora.linshare.core.utils.PemRsaKeyHelper:loadPrivateKey:Private key '/etc/linshare/id_rsa' was not found. (check read access)
linshare_backend    | [DEBUG]:localhost-startStop-1:20200121.011752:org.linagora.linshare.core.utils.PemRsaKeyHelper:loadPemKey:/etc/linshare/id_rsa.pub (No such file or directory)
linshare_backend    | java.io.FileNotFoundException: /etc/linshare/id_rsa.pub (No such file or directory)
linshare_backend    | 	at java.io.FileInputStream.open0(Native Method)
linshare_backend    | 	at java.io.FileInputStream.open(FileInputStream.java:195)
linshare_backend    | 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
linshare_backend    | 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
linshare_backend    | 	at java.io.FileReader.<init>(FileReader.java:58)
linshare_backend    | 	at org.linagora.linshare.core.utils.PemRsaKeyHelper.loadPemKey(PemRsaKeyHelper.java:118)
linshare_backend    | 	at org.linagora.linshare.core.utils.PemRsaKeyHelper.loadSSHPublicKeyFromFile(PemRsaKeyHelper.java:76)
linshare_backend    | 	at org.linagora.linshare.core.utils.PemRsaKeyHelper.loadKeys(PemRsaKeyHelper.java:100)
linshare_backend    | 	at org.linagora.linshare.core.service.impl.JwtServiceImpl.<init>(JwtServiceImpl.java:89)
linshare_backend    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
linshare_backend    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
linshare_backend    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
linshare_backend    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
linshare_backend    | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
linshare_backend    | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
linshare_backend    | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:299)

**Comment by fred49** [comment]
Hi,
This error maybe just a warning that the /etc/linshare/id_rsa file is missing. It is only required if you use the JWT functionality. So for basic usage, it is not an issue.

You must not try to access the service using your IP, you must use the virtual names defined in the README. In you case, you have to add to the /etc/hosts of your computer the following line :

`VPS_IP admin.linshare.local user.linshare.local linshare.local traefik.linshare.local`

then go to your brower to http://admin.linshare.local.

**Comment by arjungprs** [comment]
Hi fred49,
This is setup is using linux centos with desktop and not using IP.  I am accessing using the http://admin.linshare.local and getting the error.
These are the screen shots :
https://ibb.co/gRGnD99

Docker ran successfully : 
https://ibb.co/qRp0mmm

**Comment by fmartin-linagora** [comment]
Hi,
I improved the readme of the linshare-docker, now you can now if your dokcer-compose is running properly: https://github.com/linagora/linshare-docker#how-to-use-it

**Comment by fmartin-linagora** [comment]
so you need to run the following command: `docker-compose ps`

**Comment by arjungprs** [comment]
Hi Fred,
I ran the command and it started working. I am confused, that command suppose to do a check but it fixed it too? Thank you very much for updating it.
https://ibb.co/ykhqMGp

Thanks

**Comment by fmartin-linagora** [comment]
Hi,
this command does nothing except showing you the current status of containers.
For the record, you should have *Up (healthy)* status when backend container is ready, the ui-user and ui-admin should be healty too.

**Comment by arjungprs** [comment]
Thanks @fmartin-linagora
